// SSC CGL — General Awareness: ART & CULTURE (100 questions)
// Bilingual (English + Hindi), CGL level.

export const artCultureMeta = {
  title: "Art & Culture — 100 Practice Questions",
  exam: "SSC CGL — General Awareness",
  total: 100,
  note: "SSC CGL level Art & Culture questions (Classical/Folk dances, festivals, music, instruments & exponents, temples, painting). Bilingual English + हिंदी.",
};

export const artCultureSections = [
  {
    id: "dances",
    name: "Classical & Folk Dances",
    questions: [
      { q: "Bharatanatyam is the classical dance of which state?", hi: "भरतनाट्यम किस राज्य का शास्त्रीय नृत्य है?", options: ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh"], answer: 0, explain: "Bharatanatyam Tamil Nadu ka classical dance hai." },
      { q: "Kathak is the classical dance mainly associated with:", hi: "कथक मुख्यतः किस क्षेत्र से जुड़ा शास्त्रीय नृत्य है?", options: ["North India (UP)", "Kerala", "Odisha", "Assam"], answer: 0, explain: "Kathak North India (UP) ka classical dance hai." },
      { q: "Kathakali is the classical dance of:", hi: "कथकली किस राज्य का शास्त्रीय नृत्य है?", options: ["Kerala", "Tamil Nadu", "Odisha", "Manipur"], answer: 0, explain: "Kathakali Kerala ka classical dance hai (colourful makeup)." },
      { q: "Odissi is the classical dance of:", hi: "ओडिसी किस राज्य का शास्त्रीय नृत्य है?", options: ["Odisha", "Kerala", "Tamil Nadu", "Andhra Pradesh"], answer: 0, explain: "Odissi Odisha ka classical dance hai." },
      { q: "Kuchipudi is the classical dance of:", hi: "कुचिपुड़ी किस राज्य का शास्त्रीय नृत्य है?", options: ["Andhra Pradesh", "Kerala", "Tamil Nadu", "Karnataka"], answer: 0, explain: "Kuchipudi Andhra Pradesh ka classical dance hai." },
      { q: "Manipuri is the classical dance of:", hi: "मणिपुरी किस राज्य का शास्त्रीय नृत्य है?", options: ["Manipur", "Assam", "Nagaland", "Tripura"], answer: 0, explain: "Manipuri Manipur ka classical dance hai (Raslila)." },
      { q: "Mohiniyattam is the classical dance of:", hi: "मोहिनीअट्टम किस राज्य का शास्त्रीय नृत्य है?", options: ["Kerala", "Tamil Nadu", "Karnataka", "Odisha"], answer: 0, explain: "Mohiniyattam Kerala ka classical dance hai (feminine, graceful)." },
      { q: "Sattriya is the classical dance of:", hi: "सत्रीया किस राज्य का शास्त्रीय नृत्य है?", options: ["Assam", "Manipur", "Nagaland", "Bengal"], answer: 0, explain: "Sattriya Assam ka classical dance hai (Vaishnav monasteries)." },
      { q: "Bhangra is the folk dance of:", hi: "भांगड़ा किस राज्य का लोक नृत्य है?", options: ["Punjab", "Haryana", "Rajasthan", "Gujarat"], answer: 0, explain: "Bhangra Punjab ka lok nritya hai." },
      { q: "Garba is the folk dance of:", hi: "गरबा किस राज्य का लोक नृत्य है?", options: ["Gujarat", "Rajasthan", "Punjab", "Maharashtra"], answer: 0, explain: "Garba Gujarat ka lok nritya hai (Navratri)." },
      { q: "Bihu is the folk dance of:", hi: "बिहू किस राज्य का लोक नृत्य है?", options: ["Assam", "Bengal", "Odisha", "Bihar"], answer: 0, explain: "Bihu Assam ka lok nritya hai (harvest festival)." },
      { q: "Ghoomar is the folk dance of:", hi: "घूमर किस राज्य का लोक नृत्य है?", options: ["Rajasthan", "Gujarat", "Punjab", "Haryana"], answer: 0, explain: "Ghoomar Rajasthan ka lok nritya hai." },
      { q: "Lavani is the folk dance of:", hi: "लावणी किस राज्य का लोक नृत्य है?", options: ["Maharashtra", "Gujarat", "Karnataka", "Goa"], answer: 0, explain: "Lavani Maharashtra ka lok nritya hai." },
      { q: "Yakshagana is a folk theatre-dance of:", hi: "यक्षगान किस राज्य का लोक नाट्य-नृत्य है?", options: ["Karnataka", "Kerala", "Tamil Nadu", "Andhra Pradesh"], answer: 0, explain: "Yakshagana Karnataka ka lok theatre-dance hai." },
      { q: "Chhau dance is associated with which states?", hi: "छऊ नृत्य किन राज्यों से जुड़ा है?", options: ["Jharkhand, Odisha, West Bengal", "Punjab", "Kerala", "Gujarat"], answer: 0, explain: "Chhau Jharkhand, Odisha, West Bengal ka mask-based martial dance hai." },
      { q: "Kalbelia is the folk dance of:", hi: "कालबेलिया किस राज्य का लोक नृत्य है?", options: ["Rajasthan", "Gujarat", "Punjab", "MP"], answer: 0, explain: "Kalbelia Rajasthan (snake charmers) ka lok nritya hai (UNESCO)." },
      { q: "Kuchipudi originated in which state's village?", hi: "कुचिपुड़ी किस राज्य के गाँव से उत्पन्न हुआ?", options: ["Andhra Pradesh", "Tamil Nadu", "Karnataka", "Kerala"], answer: 0, explain: "Kuchipudi Andhra Pradesh ke Kuchipudi gaon se aaya." },
      { q: "Which dance form is associated with Lord Shiva's Tandava?", hi: "कौन-सा नृत्य भगवान शिव के तांडव से जुड़ा है?", options: ["Bharatanatyam (Nataraja)", "Garba", "Bhangra", "Bihu"], answer: 0, explain: "Bharatanatyam Nataraja (Shiva) ke Tandava se juda hai." },
      { q: "Rouf is the folk dance of:", hi: "रऊफ किस राज्य का लोक नृत्य है?", options: ["Jammu & Kashmir", "Himachal", "Punjab", "Ladakh"], answer: 0, explain: "Rouf Jammu & Kashmir ka lok nritya hai." },
      { q: "Which is a folk dance of Himachal Pradesh?", hi: "हिमाचल प्रदेश का लोक नृत्य कौन-सा है?", options: ["Nati", "Bihu", "Garba", "Lavani"], answer: 0, explain: "Nati Himachal Pradesh ka lok nritya hai." },
    ],
  },
  {
    id: "music",
    name: "Music, Instruments & Exponents",
    questions: [
      { q: "Pandit Ravi Shankar was a maestro of which instrument?", hi: "पंडित रवि शंकर किस वाद्य के उस्ताद थे?", options: ["Sitar", "Tabla", "Sarod", "Flute"], answer: 0, explain: "Pandit Ravi Shankar Sitar ke maestro the." },
      { q: "Ustad Zakir Hussain is famous for playing the:", hi: "उस्ताद ज़ाकिर हुसैन किस वाद्य के लिए प्रसिद्ध हैं?", options: ["Tabla", "Sitar", "Sarod", "Santoor"], answer: 0, explain: "Ustad Zakir Hussain Tabla ke liye prasiddh hain." },
      { q: "Ustad Bismillah Khan was associated with the:", hi: "उस्ताद बिस्मिल्लाह खान किस वाद्य से जुड़े थे?", options: ["Shehnai", "Sitar", "Sarod", "Tabla"], answer: 0, explain: "Ustad Bismillah Khan Shehnai ke maestro the." },
      { q: "Pandit Hariprasad Chaurasia is famous for the:", hi: "पंडित हरिप्रसाद चौरसिया किस वाद्य के लिए प्रसिद्ध हैं?", options: ["Flute (Bansuri)", "Sitar", "Tabla", "Sarod"], answer: 0, explain: "Pandit Hariprasad Chaurasia Bansuri (flute) ke maestro hain." },
      { q: "Ustad Amjad Ali Khan is associated with the:", hi: "उस्ताद अमजद अली खान किस वाद्य से जुड़े हैं?", options: ["Sarod", "Sitar", "Tabla", "Shehnai"], answer: 0, explain: "Ustad Amjad Ali Khan Sarod ke maestro hain." },
      { q: "Pandit Shivkumar Sharma is famous for the:", hi: "पंडित शिवकुमार शर्मा किस वाद्य के लिए प्रसिद्ध हैं?", options: ["Santoor", "Sitar", "Tabla", "Flute"], answer: 0, explain: "Pandit Shivkumar Sharma Santoor ke maestro the." },
      { q: "M. S. Subbulakshmi was a legend of which music?", hi: "एम.एस. सुब्बुलक्ष्मी किस संगीत की महान गायिका थीं?", options: ["Carnatic (vocal)", "Hindustani", "Folk", "Sufi"], answer: 0, explain: "M. S. Subbulakshmi Carnatic vocal music ki legend thi (Bharat Ratna)." },
      { q: "The two main schools of Indian classical music are Hindustani and:", hi: "भारतीय शास्त्रीय संगीत के दो मुख्य घराने— हिंदुस्तानी और?", options: ["Carnatic", "Sufi", "Folk", "Bhajan"], answer: 0, explain: "Do schools: Hindustani (North) aur Carnatic (South)." },
      { q: "The Veena is primarily associated with which music tradition?", hi: "वीणा मुख्यतः किस संगीत परंपरा से जुड़ी है?", options: ["Carnatic", "Hindustani", "Western", "Folk"], answer: 0, explain: "Veena mukhyata Carnatic (South Indian) music se judi hai." },
      { q: "The 'Sarod' is a:", hi: "'सरोद' कैसा वाद्य है?", options: ["String instrument", "Wind instrument", "Percussion instrument", "Keyboard"], answer: 0, explain: "Sarod ek string (taar) vaadya hai." },
      { q: "The 'Tabla' is a:", hi: "'तबला' कैसा वाद्य है?", options: ["Percussion instrument", "String instrument", "Wind instrument", "Keyboard"], answer: 0, explain: "Tabla ek percussion (taal) vaadya hai." },
      { q: "The 'Shehnai' is a:", hi: "'शहनाई' कैसा वाद्य है?", options: ["Wind instrument", "String instrument", "Percussion", "Keyboard"], answer: 0, explain: "Shehnai ek wind (sushir) vaadya hai." },
      { q: "Bhimsen Joshi was a renowned:", hi: "भीमसेन जोशी एक प्रसिद्ध क्या थे?", options: ["Hindustani vocalist", "Sitar player", "Tabla player", "Dancer"], answer: 0, explain: "Bhimsen Joshi Hindustani classical vocalist the (Bharat Ratna)." },
      { q: "The 'Mridangam' is primarily used in:", hi: "'मृदंगम' मुख्यतः किसमें प्रयोग होता है?", options: ["Carnatic music", "Hindustani music", "Western music", "Folk music"], answer: 0, explain: "Mridangam Carnatic music ka mukhya percussion hai." },
      { q: "The 'Sitar' was popularised globally by:", hi: "'सितार' को विश्व स्तर पर किसने लोकप्रिय बनाया?", options: ["Pandit Ravi Shankar", "Zakir Hussain", "Bismillah Khan", "Amjad Ali Khan"], answer: 0, explain: "Pandit Ravi Shankar ne Sitar ko world-wide popular kiya." },
    ],
  },
  {
    id: "festivals",
    name: "Festivals",
    questions: [
      { q: "The festival 'Onam' is celebrated in:", hi: "'ओणम' त्योहार कहाँ मनाया जाता है?", options: ["Kerala", "Tamil Nadu", "Karnataka", "Andhra Pradesh"], answer: 0, explain: "Onam Kerala ka harvest festival hai." },
      { q: "The festival 'Pongal' is associated with:", hi: "'पोंगल' त्योहार किससे जुड़ा है?", options: ["Tamil Nadu", "Kerala", "Punjab", "Gujarat"], answer: 0, explain: "Pongal Tamil Nadu ka harvest festival hai." },
      { q: "'Bihu' festival is celebrated in:", hi: "'बिहू' त्योहार कहाँ मनाया जाता है?", options: ["Assam", "Bengal", "Odisha", "Bihar"], answer: 0, explain: "Bihu Assam ka festival hai." },
      { q: "'Baisakhi' is a harvest festival mainly of:", hi: "'बैसाखी' मुख्यतः किसका फसल त्योहार है?", options: ["Punjab", "Gujarat", "Kerala", "Tamil Nadu"], answer: 0, explain: "Baisakhi Punjab ka harvest festival hai (Sikh new year)." },
      { q: "The 'Hornbill Festival' is celebrated in:", hi: "'हॉर्नबिल महोत्सव' कहाँ मनाया जाता है?", options: ["Nagaland", "Manipur", "Mizoram", "Assam"], answer: 0, explain: "Hornbill Festival Nagaland ka hai ('Festival of Festivals')." },
      { q: "The 'Rann Utsav' is held in:", hi: "'रण उत्सव' कहाँ आयोजित होता है?", options: ["Gujarat (Kutch)", "Rajasthan", "MP", "Punjab"], answer: 0, explain: "Rann Utsav Gujarat (Kutch, white desert) me hota hai." },
      { q: "The 'Hemis Festival' is celebrated in:", hi: "'हेमिस महोत्सव' कहाँ मनाया जाता है?", options: ["Ladakh", "Sikkim", "Himachal", "Arunachal"], answer: 0, explain: "Hemis Festival Ladakh (Buddhist monastery) me hota hai." },
      { q: "'Chhath Puja' is mainly celebrated in:", hi: "'छठ पूजा' मुख्यतः कहाँ मनाई जाती है?", options: ["Bihar & UP", "Kerala", "Gujarat", "Punjab"], answer: 0, explain: "Chhath Puja Bihar aur UP me (Sun worship) manai jaati hai." },
      { q: "The 'Pushkar Fair' (camel fair) is held in:", hi: "'पुष्कर मेला' (ऊँट मेला) कहाँ आयोजित होता है?", options: ["Rajasthan", "Gujarat", "Punjab", "Haryana"], answer: 0, explain: "Pushkar Fair Rajasthan me lagta hai (camel/livestock fair)." },
      { q: "The 'Konark Dance Festival' is held in:", hi: "'कोणार्क नृत्य महोत्सव' कहाँ होता है?", options: ["Odisha", "Tamil Nadu", "Kerala", "Karnataka"], answer: 0, explain: "Konark Dance Festival Odisha (Sun Temple) me hota hai." },
      { q: "The 'Khajuraho Dance Festival' is held in:", hi: "'खजुराहो नृत्य महोत्सव' कहाँ होता है?", options: ["Madhya Pradesh", "UP", "Rajasthan", "Odisha"], answer: 0, explain: "Khajuraho Dance Festival Madhya Pradesh me hota hai." },
      { q: "'Losar' festival is celebrated by:", hi: "'लोसर' त्योहार कौन मनाता है?", options: ["Tibetan Buddhists (Ladakh/Sikkim)", "Sikhs", "Jains", "Christians"], answer: 0, explain: "Losar Tibetan Buddhist new year hai (Ladakh, Sikkim)." },
      { q: "The 'Thrissur Pooram' festival is in:", hi: "'त्रिशूर पूरम' त्योहार कहाँ होता है?", options: ["Kerala", "Tamil Nadu", "Karnataka", "Andhra Pradesh"], answer: 0, explain: "Thrissur Pooram Kerala ka temple festival hai (elephants)." },
      { q: "The 'Nagaur Fair' (cattle fair) is held in:", hi: "'नागौर मेला' (पशु मेला) कहाँ होता है?", options: ["Rajasthan", "Gujarat", "Punjab", "MP"], answer: 0, explain: "Nagaur Fair Rajasthan ka cattle fair hai." },
      { q: "'Wangala Festival' is celebrated by the Garo tribe of:", hi: "'वांगला महोत्सव' किस राज्य की गारो जनजाति मनाती है?", options: ["Meghalaya", "Assam", "Nagaland", "Mizoram"], answer: 0, explain: "Wangala Festival Meghalaya ki Garo janjati ka hai (harvest)." },
    ],
  },
  {
    id: "temples-arch",
    name: "Temples, Architecture & Heritage",
    questions: [
      { q: "The Sun Temple at Konark is in which state?", hi: "कोणार्क का सूर्य मंदिर किस राज्य में है?", options: ["Odisha", "Tamil Nadu", "Gujarat", "Karnataka"], answer: 0, explain: "Konark Sun Temple Odisha me hai (UNESCO)." },
      { q: "The Meenakshi Temple is located in:", hi: "मीनाक्षी मंदिर कहाँ स्थित है?", options: ["Madurai (Tamil Nadu)", "Thanjavur", "Kanchipuram", "Rameswaram"], answer: 0, explain: "Meenakshi Temple Madurai (Tamil Nadu) me hai." },
      { q: "The Brihadeeswarar Temple (Thanjavur) was built by the:", hi: "बृहदेश्वर मंदिर (तंजावुर) किसने बनवाया?", options: ["Cholas", "Pallavas", "Pandyas", "Chalukyas"], answer: 0, explain: "Brihadeeswarar Temple Chola raja Rajaraja I ne banवाya." },
      { q: "The Khajuraho temples are famous for:", hi: "खजुराहो के मंदिर किसके लिए प्रसिद्ध हैं?", options: ["Erotic sculptures (Nagara style)", "Rock-cut caves", "Sun worship", "Jain art only"], answer: 0, explain: "Khajuraho temples (Chandela) apni sculptures aur Nagara style ke liye prasiddh hain." },
      { q: "The Ajanta and Ellora caves are located in:", hi: "अजंता और एलोरा की गुफाएँ कहाँ स्थित हैं?", options: ["Maharashtra", "Karnataka", "MP", "Gujarat"], answer: 0, explain: "Ajanta-Ellora caves Maharashtra (Aurangabad) me hain." },
      { q: "The Taj Mahal is an example of which architecture?", hi: "ताजमहल किस स्थापत्य का उदाहरण है?", options: ["Mughal (Indo-Islamic)", "Dravidian", "Nagara", "Gothic"], answer: 0, explain: "Taj Mahal Mughal (Indo-Islamic) architecture ka udaharan hai." },
      { q: "The Sanchi Stupa is associated with which religion?", hi: "साँची स्तूप किस धर्म से जुड़ा है?", options: ["Buddhism", "Jainism", "Hinduism", "Sikhism"], answer: 0, explain: "Sanchi Stupa (MP) Buddhism se juda hai (Ashoka)." },
      { q: "The Golden Temple (Harmandir Sahib) is in:", hi: "स्वर्ण मंदिर (हरमंदिर साहिब) कहाँ है?", options: ["Amritsar (Punjab)", "Delhi", "Anandpur Sahib", "Patna"], answer: 0, explain: "Golden Temple Amritsar (Punjab) me hai (Sikh)." },
      { q: "The rock-cut temples at Mahabalipuram were built by the:", hi: "महाबलीपुरम के शैलकृत मंदिर किसने बनवाए?", options: ["Pallavas", "Cholas", "Pandyas", "Cheras"], answer: 0, explain: "Mahabalipuram rock-cut temples Pallava vansh ne banवाye." },
      { q: "The Kailasa Temple at Ellora was built by the:", hi: "एलोरा का कैलाश मंदिर किसने बनवाया?", options: ["Rashtrakutas", "Cholas", "Pallavas", "Chalukyas"], answer: 0, explain: "Kailasa Temple (Ellora) Rashtrakuta raja Krishna I ne banवाya." },
      { q: "The Dilwara Temples (Jain) are located at:", hi: "दिलवाड़ा मंदिर (जैन) कहाँ स्थित हैं?", options: ["Mount Abu (Rajasthan)", "Palitana", "Shravanabelagola", "Ranakpur"], answer: 0, explain: "Dilwara Temples Mount Abu (Rajasthan) me hain." },
      { q: "The Hampi ruins belong to which empire?", hi: "हम्पी के अवशेष किस साम्राज्य के हैं?", options: ["Vijayanagar", "Chola", "Mughal", "Maratha"], answer: 0, explain: "Hampi Vijayanagar Empire ki rajdhani thi." },
      { q: "The Qutub Minar was built in which architectural style?", hi: "कुतुब मीनार किस स्थापत्य शैली में बनी है?", options: ["Indo-Islamic", "Dravidian", "Nagara", "Vesara"], answer: 0, explain: "Qutub Minar Indo-Islamic style me hai." },
      { q: "The 'Nagara' style of temple architecture is found mainly in:", hi: "मंदिर स्थापत्य की 'नागर' शैली मुख्यतः कहाँ पाई जाती है?", options: ["North India", "South India", "East India only", "Northeast"], answer: 0, explain: "Nagara style mainly North India me (shikhara/curvilinear tower)." },
      { q: "The 'Dravida' style of temple architecture is found mainly in:", hi: "मंदिर स्थापत्य की 'द्रविड़' शैली मुख्यतः कहाँ पाई जाती है?", options: ["South India", "North India", "West India", "Northeast"], answer: 0, explain: "Dravida style mainly South India me (vimana/pyramidal tower + gopuram)." },
    ],
  },
  {
    id: "painting-misc",
    name: "Painting, Theatre & Miscellaneous",
    questions: [
      { q: "Madhubani painting originated in which state?", hi: "मधुबनी चित्रकला किस राज्य से उत्पन्न हुई?", options: ["Bihar", "Bengal", "Odisha", "Rajasthan"], answer: 0, explain: "Madhubani (Mithila) painting Bihar se aayi." },
      { q: "Warli painting is a folk art of:", hi: "वारली चित्रकला किसकी लोक कला है?", options: ["Maharashtra", "Gujarat", "Rajasthan", "MP"], answer: 0, explain: "Warli painting Maharashtra ki tribal folk art hai." },
      { q: "Pattachitra painting is associated with:", hi: "पट्टचित्र चित्रकला किससे जुड़ी है?", options: ["Odisha & West Bengal", "Punjab", "Kerala", "Gujarat"], answer: 0, explain: "Pattachitra Odisha aur West Bengal ki cloth-based painting hai." },
      { q: "Tanjore (Thanjavur) painting is famous for:", hi: "तंजौर चित्रकला किसके लिए प्रसिद्ध है?", options: ["Gold foil work", "Tribal motifs", "Miniature portraits", "Abstract art"], answer: 0, explain: "Tanjore painting apne gold foil (sona) work ke liye prasiddh hai (Tamil Nadu)." },
      { q: "Kalamkari art is associated with:", hi: "कलमकारी कला किससे जुड़ी है?", options: ["Andhra Pradesh", "Kerala", "Punjab", "Assam"], answer: 0, explain: "Kalamkari Andhra Pradesh ki hand-painted textile art hai." },
      { q: "Phad painting is a folk art of:", hi: "फड़ चित्रकला किसकी लोक कला है?", options: ["Rajasthan", "Gujarat", "Bihar", "Odisha"], answer: 0, explain: "Phad painting Rajasthan ki scroll painting hai." },
      { q: "The Mughal school of painting reached its peak under:", hi: "मुगल चित्रकला शैली अपने चरम पर किसके अधीन पहुँची?", options: ["Jahangir", "Babur", "Aurangzeb", "Humayun"], answer: 0, explain: "Mughal painting Jahangir ke samay charam par thi." },
      { q: "Ravi Varma (Raja Ravi Varma) was a famous:", hi: "राजा रवि वर्मा एक प्रसिद्ध क्या थे?", options: ["Painter", "Dancer", "Musician", "Sculptor"], answer: 0, explain: "Raja Ravi Varma prasiddh painter the (Indian gods in realistic style)." },
      { q: "'Kathakali' combines dance with which art form?", hi: "'कथकली' नृत्य को किस कला रूप के साथ जोड़ता है?", options: ["Theatre/drama", "Painting", "Sculpture", "Music only"], answer: 0, explain: "Kathakali dance-drama (theatre) hai (Kerala)." },
      { q: "'Ramlila' is a traditional theatrical enactment of:", hi: "'रामलीला' किसका पारंपरिक नाट्य रूपांतरण है?", options: ["Ramayana", "Mahabharata", "Bhagavad Gita", "Puranas"], answer: 0, explain: "Ramlila Ramayana ka natak roopantaran hai (UNESCO)." },
      { q: "The 'Sattriya' dance was created by:", hi: "'सत्रीया' नृत्य किसने बनाया?", options: ["Srimanta Sankardev", "Tyagaraja", "Amir Khusrau", "Swati Tirunal"], answer: 0, explain: "Sattriya Srimanta Sankardev (Assam Vaishnav saint) ne banaya." },
      { q: "'Miniature painting' flourished under which schools (besides Mughal)?", hi: "'लघुचित्रकला' मुगल के अलावा किन शैलियों में फली-फूली?", options: ["Rajput/Pahari", "Warli", "Madhubani", "Warli"], answer: 0, explain: "Miniature painting Rajput aur Pahari (Kangra) schools me bhi flourish hui." },
      { q: "The 'Cheraw' (bamboo dance) is performed in:", hi: "'चेरॉ' (बांस नृत्य) कहाँ किया जाता है?", options: ["Mizoram", "Nagaland", "Assam", "Manipur"], answer: 0, explain: "Cheraw (bamboo dance) Mizoram ka lok nritya hai." },
      { q: "'Gond art' is a tribal painting from:", hi: "'गोंड कला' किसकी जनजातीय चित्रकला है?", options: ["Madhya Pradesh", "Kerala", "Punjab", "Bengal"], answer: 0, explain: "Gond art Madhya Pradesh ki tribal painting hai." },
      { q: "The classical music treatise 'Natya Shastra' was written by:", hi: "शास्त्रीय संगीत/नाट्य ग्रंथ 'नाट्य शास्त्र' किसने लिखा?", options: ["Bharata Muni", "Kalidasa", "Tyagaraja", "Amir Khusrau"], answer: 0, explain: "Natya Shastra Bharata Muni ne likha (dance-drama-music ka aadhaar)." },
      { q: "'Bharatanatyam' derives its theoretical base from:", hi: "'भरतनाट्यम' का सैद्धांतिक आधार किससे है?", options: ["Natya Shastra", "Vedas", "Puranas", "Arthashastra"], answer: 0, explain: "Bharatanatyam ka aadhaar Bharata Muni ke Natya Shastra se hai." },
      { q: "The 'Dhrupad' is a genre of:", hi: "'ध्रुपद' किसकी शैली है?", options: ["Hindustani classical vocal", "Carnatic", "Folk", "Western"], answer: 0, explain: "Dhrupad Hindustani classical vocal ki prachin shaili hai." },
      { q: "The 'Thumri' is a form of:", hi: "'ठुमरी' किसका रूप है?", options: ["Semi-classical vocal music", "Dance", "Painting", "Instrument"], answer: 0, explain: "Thumri semi-classical vocal music hai (romantic/devotional)." },
      { q: "Amir Khusrau is credited with inventing the:", hi: "अमीर खुसरो को किसका आविष्कार करने का श्रेय है?", options: ["Sitar and Tabla (traditionally)", "Veena", "Flute", "Mridangam"], answer: 0, explain: "Amir Khusrau ko traditionally Sitar aur Tabla ke invention ka shrey diya jaata hai." },
      { q: "The 'Ghazal' is a form of:", hi: "'ग़ज़ल' किसका रूप है?", options: ["Poetry set to music", "Classical dance", "Folk painting", "Theatre"], answer: 0, explain: "Ghazal poetic form hai jo sangeet me gayi jaati hai." },
      { q: "The 'Qawwali' is a devotional music associated with:", hi: "'कव्वाली' भक्ति संगीत किससे जुड़ा है?", options: ["Sufism", "Sikhism", "Jainism", "Buddhism"], answer: 0, explain: "Qawwali Sufi bhakti sangeet hai." },
      { q: "'Rangoli' is a traditional art form of:", hi: "'रंगोली' किसकी पारंपरिक कला है?", options: ["Decorative floor art", "Wall painting", "Sculpture", "Weaving"], answer: 0, explain: "Rangoli decorative floor art hai (festivals)." },
      { q: "Pashmina shawls are famous from:", hi: "पश्मीना शॉल किसके लिए प्रसिद्ध हैं?", options: ["Kashmir", "Punjab", "Gujarat", "Assam"], answer: 0, explain: "Pashmina shawls Kashmir ke prasiddh hain." },
      { q: "Bandhani (tie-dye) textile art is famous in:", hi: "बंधनी (टाई-डाई) वस्त्र कला कहाँ प्रसिद्ध है?", options: ["Gujarat & Rajasthan", "Kerala", "Bengal", "Assam"], answer: 0, explain: "Bandhani Gujarat aur Rajasthan ki tie-dye textile art hai." },
      { q: "The 'Kanjeevaram' silk sarees are from:", hi: "'कांजीवरम' रेशमी साड़ियाँ कहाँ की हैं?", options: ["Tamil Nadu", "Karnataka", "Kerala", "Andhra Pradesh"], answer: 0, explain: "Kanjeevaram silk sarees Tamil Nadu (Kanchipuram) ki hain." },
      { q: "'Bidriware' metal handicraft is from:", hi: "'बिदरीवेयर' धातु शिल्प कहाँ का है?", options: ["Karnataka (Bidar)", "Rajasthan", "Gujarat", "Punjab"], answer: 0, explain: "Bidriware Karnataka (Bidar) ka metal handicraft hai." },
      { q: "The 'Kathputli' (puppet) art is famous in:", hi: "'कठपुतली' कला कहाँ प्रसिद्ध है?", options: ["Rajasthan", "Kerala", "Bengal", "Punjab"], answer: 0, explain: "Kathputli (string puppet) Rajasthan ki prasiddh kala hai." },
      { q: "The classical dance 'Bharatanatyam' was earlier known as:", hi: "शास्त्रीय नृत्य 'भरतनाट्यम' पहले किस नाम से जाना जाता था?", options: ["Sadir", "Dasi Attam", "Nautch", "Both Sadir & Dasi Attam"], answer: 3, explain: "Bharatanatyam pehle Sadir/Dasi Attam ke naam se jaana jaata tha." },
      { q: "'Tyagaraja' was a great composer of:", hi: "'त्यागराज' किसके महान संगीतकार थे?", options: ["Carnatic music", "Hindustani music", "Folk music", "Sufi music"], answer: 0, explain: "Tyagaraja Carnatic music ke mahान composer the (Trinity of Carnatic music)." },
      { q: "The 'Chikankari' embroidery is famous in:", hi: "'चिकनकारी' कढ़ाई कहाँ प्रसिद्ध है?", options: ["Lucknow (UP)", "Kashmir", "Gujarat", "Bengal"], answer: 0, explain: "Chikankari embroidery Lucknow (UP) ki prasiddh hai." },
      { q: "'Kolam' floor art is a tradition of:", hi: "'कोलम' फर्श कला किसकी परंपरा है?", options: ["Tamil Nadu", "Punjab", "Bengal", "Gujarat"], answer: 0, explain: "Kolam (rangoli jaisa) Tamil Nadu ki parampara hai." },
      { q: "The 'Sangeet Natak Akademi' promotes:", hi: "'संगीत नाटक अकादमी' किसे बढ़ावा देती है?", options: ["Music, dance & drama", "Painting", "Literature", "Films"], answer: 0, explain: "Sangeet Natak Akademi music, dance, drama ko badhava deti hai." },
      { q: "The 'Sahitya Akademi' is associated with:", hi: "'साहित्य अकादमी' किससे संबंधित है?", options: ["Literature", "Music", "Dance", "Painting"], answer: 0, explain: "Sahitya Akademi sahitya (literature) se sambandhit hai." },
      { q: "The 'Lalit Kala Akademi' promotes:", hi: "'ललित कला अकादमी' किसे बढ़ावा देती है?", options: ["Fine arts (painting/sculpture)", "Music", "Dance", "Drama"], answer: 0, explain: "Lalit Kala Akademi fine arts (painting, sculpture) ko badhava deti hai." },
      { q: "The classical dance 'Odissi' is often performed in temples dedicated to:", hi: "शास्त्रीय नृत्य 'ओडिसी' अक्सर किस देवता के मंदिरों में किया जाता था?", options: ["Lord Jagannath", "Lord Shiva", "Lord Vishnu", "Lord Ganesha"], answer: 0, explain: "Odissi Odisha ke Jagannath (Puri) mandiron se judi thi (Mahari tradition)." },
    ],
  },
];
