// SSC CGL — General Awareness: ECONOMICS (100 questions)
// Bilingual (English + Hindi), CGL level.

export const economicsMeta = {
  title: "Economics — 100 Practice Questions",
  exam: "SSC CGL — General Awareness",
  total: 100,
  note: "SSC CGL level Economics questions (GDP, inflation, fiscal/monetary policy, banking, budget, economic concepts). Bilingual English + हिंदी.",
};

export const economicsSections = [
  {
    id: "basics",
    name: "Basic Economic Concepts",
    questions: [
      { q: "GDP stands for:", hi: "GDP का पूर्ण रूप क्या है?", options: ["Gross Domestic Product", "Gross Domestic Payment", "General Domestic Product", "Gross Development Product"], answer: 0, explain: "GDP = Gross Domestic Product (kul gharelu utpad)." },
      { q: "GNP stands for:", hi: "GNP का पूर्ण रूप क्या है?", options: ["Gross National Product", "Gross Net Product", "General National Product", "Gross National Payment"], answer: 0, explain: "GNP = Gross National Product." },
      { q: "The study of individual economic units is called:", hi: "व्यक्तिगत आर्थिक इकाइयों के अध्ययन को क्या कहते हैं?", options: ["Microeconomics", "Macroeconomics", "Econometrics", "Statistics"], answer: 0, explain: "Microeconomics vyaktigat units (consumer, firm) ka adhyayan hai." },
      { q: "The study of the economy as a whole is called:", hi: "संपूर्ण अर्थव्यवस्था के अध्ययन को क्या कहते हैं?", options: ["Macroeconomics", "Microeconomics", "Econometrics", "Finance"], answer: 0, explain: "Macroeconomics poori economy (GDP, inflation) ka adhyayan hai." },
      { q: "A continuous rise in the general price level is called:", hi: "सामान्य मूल्य स्तर में निरंतर वृद्धि को क्या कहते हैं?", options: ["Inflation", "Deflation", "Recession", "Depression"], answer: 0, explain: "Inflation (mudra sfeeti) = keematon me nirantar vridhi." },
      { q: "A continuous fall in the general price level is called:", hi: "सामान्य मूल्य स्तर में निरंतर गिरावट को क्या कहते हैं?", options: ["Deflation", "Inflation", "Stagflation", "Recession"], answer: 0, explain: "Deflation = keematon me nirantar giraavat." },
      { q: "High inflation combined with stagnant growth is called:", hi: "उच्च मुद्रास्फीति के साथ ठहरी हुई वृद्धि को क्या कहते हैं?", options: ["Stagflation", "Deflation", "Recession", "Reflation"], answer: 0, explain: "Stagflation = high inflation + stagnant growth + unemployment." },
      { q: "The three sectors of the economy are primary, secondary and:", hi: "अर्थव्यवस्था के तीन क्षेत्र— प्राथमिक, द्वितीयक और?", options: ["Tertiary", "Quaternary", "Industrial", "Financial"], answer: 0, explain: "Teen sector: Primary (agri), Secondary (industry), Tertiary (services)." },
      { q: "Agriculture belongs to which sector?", hi: "कृषि किस क्षेत्र में आती है?", options: ["Primary", "Secondary", "Tertiary", "Quaternary"], answer: 0, explain: "Agriculture Primary sector me aati hai." },
      { q: "Banking and IT services belong to which sector?", hi: "बैंकिंग और IT सेवाएँ किस क्षेत्र में आती हैं?", options: ["Tertiary (Services)", "Primary", "Secondary", "Industrial"], answer: 0, explain: "Banking, IT, services Tertiary sector me aate hain." },
      { q: "The 'law of demand' states that as price rises, demand:", hi: "'मांग का नियम' कहता है कि मूल्य बढ़ने पर मांग?", options: ["Falls", "Rises", "Remains constant", "Doubles"], answer: 0, explain: "Law of Demand: price badhe to demand girti hai (inverse)." },
      { q: "Per capita income is calculated by dividing national income by:", hi: "प्रति व्यक्ति आय राष्ट्रीय आय को किससे भाग देकर निकाली जाती है?", options: ["Total population", "GDP", "Number of workers", "Number of families"], answer: 0, explain: "Per capita income = National income / kul aabadi." },
      { q: "NITI Aayog replaced which body in 2015?", hi: "नीति आयोग ने 2015 में किसका स्थान लिया?", options: ["Planning Commission", "Finance Commission", "Election Commission", "UPSC"], answer: 0, explain: "NITI Aayog (2015) ne Planning Commission ko replace kiya." },
      { q: "The first Five Year Plan in India focused on:", hi: "भारत की पहली पंचवर्षीय योजना का फोकस किस पर था?", options: ["Agriculture", "Industry", "Services", "Defence"], answer: 0, explain: "Pehli Five Year Plan (1951-56) agriculture par focused thi (Harrod-Domar model)." },
      { q: "The Human Development Index (HDI) is published by:", hi: "मानव विकास सूचकांक (HDI) कौन प्रकाशित करता है?", options: ["UNDP", "World Bank", "IMF", "WTO"], answer: 0, explain: "HDI UNDP (United Nations Development Programme) publish karta hai." },
    ],
  },
  {
    id: "money-banking",
    name: "Money, Banking & Finance",
    questions: [
      { q: "The central bank of India is:", hi: "भारत का केंद्रीय बैंक कौन-सा है?", options: ["Reserve Bank of India", "State Bank of India", "NABARD", "SEBI"], answer: 0, explain: "RBI (Reserve Bank of India) desh ka central bank hai." },
      { q: "The RBI was established in:", hi: "RBI की स्थापना कब हुई?", options: ["1935", "1947", "1950", "1949"], answer: 0, explain: "RBI 1935 me sthapit hui; 1949 me nationalized." },
      { q: "Who issues currency notes in India (except ₹1)?", hi: "भारत में करेंसी नोट (₹1 को छोड़कर) कौन जारी करता है?", options: ["RBI", "Ministry of Finance", "SBI", "Mint"], answer: 0, explain: "Currency notes RBI jaari karta hai (₹1 note aur coins Finance Ministry)." },
      { q: "The rate at which RBI lends to commercial banks is:", hi: "जिस दर पर RBI वाणिज्यिक बैंकों को उधार देता है, वह क्या है?", options: ["Repo rate", "Reverse repo rate", "Bank rate", "CRR"], answer: 0, explain: "Repo rate par RBI commercial banks ko short-term loan deta hai." },
      { q: "The rate at which RBI borrows from banks is:", hi: "जिस दर पर RBI बैंकों से उधार लेता है, वह क्या है?", options: ["Reverse repo rate", "Repo rate", "Bank rate", "SLR"], answer: 0, explain: "Reverse repo rate par RBI banks se paisa borrow karta hai." },
      { q: "CRR stands for:", hi: "CRR का पूर्ण रूप क्या है?", options: ["Cash Reserve Ratio", "Credit Reserve Ratio", "Central Reserve Rate", "Cash Repo Rate"], answer: 0, explain: "CRR = Cash Reserve Ratio (banks RBI ke paas rakhte hain)." },
      { q: "SLR stands for:", hi: "SLR का पूर्ण रूप क्या है?", options: ["Statutory Liquidity Ratio", "Standard Liquidity Rate", "Statutory Loan Ratio", "Standard Loan Ratio"], answer: 0, explain: "SLR = Statutory Liquidity Ratio." },
      { q: "SEBI regulates which market in India?", hi: "SEBI भारत में किस बाज़ार का नियमन करता है?", options: ["Stock/Securities market", "Banking", "Insurance", "Currency"], answer: 0, explain: "SEBI (Securities and Exchange Board of India) share market ko regulate karta hai." },
      { q: "IRDAI regulates which sector?", hi: "IRDAI किस क्षेत्र का नियमन करता है?", options: ["Insurance", "Banking", "Stock market", "Pension"], answer: 0, explain: "IRDAI insurance sector ko regulate karta hai." },
      { q: "The first bank established in India was:", hi: "भारत में स्थापित पहला बैंक कौन-सा था?", options: ["Bank of Hindustan", "State Bank of India", "RBI", "Punjab National Bank"], answer: 0, explain: "Bank of Hindustan (1770) pehla bank tha." },
      { q: "The nationalization of 14 major banks happened in:", hi: "14 प्रमुख बैंकों का राष्ट्रीयकरण कब हुआ?", options: ["1969", "1949", "1980", "1991"], answer: 0, explain: "14 banks ka nationalization 1969 me hua (Indira Gandhi)." },
      { q: "NABARD is associated with the development of:", hi: "NABARD किसके विकास से संबंधित है?", options: ["Agriculture & Rural areas", "Industry", "Urban housing", "Exports"], answer: 0, explain: "NABARD (1982) agriculture aur rural development ke liye hai." },
      { q: "A cheque that has crossed the validity period is called:", hi: "जिस चेक की वैधता अवधि समाप्त हो गई हो, उसे क्या कहते हैं?", options: ["Stale cheque", "Bearer cheque", "Crossed cheque", "Open cheque"], answer: 0, explain: "Validity ke baad wala cheque 'stale cheque' hai (3 months)." },
      { q: "'Devaluation' of currency means:", hi: "मुद्रा का 'अवमूल्यन' का अर्थ है?", options: ["Reducing value against foreign currency", "Increasing value", "Printing more money", "Withdrawing money"], answer: 0, explain: "Devaluation = mudra ki value videshi mudra ke saapeksh kam karna." },
      { q: "The full form of NEFT is:", hi: "NEFT का पूर्ण रूप क्या है?", options: ["National Electronic Funds Transfer", "New Electronic Fund Transaction", "National Easy Fund Transfer", "Net Electronic Fund Transfer"], answer: 0, explain: "NEFT = National Electronic Funds Transfer." },
    ],
  },
  {
    id: "budget-tax",
    name: "Budget, Taxation & Fiscal Policy",
    questions: [
      { q: "The Union Budget is presented by the:", hi: "केंद्रीय बजट कौन प्रस्तुत करता है?", options: ["Finance Minister", "Prime Minister", "President", "RBI Governor"], answer: 0, explain: "Union Budget Finance Minister prastut karta hai (Art 112)." },
      { q: "The Union Budget is also called the:", hi: "केंद्रीय बजट को और क्या कहते हैं?", options: ["Annual Financial Statement", "Economic Survey", "Fiscal Report", "Monetary Policy"], answer: 0, explain: "Budget ko 'Annual Financial Statement' (Art 112) kehte hain." },
      { q: "GST is which type of tax?", hi: "GST किस प्रकार का कर है?", options: ["Indirect tax", "Direct tax", "Wealth tax", "Corporate tax"], answer: 0, explain: "GST indirect tax hai (goods aur services par)." },
      { q: "Income tax is a:", hi: "आयकर किस प्रकार का कर है?", options: ["Direct tax", "Indirect tax", "GST", "Excise duty"], answer: 0, explain: "Income tax direct tax hai (aay par seedha)." },
      { q: "GST was implemented in India on:", hi: "भारत में GST कब लागू हुआ?", options: ["1 July 2017", "1 April 2016", "1 January 2018", "15 August 2017"], answer: 0, explain: "GST 1 July 2017 ko laागू hua." },
      { q: "The difference between total expenditure and total revenue is the:", hi: "कुल व्यय और कुल राजस्व के बीच अंतर को क्या कहते हैं?", options: ["Fiscal deficit", "Revenue deficit", "Trade deficit", "Budget surplus"], answer: 0, explain: "Fiscal deficit = total expenditure − total revenue (borrowing chhod kar)." },
      { q: "The GST Council is headed by the:", hi: "GST परिषद का अध्यक्ष कौन होता है?", options: ["Union Finance Minister", "PM", "President", "RBI Governor"], answer: 0, explain: "GST Council ka adhyaksh Union Finance Minister hota hai." },
      { q: "Which policy is controlled by the RBI?", hi: "RBI किस नीति को नियंत्रित करता है?", options: ["Monetary policy", "Fiscal policy", "Trade policy", "Industrial policy"], answer: 0, explain: "Monetary policy RBI control karta hai; Fiscal policy sarkaar." },
      { q: "Fiscal policy is controlled by the:", hi: "राजकोषीय नीति किसके द्वारा नियंत्रित होती है?", options: ["Government", "RBI", "SEBI", "NITI Aayog"], answer: 0, explain: "Fiscal policy (tax aur spending) sarkaar control karti hai." },
      { q: "Corporate tax is levied on the profits of:", hi: "निगम कर किसके लाभ पर लगाया जाता है?", options: ["Companies", "Individuals", "Farmers", "Traders"], answer: 0, explain: "Corporate tax companies ke profit par lagta hai (direct tax)." },
      { q: "The financial year in India runs from:", hi: "भारत में वित्तीय वर्ष कब से कब तक चलता है?", options: ["1 April to 31 March", "1 Jan to 31 Dec", "1 July to 30 June", "1 Oct to 30 Sep"], answer: 0, explain: "Financial year 1 April se 31 March tak." },
      { q: "Which tax was subsumed under GST?", hi: "GST के अंतर्गत कौन-सा कर समाहित हुआ?", options: ["Excise duty, VAT, Service tax", "Income tax", "Corporate tax", "Property tax"], answer: 0, explain: "GST me Excise duty, VAT, Service tax etc. samahit hue." },
      { q: "The Economic Survey is presented:", hi: "आर्थिक सर्वेक्षण कब प्रस्तुत होता है?", options: ["A day before the Union Budget", "After budget", "In December", "In August"], answer: 0, explain: "Economic Survey budget se ek din pehle Finance Ministry pesh karti hai." },
      { q: "Disinvestment means:", hi: "विनिवेश का अर्थ है?", options: ["Selling govt stake in PSUs", "Buying shares", "Nationalization", "Printing money"], answer: 0, explain: "Disinvestment = sarkaar dwara PSU me apni hissedari bechna." },
      { q: "The 'Laffer Curve' shows the relationship between tax rates and:", hi: "'लैफर वक्र' कर दरों और किसके बीच संबंध दर्शाता है?", options: ["Tax revenue", "Inflation", "GDP", "Employment"], answer: 0, explain: "Laffer Curve tax rate aur tax revenue ka sambandh dikhata hai." },
    ],
  },
  {
    id: "econ-terms",
    name: "Economic Terms & Organizations",
    questions: [
      { q: "The headquarters of the IMF is in:", hi: "IMF का मुख्यालय कहाँ है?", options: ["Washington D.C.", "New York", "Geneva", "London"], answer: 0, explain: "IMF (International Monetary Fund) ka HQ Washington D.C. me hai." },
      { q: "The headquarters of the World Bank is in:", hi: "विश्व बैंक का मुख्यालय कहाँ है?", options: ["Washington D.C.", "New York", "Geneva", "Paris"], answer: 0, explain: "World Bank ka HQ Washington D.C. me hai." },
      { q: "The headquarters of the WTO is in:", hi: "WTO का मुख्यालय कहाँ है?", options: ["Geneva", "Washington D.C.", "New York", "Rome"], answer: 0, explain: "WTO (World Trade Organization) ka HQ Geneva me hai." },
      { q: "The 'Green GDP' accounts for:", hi: "'हरित GDP' किसका लेखा-जोखा रखता है?", options: ["Environmental costs", "Only agriculture", "Only industry", "Foreign trade"], answer: 0, explain: "Green GDP me environmental degradation ki cost bhi shaamil hoti hai." },
      { q: "The full form of NPA (in banking) is:", hi: "बैंकिंग में NPA का पूर्ण रूप क्या है?", options: ["Non-Performing Asset", "Net Personal Account", "National Payment Association", "New Payment Asset"], answer: 0, explain: "NPA = Non-Performing Asset (jo loan return nahi ho raha)." },
      { q: "'Repo' in repo rate stands for:", hi: "रेपो रेट में 'रेपो' का अर्थ क्या है?", options: ["Repurchase", "Repayment", "Report", "Reserve"], answer: 0, explain: "Repo = Repurchase agreement." },
      { q: "The 'Blue Economy' is related to:", hi: "'नीली अर्थव्यवस्था' किससे संबंधित है?", options: ["Ocean resources", "Agriculture", "Mining", "IT"], answer: 0, explain: "Blue Economy samudri (ocean) sansadhanon ke sustainable use se juda hai." },
      { q: "The demand curve slopes:", hi: "मांग वक्र किस दिशा में झुकता है?", options: ["Downward (left to right)", "Upward", "Vertical", "Horizontal"], answer: 0, explain: "Demand curve neeche ki or jhukta hai (inverse relation)." },
      { q: "The supply curve slopes:", hi: "आपूर्ति वक्र किस दिशा में झुकता है?", options: ["Upward (left to right)", "Downward", "Vertical", "Horizontal"], answer: 0, explain: "Supply curve upar ki or jhukta hai (direct relation)." },
      { q: "'Repo rate' increase by RBI generally leads to:", hi: "RBI द्वारा रेपो दर बढ़ाने से आमतौर पर क्या होता है?", options: ["Costlier loans, lower inflation", "Cheaper loans", "More money supply", "Higher inflation"], answer: 0, explain: "Repo rate badhne se loans mehnge, money supply kam, inflation control." },
      { q: "The 'trade deficit' occurs when:", hi: "'व्यापार घाटा' कब होता है?", options: ["Imports exceed exports", "Exports exceed imports", "Trade is balanced", "No trade"], answer: 0, explain: "Trade deficit = imports > exports." },
      { q: "'Fiscal deficit' is financed mainly by:", hi: "'राजकोषीय घाटा' मुख्यतः कैसे पूरा होता है?", options: ["Borrowing", "Printing money only", "Taxes", "Foreign aid only"], answer: 0, explain: "Fiscal deficit mainly borrowing (loan) se pura hota hai." },
      { q: "The 'Gini coefficient' measures:", hi: "'गिनी गुणांक' किसे मापता है?", options: ["Income inequality", "Inflation", "GDP growth", "Unemployment"], answer: 0, explain: "Gini coefficient aay asamaanta (income inequality) naapta hai." },
      { q: "A market with a single seller is called:", hi: "एकल विक्रेता वाला बाज़ार क्या कहलाता है?", options: ["Monopoly", "Oligopoly", "Duopoly", "Perfect competition"], answer: 0, explain: "Ek seller wala market = Monopoly (ekadhikaar)." },
      { q: "A market with a few sellers is called:", hi: "कुछ विक्रेताओं वाला बाज़ार क्या कहलाता है?", options: ["Oligopoly", "Monopoly", "Perfect competition", "Monopsony"], answer: 0, explain: "Kuch sellers = Oligopoly." },
    ],
  },
  {
    id: "econ-india",
    name: "Indian Economy — Facts & Schemes",
    questions: [
      { q: "India's economy was liberalized (LPG reforms) in:", hi: "भारत की अर्थव्यवस्था का उदारीकरण (LPG सुधार) कब हुआ?", options: ["1991", "1947", "1980", "2000"], answer: 0, explain: "1991 me LPG (Liberalization, Privatization, Globalization) reforms hue (Manmohan Singh)." },
      { q: "Who is called the architect of India's 1991 economic reforms?", hi: "1991 के आर्थिक सुधारों का शिल्पकार किसे कहा जाता है?", options: ["Dr. Manmohan Singh", "P. V. Narasimha Rao", "Nehru", "Montek Singh"], answer: 0, explain: "Dr. Manmohan Singh (tab FM) 1991 reforms ke architect the." },
      { q: "MGNREGA guarantees how many days of employment?", hi: "MGNREGA कितने दिनों के रोजगार की गारंटी देता है?", options: ["100 days", "150 days", "50 days", "200 days"], answer: 0, explain: "MGNREGA (2005) grameen parivaron ko 100 din rozgar ki guarantee deta hai." },
      { q: "Jan Dhan Yojana is related to:", hi: "जन धन योजना किससे संबंधित है?", options: ["Financial inclusion (bank accounts)", "Housing", "Health", "Education"], answer: 0, explain: "Pradhan Mantri Jan Dhan Yojana (2014) financial inclusion (bank accounts) ke liye hai." },
      { q: "The currency of India is issued as legal tender by:", hi: "भारत की मुद्रा को वैध मुद्रा के रूप में कौन जारी करता है?", options: ["RBI", "SBI", "Finance Ministry", "Mint"], answer: 0, explain: "RBI legal tender currency issue karta hai." },
      { q: "Which state has the highest per capita income in India?", hi: "भारत में सर्वाधिक प्रति व्यक्ति आय किस राज्य की है?", options: ["Goa/small states (varies)", "Bihar", "UP", "Odisha"], answer: 0, explain: "Chhote rajya/UTs (Goa, Sikkim) me per capita income sabse zyada hoti hai." },
      { q: "'Repo rate' is decided by which RBI committee?", hi: "'रेपो दर' किस RBI समिति द्वारा तय होती है?", options: ["Monetary Policy Committee (MPC)", "GST Council", "Finance Commission", "NITI Aayog"], answer: 0, explain: "Repo rate MPC (Monetary Policy Committee) tay karti hai." },
      { q: "The largest source of tax revenue for the Indian government is:", hi: "भारत सरकार के लिए कर राजस्व का सबसे बड़ा स्रोत कौन-सा है?", options: ["GST + Income tax", "Customs", "Wealth tax", "Property tax"], answer: 0, explain: "GST aur Income tax sabse bade tax revenue sources hain." },
      { q: "Which sector contributes the most to India's GDP?", hi: "भारत की GDP में सबसे अधिक योगदान किस क्षेत्र का है?", options: ["Services (Tertiary)", "Agriculture", "Industry", "Mining"], answer: 0, explain: "Services (tertiary) sector GDP me sabse zyada (~50%+) yogdan deta hai." },
      { q: "The 'Poverty Line' in India is estimated by (earlier):", hi: "भारत में 'गरीबी रेखा' का आकलन (पहले) कौन करता था?", options: ["Planning Commission / NITI Aayog", "RBI", "SEBI", "Finance Commission"], answer: 0, explain: "Poverty line Planning Commission (ab NITI Aayog related) estimate karta tha." },
      { q: "PMAY (Pradhan Mantri Awas Yojana) is related to:", hi: "प्रधानमंत्री आवास योजना किससे संबंधित है?", options: ["Housing for all", "Employment", "Health", "Education"], answer: 0, explain: "PMAY 'Housing for All' ke liye hai." },
      { q: "Ayushman Bharat is a scheme related to:", hi: "आयुष्मान भारत किससे संबंधित योजना है?", options: ["Health insurance", "Housing", "Employment", "Education"], answer: 0, explain: "Ayushman Bharat (PM-JAY) health insurance yojana hai." },
      { q: "The India rupee symbol ₹ was adopted in:", hi: "भारतीय रुपये का प्रतीक ₹ कब अपनाया गया?", options: ["2010", "2000", "2015", "1991"], answer: 0, explain: "Rupee symbol ₹ 2010 me adopt hua (D. Udaya Kumar ne design kiya)." },
      { q: "'Repo rate' and 'CRR' are tools of:", hi: "'रेपो दर' और 'CRR' किसके उपकरण हैं?", options: ["Monetary policy", "Fiscal policy", "Trade policy", "Industrial policy"], answer: 0, explain: "Repo rate, CRR, SLR monetary policy ke tools hain (RBI)." },
      { q: "The 'demonetization' in India took place in:", hi: "भारत में 'विमुद्रीकरण' कब हुआ?", options: ["November 2016", "July 2017", "March 2015", "August 2019"], answer: 0, explain: "Demonetization (₹500, ₹1000 notes) November 2016 me hua." },
      { q: "Which organization releases the 'World Economic Outlook' report?", hi: "'वर्ल्ड इकोनॉमिक आउटलुक' रिपोर्ट कौन जारी करता है?", options: ["IMF", "World Bank", "WTO", "UN"], answer: 0, explain: "World Economic Outlook IMF jaari karta hai." },
    ],
  },
  {
    id: "econ-extra",
    name: "Economics — More Concepts & Facts",
    questions: [
      { q: "The 'primary deficit' is the fiscal deficit minus:", hi: "'प्राथमिक घाटा' राजकोषीय घाटा घटाकर क्या होता है?", options: ["Interest payments", "Tax revenue", "Subsidies", "Grants"], answer: 0, explain: "Primary deficit = fiscal deficit − interest payments." },
      { q: "'Repo rate' cut generally makes loans:", hi: "'रेपो दर' में कटौती से आमतौर पर ऋण कैसे होते हैं?", options: ["Cheaper", "Costlier", "Unchanged", "Unavailable"], answer: 0, explain: "Repo rate kam hone se loans saste hote hain." },
      { q: "The 'balance of payments' records:", hi: "'भुगतान संतुलन' किसका लेखा रखता है?", options: ["All economic transactions with other countries", "Only exports", "Only imports", "Domestic trade"], answer: 0, explain: "Balance of payments desh ke saare videshi len-den ka record hai." },
      { q: "'FDI' stands for:", hi: "'FDI' का पूर्ण रूप क्या है?", options: ["Foreign Direct Investment", "Foreign Domestic Income", "Full Direct Investment", "Fixed Deposit Investment"], answer: 0, explain: "FDI = Foreign Direct Investment." },
      { q: "'FII' stands for:", hi: "'FII' का पूर्ण रूप क्या है?", options: ["Foreign Institutional Investor", "Foreign Individual Income", "Full Investment Index", "Fixed Income Investment"], answer: 0, explain: "FII = Foreign Institutional Investor." },
      { q: "The 'CPI' measures inflation based on:", hi: "'CPI' किस आधार पर मुद्रास्फीति मापता है?", options: ["Consumer prices", "Wholesale prices", "Export prices", "Producer costs"], answer: 0, explain: "CPI (Consumer Price Index) upभोक्ta keematon par inflation naapta hai." },
      { q: "The 'WPI' measures inflation based on:", hi: "'WPI' किस आधार पर मुद्रास्फीति मापता है?", options: ["Wholesale prices", "Consumer prices", "Retail prices", "Import prices"], answer: 0, explain: "WPI (Wholesale Price Index) thok keematon par based hai." },
      { q: "Which is a 'direct tax'?", hi: "कौन-सा 'प्रत्यक्ष कर' है?", options: ["Income tax", "GST", "Excise duty", "Customs duty"], answer: 0, explain: "Income tax direct tax hai; GST/excise/customs indirect." },
      { q: "'Subsidy' is a form of:", hi: "'सब्सिडी' किसका रूप है?", options: ["Government financial support", "Tax", "Loan", "Investment"], answer: 0, explain: "Subsidy sarkaar dwara di gayi vittiya sahayta hai." },
      { q: "The 'Sensex' is the index of which stock exchange?", hi: "'सेंसेक्स' किस स्टॉक एक्सचेंज का सूचकांक है?", options: ["BSE (Bombay Stock Exchange)", "NSE", "NYSE", "NASDAQ"], answer: 0, explain: "Sensex BSE (Bombay Stock Exchange) ka index hai (30 companies)." },
      { q: "The 'Nifty' is the index of which stock exchange?", hi: "'निफ्टी' किस स्टॉक एक्सचेंज का सूचकांक है?", options: ["NSE (National Stock Exchange)", "BSE", "NYSE", "LSE"], answer: 0, explain: "Nifty NSE (National Stock Exchange) ka index hai (50 companies)." },
      { q: "The 'GST' has how many main slabs (rates) commonly?", hi: "'GST' के आमतौर पर कितने मुख्य स्लैब हैं?", options: ["Four (5,12,18,28%)", "Two", "Six", "Three"], answer: 0, explain: "GST me 4 mukhya slabs: 5%, 12%, 18%, 28%." },
      { q: "'Microfinance' primarily serves:", hi: "'माइक्रोफाइनेंस' मुख्यतः किसकी सेवा करता है?", options: ["Small/poor borrowers", "Big corporations", "Government", "Foreign investors"], answer: 0, explain: "Microfinance chhote/gareeb borrowers ko chhote loan deta hai." },
      { q: "The 'MSP' (Minimum Support Price) is announced for:", hi: "'MSP' (न्यूनतम समर्थन मूल्य) किसके लिए घोषित होता है?", options: ["Agricultural crops", "Industrial goods", "Services", "Imports"], answer: 0, explain: "MSP krishi faslon ke liye ghoshit hoti hai (farmers ki suraksha)." },
      { q: "The 'CRR' is maintained by banks with the:", hi: "'CRR' बैंक किसके पास रखते हैं?", options: ["RBI", "SEBI", "Finance Ministry", "SBI"], answer: 0, explain: "CRR banks RBI ke paas cash reserve ke roop me rakhte hain." },
      { q: "'Hot money' refers to:", hi: "'हॉट मनी' किसे कहते हैं?", options: ["Short-term speculative capital", "Black money", "Counterfeit currency", "Gold reserves"], answer: 0, explain: "Hot money short-term speculative funds hain jo tezi se aate-jaate hain." },
      { q: "'Deficit financing' means the government:", hi: "'घाटे की वित्त व्यवस्था' का अर्थ है सरकार?", options: ["Spends more than it earns (borrows/prints)", "Saves money", "Reduces taxes", "Stops spending"], answer: 0, explain: "Deficit financing = kamai se zyada kharch (borrowing/printing se)." },
      { q: "The 'Human Development Index' includes life expectancy, education and:", hi: "'मानव विकास सूचकांक' में जीवन प्रत्याशा, शिक्षा और क्या शामिल है?", options: ["Per capita income", "Population", "GDP growth", "Inflation"], answer: 0, explain: "HDI = life expectancy + education + per capita income." },
      { q: "'GST' is levied at the point of:", hi: "'GST' किस बिंदु पर लगाया जाता है?", options: ["Consumption (destination-based)", "Production", "Import only", "Export only"], answer: 0, explain: "GST destination-based (consumption) tax hai." },
      { q: "The 'repo' transaction involves government:", hi: "'रेपो' लेन-देन में क्या शामिल होता है?", options: ["Securities as collateral", "Gold", "Foreign currency", "Land"], answer: 0, explain: "Repo me banks government securities collateral rakhkar RBI se loan lete hain." },
      { q: "A 'recession' is defined as negative GDP growth for at least:", hi: "'मंदी' कम से कम कितनी अवधि की नकारात्मक GDP वृद्धि है?", options: ["Two consecutive quarters", "One month", "One year", "Five years"], answer: 0, explain: "Recession = do lagataar quarters me negative GDP growth." },
      { q: "'Per capita income' indicates the:", hi: "'प्रति व्यक्ति आय' किसका सूचक है?", options: ["Average income per person", "Total national income", "Government revenue", "Export earnings"], answer: 0, explain: "Per capita income = pratipratividha vyakti ki ausat aay." },
      { q: "The apex body for cooperative credit in rural India is:", hi: "ग्रामीण भारत में सहकारी ऋण का शीर्ष निकाय कौन-सा है?", options: ["NABARD", "SEBI", "IRDAI", "SIDBI"], answer: 0, explain: "NABARD rural cooperative credit ka apex body hai." },
      { q: "SIDBI is meant for the development of:", hi: "SIDBI किसके विकास के लिए है?", options: ["Small industries", "Agriculture", "Housing", "Exports"], answer: 0, explain: "SIDBI (Small Industries Development Bank) small-scale industries ke liye hai." },
    ],
  },
];
