// SSC CGL — English Comprehension (200 questions)
// High-level, matching SSC CGL 2025 real-paper standard.
// { q, options[4], answer index 0-3, explain }
// (English section — Hindi explanation added where helpful.)

export const englishMeta = {
  title: "English Comprehension — 200 Practice Questions",
  exam: "SSC CGL Tier 1 Level",
  total: 200,
  note: "SSC CGL Tier-1 level English questions — 2025 exam standard (high difficulty). Detailed solutions 'Show Answer Key' me. Answer list sabse neeche.",
};

export const englishSections = [
  {
    id: "error",
    name: "Spot the Error",
    questions: [
      { q: "Select the part with an error: Neither the students nor the teacher (a) / were ready for the drill (b) / leading to confusion (c) / before everyone evacuated. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 1, explain: "'Neither...nor' me verb nearest subject (teacher, singular) se agree kare → 'was ready', not 'were'." },
      { q: "Spot the error: The manager, along with her team, (a) / expect that the project (b) / will be completed (c) / before the deadline. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 1, explain: "'along with her team' subject nahi badalta; subject 'manager' singular → 'expects'." },
      { q: "Spot the error: One of the boys (a) / who were present (b) / have broken (c) / the window. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 2, explain: "'One of the boys' singular → 'has broken', not 'have'." },
      { q: "Spot the error: The committee's objectives included (a) / increasing membership, improving channels (b) / and to foster community (c) / among members. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 2, explain: "Parallelism: increasing, improving, and 'fostering' — 'to foster' breaks parallel structure." },
      { q: "Spot the error: Each of the participants (a) / were given (b) / a certificate (c) / after the event. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 1, explain: "'Each' singular → 'was given'." },
      { q: "Spot the error: He is one of those (a) / who always tries (b) / to help others (c) / in need. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 1, explain: "'one of those who' → plural verb 'try', not 'tries'." },
      { q: "Spot the error: The scenery of the hills (a) / were so beautiful (b) / that we decided (c) / to stay longer. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 1, explain: "'scenery' uncountable/singular → 'was so beautiful'." },
      { q: "Spot the error: Hardly had he entered (a) / the room than (b) / the lights went off (c) / suddenly. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 1, explain: "'Hardly...when' correct correlative, not 'than' → 'the room when'." },
      { q: "Spot the error: The number of students (a) / in the class (b) / are increasing (c) / every year. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 2, explain: "'The number of' takes singular verb → 'is increasing'." },
      { q: "Spot the error: She said that (a) / she will come (b) / to the party (c) / the next day. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 1, explain: "Reported speech in past → 'she would come', not 'will'." },
      { q: "Spot the error: Neither of the two answers (a) / are correct (b) / according to (c) / the answer key. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 1, explain: "'Neither of' singular → 'is correct'." },
      { q: "Spot the error: If I was you (a) / I would not (b) / accept such (c) / a poor offer. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 0, explain: "Subjunctive (hypothetical) → 'If I were you'." },
      { q: "Spot the error: The jury was divided (a) / in their opinion (b) / and could not (c) / reach a verdict. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 0, explain: "When jury acts as divided individuals → 'The jury were divided'." },
      { q: "Spot the error: He has been working (a) / in this office (b) / since five years (c) / without a break. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 2, explain: "Duration → 'for five years'; 'since' needs point of time." },
      { q: "Spot the error: The teacher told the students (a) / that the earth (b) / moved around (c) / the sun. (d)", options: ["(a)", "(b)", "(c)", "(d)"], answer: 2, explain: "Universal truth stays present tense → 'moves around'." },
    ],
  },
  {
    id: "improvement",
    name: "Sentence Improvement",
    questions: [
      { q: "Improve the underlined: He is superior 'than' me in every respect.", options: ["superior to", "superior from", "superior than", "no improvement"], answer: 0, explain: "'Superior' takes 'to', not 'than'." },
      { q: "Improve: The teacher asked the boy that why he was late.", options: ["why he was late", "that why was he late", "why was he late", "no improvement"], answer: 0, explain: "Indirect question: no 'that', normal word order → 'why he was late'." },
      { q: "Improve: I have been knowing him for ten years.", options: ["have known him", "am knowing him", "had been knowing him", "no improvement"], answer: 0, explain: "'Know' is a stative verb; not used in continuous → 'have known'." },
      { q: "Improve: Each of the students have submitted their assignment.", options: ["has submitted his assignment", "have submitted his assignment", "has submitted their assignment", "no improvement"], answer: 0, explain: "'Each' singular → 'has submitted his'." },
      { q: "Improve: No sooner did he arrive than the meeting started.", options: ["no improvement", "No sooner he arrived", "No sooner had he arrive", "No sooner he did arrive"], answer: 0, explain: "'No sooner...than' with inversion is correct as given." },
      { q: "Improve: The reason for his failure is because he did not study.", options: ["is that he did not study", "is because of not studying", "was because he did not study", "no improvement"], answer: 0, explain: "'The reason is because' is redundant → 'the reason is that'." },
      { q: "Improve: She is one of the most brilliant student in the class.", options: ["students", "student", "most brilliant of student", "no improvement"], answer: 0, explain: "'One of the most brilliant' → plural noun 'students'." },
      { q: "Improve: He did not knew the answer to the question.", options: ["did not know", "did not known", "not knew", "no improvement"], answer: 0, explain: "After 'did', base form → 'did not know'." },
      { q: "Improve: Hardly I had reached the station when the train left.", options: ["Hardly had I reached", "Hardly I reached", "Hardly did I reach", "no improvement"], answer: 0, explain: "'Hardly' at start needs inversion → 'Hardly had I reached'." },
      { q: "Improve: The rich should help the poors.", options: ["the poor", "poor people's", "the poors", "no improvement"], answer: 0, explain: "'The poor' (adjective as noun) is already plural; no 's'." },
      { q: "Improve: If he would have studied, he would have passed.", options: ["If he had studied", "If he studied", "If he has studied", "no improvement"], answer: 0, explain: "Third conditional: 'If + had + past participle' → 'If he had studied'." },
      { q: "Improve: Let you and I resolve this matter amicably.", options: ["Let you and me", "Let I and you", "Let you and myself", "no improvement"], answer: 0, explain: "After 'let', object pronoun → 'you and me'." },
      { q: "Improve: The furnitures in the office are new.", options: ["furniture in the office is", "furnitures in the office is", "furniture in the office are", "no improvement"], answer: 0, explain: "'Furniture' uncountable → no plural, singular verb 'is'." },
      { q: "Improve: He prefers coffee than tea.", options: ["coffee to tea", "coffee than to tea", "coffee over than tea", "no improvement"], answer: 0, explain: "'Prefer' takes 'to' → 'coffee to tea'." },
      { q: "Improve: Being a hot day, we stayed indoors.", options: ["It being a hot day", "Been a hot day", "Being hot day", "no improvement"], answer: 0, explain: "Dangling modifier; needs subject → 'It being a hot day'." },
    ],
  },
  {
    id: "fill",
    name: "Fill in the Blanks",
    questions: [
      { q: "The scientist's theory was so ______ that only a few experts could understand it.", options: ["abstruse", "lucid", "trivial", "mundane"], answer: 0, explain: "'Abstruse' = difficult to understand; fits 'only few experts could understand'." },
      { q: "Despite the ______ evidence, the jury acquitted the accused.", options: ["damning", "flimsy", "scanty", "meagre"], answer: 0, explain: "'Damning' = strongly indicating guilt; contrast with acquittal." },
      { q: "His ______ remarks during the meeting offended several colleagues.", options: ["caustic", "amiable", "genial", "cordial"], answer: 0, explain: "'Caustic' = sarcastic/bitter; fits 'offended'." },
      { q: "The politician gave an ______ speech that inspired the entire nation.", options: ["eloquent", "insipid", "tedious", "vapid"], answer: 0, explain: "'Eloquent' = fluent, persuasive; fits 'inspired'." },
      { q: "The old manuscript was so ______ that it crumbled at the slightest touch.", options: ["fragile", "robust", "sturdy", "resilient"], answer: 0, explain: "'Fragile' = easily broken; fits 'crumbled'." },
      { q: "She remained ______ despite the chaos around her.", options: ["composed", "agitated", "frantic", "flustered"], answer: 0, explain: "'Composed' = calm; contrast with 'chaos'." },
      { q: "The detective found a ______ in the suspect's alibi.", options: ["discrepancy", "consistency", "harmony", "coherence"], answer: 0, explain: "'Discrepancy' = inconsistency; a flaw in the alibi." },
      { q: "The company's profits ______ after the new policy was implemented.", options: ["soared", "plummeted", "stagnated", "dwindled"], answer: 0, explain: "Context of success/new policy → 'soared' (rose sharply). (Choose per positive framing.)" },
      { q: "His argument was ______; nobody could find a flaw in it.", options: ["irrefutable", "tenuous", "specious", "dubious"], answer: 0, explain: "'Irrefutable' = cannot be disproved; fits 'no flaw'." },
      { q: "The child's ______ curiosity led him to ask endless questions.", options: ["insatiable", "limited", "waning", "feeble"], answer: 0, explain: "'Insatiable' = impossible to satisfy; fits 'endless questions'." },
      { q: "The two nations signed a treaty to ______ the long-standing dispute.", options: ["resolve", "aggravate", "provoke", "inflame"], answer: 0, explain: "Treaty aims to 'resolve' (settle) a dispute." },
      { q: "The professor's lecture was so ______ that students struggled to stay awake.", options: ["soporific", "stimulating", "riveting", "engaging"], answer: 0, explain: "'Soporific' = sleep-inducing; fits 'struggled to stay awake'." },
      { q: "The rumours turned out to be ______ and caused unnecessary panic.", options: ["baseless", "credible", "authentic", "valid"], answer: 0, explain: "'Baseless' = without foundation; fits 'unnecessary panic'." },
      { q: "The manager's ______ approach ensured no detail was overlooked.", options: ["meticulous", "careless", "slapdash", "cursory"], answer: 0, explain: "'Meticulous' = very careful; fits 'no detail overlooked'." },
      { q: "After the scandal, the minister's reputation was ______.", options: ["tarnished", "enhanced", "bolstered", "elevated"], answer: 0, explain: "'Tarnished' = damaged; fits 'after scandal'." },
    ],
  },
  {
    id: "voice",
    name: "Active & Passive Voice",
    questions: [
      { q: "Change to passive: 'Has the technician repaired the faulty circuit?'", options: ["Has the faulty circuit been repaired by the technician?", "Is the faulty circuit repaired by the technician?", "Was the faulty circuit being repaired?", "Had the faulty circuit repaired?"], answer: 0, explain: "Present perfect passive question: 'Has + object + been + V3'." },
      { q: "Passive of: 'They are repairing the old bridge.'", options: ["The old bridge is being repaired.", "The old bridge is repaired.", "The old bridge has been repaired.", "The old bridge will be repaired."], answer: 0, explain: "Present continuous passive: 'is being + V3'." },
      { q: "Active of: 'The final report had been completed by the researchers.'", options: ["The researchers had completed the final report.", "The researchers have completed the report.", "The researchers completed the report.", "The researchers were completing the report."], answer: 0, explain: "Past perfect passive → active 'had completed'." },
      { q: "Passive of: 'The technicians will be installing the cables.'", options: ["The cables will be being installed by the technicians.", "The cables will be installed by the technicians.", "The cables are installed.", "The cables have been installed."], answer: 0, explain: "Future continuous passive: 'will be being installed'." },
      { q: "Passive of: 'Someone has stolen my wallet.'", options: ["My wallet has been stolen.", "My wallet was stolen.", "My wallet is stolen.", "My wallet had been stolen."], answer: 0, explain: "Present perfect passive → 'has been stolen'." },
      { q: "Passive of: 'The teacher is explaining the lesson.'", options: ["The lesson is being explained by the teacher.", "The lesson is explained.", "The lesson was being explained.", "The lesson has been explained."], answer: 0, explain: "Present continuous passive." },
      { q: "Active of: 'Let the door be closed.'", options: ["Close the door.", "You closed the door.", "The door closes.", "Closing the door."], answer: 0, explain: "Imperative passive → active imperative 'Close the door'." },
      { q: "Passive of: 'People speak English all over the world.'", options: ["English is spoken all over the world.", "English was spoken.", "English has been spoken.", "English is being spoken."], answer: 0, explain: "Simple present passive → 'is spoken'." },
      { q: "Passive of: 'Who wrote this letter?'", options: ["By whom was this letter written?", "Who was this letter written?", "By whom this letter was written?", "Whom wrote this letter?"], answer: 0, explain: "Interrogative (who) passive → 'By whom was...written?'" },
      { q: "Passive of: 'They will complete the project by Monday.'", options: ["The project will be completed by Monday.", "The project is completed.", "The project has been completed.", "The project was completed."], answer: 0, explain: "Simple future passive → 'will be completed'." },
    ],
  },
  {
    id: "narration",
    name: "Direct & Indirect Speech",
    questions: [
      { q: "Indirect: She remarked, 'I visited that museum last week.'", options: ["She remarked that she had visited that museum the previous week.", "She remarked that she visited that museum last week.", "She remarked that I had visited the museum.", "She remarked that she has visited the museum."], answer: 0, explain: "Past simple → past perfect; 'last week' → 'the previous week'." },
      { q: "Indirect: She said to them, 'Will you be attending the conference?'", options: ["She asked them if they would be attending the conference.", "She asked them will they be attending.", "She asked whether they will be attending.", "She asked would they be attending."], answer: 0, explain: "Yes/no question → 'if/whether'; 'will' → 'would'." },
      { q: "Indirect: The teacher asked, 'Why are you late today?'", options: ["The teacher asked why I was late that day.", "The teacher asked why are you late today.", "The teacher asked why I am late.", "The teacher asked why was I late."], answer: 0, explain: "Wh-question → statement order; present → past; 'today' → 'that day'." },
      { q: "Direct: He urged us to complete the assignment before the deadline.", options: ["'Complete the assignment before the deadline,' he urged.", "'You should complete it,' he urged.", "'Will you complete it?' he asked.", "'We must complete it,' he said."], answer: 0, explain: "Urged + to-infinitive → imperative in direct speech." },
      { q: "Indirect: The teacher said, 'The Earth revolves around the Sun.'", options: ["The teacher said that the Earth revolves around the Sun.", "The teacher said that the Earth revolved.", "The teacher said the Earth had revolved.", "The teacher said the Earth is revolving."], answer: 0, explain: "Universal truth stays in present tense." },
      { q: "Indirect: He said, 'Alas! I have failed.'", options: ["He exclaimed with sorrow that he had failed.", "He said that he failed.", "He exclaimed that he has failed.", "He said alas he had failed."], answer: 0, explain: "Exclamation of sorrow → 'exclaimed with sorrow that'." },
      { q: "Indirect: She said, 'Let us go for a walk.'", options: ["She suggested that they should go for a walk.", "She said let us go for a walk.", "She asked to go for a walk.", "She told to go for a walk."], answer: 0, explain: "'Let us' (suggestion) → 'suggested that... should'." },
      { q: "Indirect: Mother said to me, 'May you succeed!'", options: ["Mother wished that I might succeed.", "Mother said that I may succeed.", "Mother told me to succeed.", "Mother prayed I will succeed."], answer: 0, explain: "Optative (wish) → 'wished that... might'." },
      { q: "Indirect: He said, 'What a beautiful painting!'", options: ["He exclaimed that it was a very beautiful painting.", "He said what a beautiful painting.", "He exclaimed it is beautiful.", "He asked about the painting."], answer: 0, explain: "Exclamation → 'exclaimed that... very'." },
      { q: "Direct: She asked me whether I had finished my work.", options: ["She said to me, 'Have you finished your work?'", "She said, 'Did you finish?'", "She asked, 'Will you finish?'", "She said, 'You finished the work.'"], answer: 0, explain: "Indirect 'whether...had finished' → direct present perfect question." },
    ],
  },
  {
    id: "synonym",
    name: "Synonyms",
    questions: [
      { q: "Synonym of ESOTERIC:", options: ["Abstruse", "Common", "Popular", "Simple"], answer: 0, explain: "Esoteric = understood by few; synonym 'Abstruse' (obscure)." },
      { q: "Synonym of FRUGAL:", options: ["Thrifty", "Extravagant", "Lavish", "Wasteful"], answer: 0, explain: "Frugal = economical; synonym 'Thrifty'." },
      { q: "Synonym of PERNICIOUS:", options: ["Harmful", "Beneficial", "Helpful", "Wholesome"], answer: 0, explain: "Pernicious = harmful/destructive." },
      { q: "Synonym of EPHEMERAL:", options: ["Transient", "Permanent", "Eternal", "Lasting"], answer: 0, explain: "Ephemeral = short-lived; synonym 'Transient'." },
      { q: "Synonym of GARRULOUS:", options: ["Talkative", "Silent", "Reserved", "Taciturn"], answer: 0, explain: "Garrulous = excessively talkative." },
      { q: "Synonym of CANDID:", options: ["Frank", "Deceitful", "Evasive", "Secretive"], answer: 0, explain: "Candid = truthful and straightforward; synonym 'Frank'." },
      { q: "Synonym of MITIGATE:", options: ["Alleviate", "Aggravate", "Intensify", "Worsen"], answer: 0, explain: "Mitigate = make less severe; synonym 'Alleviate'." },
      { q: "Synonym of OSTENTATIOUS:", options: ["Showy", "Modest", "Humble", "Plain"], answer: 0, explain: "Ostentatious = showy; designed to impress." },
      { q: "Synonym of PRAGMATIC:", options: ["Practical", "Idealistic", "Theoretical", "Impractical"], answer: 0, explain: "Pragmatic = dealing practically; synonym 'Practical'." },
      { q: "Synonym of BENEVOLENT:", options: ["Kind", "Cruel", "Malicious", "Hostile"], answer: 0, explain: "Benevolent = well-meaning and kind." },
      { q: "Synonym of TENACIOUS:", options: ["Persistent", "Weak", "Yielding", "Fickle"], answer: 0, explain: "Tenacious = holding firmly; synonym 'Persistent'." },
      { q: "Synonym of LUCID:", options: ["Clear", "Vague", "Obscure", "Confusing"], answer: 0, explain: "Lucid = clearly expressed; synonym 'Clear'." },
      { q: "Synonym of ZEALOUS:", options: ["Enthusiastic", "Apathetic", "Indifferent", "Lazy"], answer: 0, explain: "Zealous = full of zeal; synonym 'Enthusiastic'." },
      { q: "Synonym of PROLIFIC:", options: ["Productive", "Barren", "Sterile", "Unproductive"], answer: 0, explain: "Prolific = producing much; synonym 'Productive'." },
      { q: "Synonym of AMELIORATE:", options: ["Improve", "Deteriorate", "Damage", "Spoil"], answer: 0, explain: "Ameliorate = make better; synonym 'Improve'." },
    ],
  },
  {
    id: "antonym",
    name: "Antonyms",
    questions: [
      { q: "Antonym of PRODIGAL:", options: ["Frugal", "Wasteful", "Lavish", "Extravagant"], answer: 0, explain: "Prodigal = wasteful; antonym 'Frugal' (economical)." },
      { q: "Antonym of EXONERATE:", options: ["Convict", "Absolve", "Acquit", "Clear"], answer: 0, explain: "Exonerate = free from blame; antonym 'Convict'." },
      { q: "Antonym of BENEVOLENT:", options: ["Malevolent", "Kind", "Generous", "Gracious"], answer: 0, explain: "Benevolent (kind) ↔ Malevolent (wishing harm)." },
      { q: "Antonym of TRANSPARENT:", options: ["Opaque", "Clear", "Lucid", "Obvious"], answer: 0, explain: "Transparent ↔ Opaque (not see-through)." },
      { q: "Antonym of AUGMENT:", options: ["Diminish", "Increase", "Expand", "Enlarge"], answer: 0, explain: "Augment = increase; antonym 'Diminish'." },
      { q: "Antonym of CONDEMN:", options: ["Praise", "Blame", "Criticise", "Censure"], answer: 0, explain: "Condemn = express disapproval; antonym 'Praise'." },
      { q: "Antonym of FEEBLE:", options: ["Robust", "Weak", "Frail", "Fragile"], answer: 0, explain: "Feeble = weak; antonym 'Robust' (strong)." },
      { q: "Antonym of ABUNDANT:", options: ["Scarce", "Plentiful", "Ample", "Copious"], answer: 0, explain: "Abundant = plentiful; antonym 'Scarce'." },
      { q: "Antonym of HUMBLE:", options: ["Arrogant", "Modest", "Meek", "Docile"], answer: 0, explain: "Humble ↔ Arrogant (proud)." },
      { q: "Antonym of TRANSIENT:", options: ["Permanent", "Fleeting", "Momentary", "Brief"], answer: 0, explain: "Transient = temporary; antonym 'Permanent'." },
      { q: "Antonym of COMMEND:", options: ["Reproach", "Applaud", "Laud", "Extol"], answer: 0, explain: "Commend = praise; antonym 'Reproach'." },
      { q: "Antonym of OBSCURE:", options: ["Clear", "Vague", "Hidden", "Dim"], answer: 0, explain: "Obscure = unclear; antonym 'Clear'." },
      { q: "Antonym of CONCEAL:", options: ["Reveal", "Hide", "Cover", "Mask"], answer: 0, explain: "Conceal = hide; antonym 'Reveal'." },
      { q: "Antonym of RIGID:", options: ["Flexible", "Stiff", "Firm", "Inflexible"], answer: 0, explain: "Rigid = stiff; antonym 'Flexible'." },
      { q: "Antonym of GENEROUS:", options: ["Miserly", "Liberal", "Bountiful", "Charitable"], answer: 0, explain: "Generous = giving; antonym 'Miserly' (stingy)." },
    ],
  },
  {
    id: "idioms",
    name: "Idioms & Phrases",
    questions: [
      { q: "Meaning of 'Bite the bullet':", options: ["To face a difficult situation with courage", "To give up easily", "To avoid a problem", "To decide hastily"], answer: 0, explain: "'Bite the bullet' = endure a painful situation bravely." },
      { q: "Meaning of 'To carry coals to Newcastle':", options: ["To do something pointless/superfluous", "To perform a necessary task", "To transport goods", "To take a risk"], answer: 0, explain: "Newcastle already had coal → doing something needless." },
      { q: "Meaning of 'To have an ace up one's sleeve':", options: ["To possess a hidden advantage", "To cheat in a game", "To be overconfident", "To wear a charm"], answer: 0, explain: "A secret resource kept in reserve." },
      { q: "Meaning of 'To throw in the towel':", options: ["To admit defeat", "To clean up", "To start a fight", "To give a gift"], answer: 0, explain: "Boxing idiom = surrender/give up." },
      { q: "Meaning of 'Beat around the bush':", options: ["To avoid the main point", "To speak directly", "To damage carelessly", "To take risks"], answer: 0, explain: "To talk indirectly, avoiding the issue." },
      { q: "Meaning of 'To pay through the nose':", options: ["To pay an excessively high price", "To pay very little", "To pay in installments", "To negotiate"], answer: 0, explain: "To pay far too much for something." },
      { q: "Meaning of 'To carry the can':", options: ["To take the blame", "To fetch water", "To help someone", "To succeed"], answer: 0, explain: "To take responsibility/blame for a mistake." },
      { q: "Meaning of 'A blessing in disguise':", options: ["A good thing that seemed bad at first", "A hidden curse", "An open secret", "A sudden loss"], answer: 0, explain: "Something initially bad that turns out good." },
      { q: "Meaning of 'To let the cat out of the bag':", options: ["To reveal a secret", "To create chaos", "To release an animal", "To make a mistake"], answer: 0, explain: "To disclose a secret carelessly." },
      { q: "Meaning of 'To burn the midnight oil':", options: ["To work late into the night", "To waste resources", "To cause a fire", "To relax"], answer: 0, explain: "To study/work until late at night." },
      { q: "Meaning of 'A storm in a teacup':", options: ["A big fuss over a trivial matter", "A serious crisis", "A sudden weather change", "A rare event"], answer: 0, explain: "Great excitement about an unimportant matter." },
      { q: "Meaning of 'To bury the hatchet':", options: ["To make peace", "To hide a weapon", "To dig a grave", "To end a career"], answer: 0, explain: "To end a quarrel and become friendly." },
      { q: "Meaning of 'To cut corners':", options: ["To do something cheaply/carelessly", "To take a shortcut route", "To trim edges", "To save time properly"], answer: 0, explain: "To do a task poorly to save money/effort." },
      { q: "Meaning of 'Once in a blue moon':", options: ["Very rarely", "Very often", "At night", "Monthly"], answer: 0, explain: "Something that happens very rarely." },
      { q: "Meaning of 'To spill the beans':", options: ["To reveal secret information", "To waste food", "To make an error", "To cook badly"], answer: 0, explain: "To disclose secret information." },
    ],
  },
  {
    id: "oneword",
    name: "One Word Substitution",
    questions: [
      { q: "One word for 'a person who knows many languages':", options: ["Polyglot", "Linguist", "Bilingual", "Orator"], answer: 0, explain: "Polyglot = one who knows/uses several languages." },
      { q: "One word for 'a government by the wealthy':", options: ["Plutocracy", "Aristocracy", "Autocracy", "Democracy"], answer: 0, explain: "Plutocracy = rule by the rich." },
      { q: "One word for 'that which cannot be corrected':", options: ["Incorrigible", "Incurable", "Illegible", "Invincible"], answer: 0, explain: "Incorrigible = not able to be corrected/reformed." },
      { q: "One word for 'one who eats everything':", options: ["Omnivorous", "Carnivorous", "Herbivorous", "Voracious"], answer: 0, explain: "Omnivorous = eating both plants and animals / everything." },
      { q: "One word for 'a speech made without preparation':", options: ["Extempore", "Eloquent", "Verbose", "Rhetoric"], answer: 0, explain: "Extempore = spoken/done without preparation." },
      { q: "One word for 'a place where birds are kept':", options: ["Aviary", "Apiary", "Aquarium", "Sanctuary"], answer: 0, explain: "Aviary = large enclosure for birds (Apiary = bees)." },
      { q: "One word for 'incapable of being satisfied':", options: ["Insatiable", "Insensible", "Insatiate", "Invincible"], answer: 0, explain: "Insatiable = impossible to satisfy." },
      { q: "One word for 'one who studies the origin of words':", options: ["Etymologist", "Entomologist", "Ecologist", "Ethnologist"], answer: 0, explain: "Etymologist = studies word origins (Entomologist = insects)." },
      { q: "One word for 'a cure for all diseases':", options: ["Panacea", "Antidote", "Remedy", "Vaccine"], answer: 0, explain: "Panacea = a solution/remedy for all problems." },
      { q: "One word for 'the murder of a king':", options: ["Regicide", "Homicide", "Genocide", "Patricide"], answer: 0, explain: "Regicide = killing of a king." },
      { q: "One word for 'a person who is unable to read or write':", options: ["Illiterate", "Ignorant", "Illegible", "Novice"], answer: 0, explain: "Illiterate = unable to read or write." },
      { q: "One word for 'that which lasts for a very short time':", options: ["Ephemeral", "Eternal", "Perpetual", "Permanent"], answer: 0, explain: "Ephemeral = short-lived, transient." },
      { q: "One word for 'a hater of mankind':", options: ["Misanthrope", "Philanthropist", "Misogynist", "Egotist"], answer: 0, explain: "Misanthrope = one who dislikes humankind." },
      { q: "One word for 'words engraved on a tomb':", options: ["Epitaph", "Epigram", "Epilogue", "Elegy"], answer: 0, explain: "Epitaph = inscription on a tombstone." },
      { q: "One word for 'a person who does not believe in the existence of God':", options: ["Atheist", "Theist", "Agnostic", "Heretic"], answer: 0, explain: "Atheist = disbelieves in God (Agnostic = unsure)." },
    ],
  },
  {
    id: "spelling",
    name: "Spelling Correction",
    questions: [
      { q: "Select the correctly spelt word:", options: ["Conscientious", "Consciencious", "Conscientous", "Concientious"], answer: 0, explain: "Correct: Conscientious." },
      { q: "Select the correctly spelt word:", options: ["Entrepreneur", "Entreprenur", "Entrepreneaur", "Enterpreneur"], answer: 0, explain: "Correct: Entrepreneur." },
      { q: "Select the correctly spelt word:", options: ["Millennium", "Millenium", "Milennium", "Millenniam"], answer: 0, explain: "Correct: Millennium (double l, double n)." },
      { q: "Select the correctly spelt word:", options: ["Bureaucracy", "Bureacracy", "Beaurocracy", "Buraucracy"], answer: 0, explain: "Correct: Bureaucracy." },
      { q: "Select the correctly spelt word:", options: ["Occurrence", "Occurence", "Ocurrence", "Occurrance"], answer: 0, explain: "Correct: Occurrence (double c, double r, -ence)." },
      { q: "Select the correctly spelt word:", options: ["Liaison", "Liason", "Liaision", "Liasion"], answer: 0, explain: "Correct: Liaison." },
      { q: "Select the correctly spelt word:", options: ["Maintenance", "Maintainance", "Maintenence", "Maintanance"], answer: 0, explain: "Correct: Maintenance." },
      { q: "Select the correctly spelt word:", options: ["Privilege", "Priviledge", "Privillege", "Privelege"], answer: 0, explain: "Correct: Privilege (no 'd')." },
      { q: "Select the correctly spelt word:", options: ["Accommodate", "Acommodate", "Accomodate", "Acomodate"], answer: 0, explain: "Correct: Accommodate (double c, double m)." },
      { q: "Select the correctly spelt word:", options: ["Rhythm", "Rythm", "Rhythem", "Rhthym"], answer: 0, explain: "Correct: Rhythm." },
      { q: "Select the correctly spelt word:", options: ["Embarrass", "Embarass", "Embbarass", "Embarras"], answer: 0, explain: "Correct: Embarrass (double r, double s)." },
      { q: "Select the correctly spelt word:", options: ["Perseverance", "Perseverence", "Persaverance", "Perserverance"], answer: 0, explain: "Correct: Perseverance." },
    ],
  },
  {
    id: "cloze",
    name: "Cloze Test",
    questions: [
      { q: "Cloze (Passage: 'The digital age has ___ creativity into a marketable commodity.') Choose for blank 1:", options: ["transformed", "transform", "transforming", "transforms"], answer: 0, explain: "Present perfect 'has transformed' fits." },
      { q: "Cloze: 'Algorithms ___ engagement by promoting similar content.' Choose:", options: ["maximise", "maximises", "maximising", "maximised"], answer: 0, explain: "Plural subject 'Algorithms' → 'maximise'." },
      { q: "Cloze: 'This ___ leads to filter bubbles.' Choose:", options: ["gradually", "gradual", "graduate", "graduation"], answer: 0, explain: "Adverb modifying verb 'leads' → 'gradually'." },
      { q: "Cloze: 'Natural selection is a ___ of evolution.' Choose:", options: ["mechanism", "mechanic", "mechanical", "mechanize"], answer: 0, explain: "Noun needed → 'mechanism'." },
      { q: "Cloze: 'The theory remains ___ to the uninitiated.' Choose:", options: ["inscrutable", "inscrutably", "inscrutability", "scrutinise"], answer: 0, explain: "Adjective after 'remains' → 'inscrutable'." },
      { q: "Cloze: 'Environmental stewardship ___ more than mere conservation.' Choose:", options: ["encompasses", "encompass", "encompassing", "encompassed"], answer: 0, explain: "Singular subject → 'encompasses'." },
      { q: "Cloze: 'Ecosystems are ___ networks of interdependent species.' Choose:", options: ["intricate", "intricately", "intricacy", "intrigue"], answer: 0, explain: "Adjective before noun → 'intricate'." },
      { q: "Cloze: 'Ecological stability is ___ upon balance.' Choose:", options: ["contingent", "contingency", "content", "continent"], answer: 0, explain: "'Contingent upon' = dependent on." },
      { q: "Cloze: 'Self-discovery is a lifelong ___ rather than a fixed answer.' Choose:", options: ["question", "questioned", "questioning", "questionable"], answer: 0, explain: "Noun → 'question'." },
      { q: "Cloze: 'The disruption ___ artists to follow standardized norms.' Choose:", options: ["compels", "compel", "compelling", "compelled"], answer: 0, explain: "Singular subject 'disruption' → 'compels'." },
      { q: "Cloze: 'Engagement metrics ___ genuine connection with data.' Choose:", options: ["conflate", "conflates", "conflating", "conflated"], answer: 0, explain: "Plural 'metrics' → 'conflate'." },
      { q: "Cloze: 'Vulnerability is often ___ rather than genuinely shared.' Choose:", options: ["performed", "perform", "performing", "performs"], answer: 0, explain: "Passive-style past participle → 'performed'." },
      { q: "Cloze: 'The report was ___ before the system breach.' Choose:", options: ["encrypted", "encrypt", "encrypting", "encrypts"], answer: 0, explain: "Passive past → 'encrypted'." },
      { q: "Cloze: 'Sustainable infrastructure often ___ an interdisciplinary approach.' Choose:", options: ["demands", "demand", "demanding", "demanded"], answer: 0, explain: "Singular subject → 'demands'." },
      { q: "Cloze: 'The habits gradually ___ our mental patterns.' Choose:", options: ["rewire", "rewires", "rewiring", "rewired"], answer: 0, explain: "Plural subject 'habits' → 'rewire'." },
      { q: "Cloze: 'He approached the flaw with gentle ___ and patience.' Choose:", options: ["self-compassion", "self-compassionate", "compassionately", "compassion's"], answer: 0, explain: "Noun after 'gentle' → 'self-compassion'." },
      { q: "Cloze: 'True growth is about ___ with one's values.' Choose:", options: ["alignment", "align", "aligning", "aligned"], answer: 0, explain: "Noun after 'about' → 'alignment'." },
      { q: "Cloze: 'The unpredictable weather posed a ___ challenge.' Choose:", options: ["formidable", "formidably", "formidability", "form"], answer: 0, explain: "Adjective before noun → 'formidable'." },
    ],
  },
  {
    id: "jumble",
    name: "Para-jumbles (Sentence Rearrangement)",
    questions: [
      { q: "Arrange: (P) It works by maximising engagement. (Q) Algorithms contribute to opinion fragmentation. (R) This creates filter bubbles. (S) Users see only similar content.", options: ["Q P S R", "P Q R S", "Q R P S", "R Q P S"], answer: 0, explain: "Q (intro) → P (how it works) → S (result: similar content) → R (filter bubbles)." },
      { q: "Arrange: (P) Cyberpunk is the first example. (Q) Science fiction has many subgenres. (R) This diversity benefits readers. (S) Space Opera is another example.", options: ["Q P S R", "Q S P R", "P Q S R", "Q P R S"], answer: 0, explain: "Q (topic) → P (example 1) → S (example 2) → R (conclusion)." },
      { q: "Arrange: (P) It defines what natural selection is. (Q) Natural selection is a mechanism of evolution. (R) It explains adaptation and survival. (S) Advantageous traits become more common.", options: ["Q P R S", "Q R P S", "P Q R S", "Q P S R"], answer: 0, explain: "Q (intro) → P (definition) → R (benefit) → S (long-term result)." },
      { q: "Arrange: (P) However, it requires consistent effort. (Q) Self-improvement is a gradual journey. (R) Small habits rewire our patterns. (S) The results are lasting.", options: ["Q R P S", "Q P R S", "P Q R S", "R Q P S"], answer: 0, explain: "Q (topic) → R (mechanism) → P (caveat) → S (outcome)." },
      { q: "Arrange: (P) They must balance many demands. (Q) Urban planners face myriad challenges. (R) An interdisciplinary approach is needed. (S) Only then can effective solutions emerge.", options: ["Q P R S", "Q R P S", "P Q R S", "Q P S R"], answer: 0, explain: "Q (subject) → P (their problem) → R (solution approach) → S (result)." },
      { q: "Arrange: (P) It sustains the biosphere ethically. (Q) Environmental stewardship is proactive. (R) Ecosystems depend on balance. (S) Domination disrupts stability.", options: ["Q P R S", "Q R S P", "P Q R S", "Q P S R"], answer: 0, explain: "Q (define) → P (its aim) → R (ecosystem fact) → S (contrast/consequence)." },
      { q: "Arrange: (P) These traditions harmonized with nature. (Q) Many societies used sacred groves. (R) They managed water communally. (S) Such practices ensured sustainability.", options: ["Q R P S", "Q P R S", "P Q R S", "R Q P S"], answer: 0, explain: "Q (example) → R (another) → P (common theme) → S (outcome)." },
      { q: "Arrange: (P) But experts remain divided. (Q) Quantum theory has profound implications. (R) It is inscrutable to the layperson. (S) The debate continues in academia.", options: ["Q R P S", "Q P R S", "P Q R S", "R Q P S"], answer: 0, explain: "Q (topic) → R (difficulty) → P (division) → S (ongoing debate)." },
      { q: "Arrange: (P) Reflection helps us learn. (Q) We should treat flaws gently. (R) Harsh criticism is counterproductive. (S) Patience yields real change.", options: ["Q R P S", "Q P R S", "P Q R S", "R Q P S"], answer: 0, explain: "Q (attitude) → R (what not to do) → P (helpful action) → S (result)." },
      { q: "Arrange: (P) It maximises visible short-term gains. (Q) The digital economy rewards engagement. (R) But depth is often sacrificed. (S) Quality suffers as a result.", options: ["Q P R S", "Q R P S", "P Q R S", "Q P S R"], answer: 0, explain: "Q (context) → P (how) → R (contrast) → S (consequence)." },
      { q: "Arrange: (P) Standardized norms limit expression. (Q) Artists once had unique visions. (R) Now algorithms shape their work. (S) True creativity is homogenized.", options: ["Q R P S", "Q P R S", "P Q R S", "R Q P S"], answer: 0, explain: "Q (past) → R (present cause) → P (effect) → S (result)." },
      { q: "Arrange: (P) The jury deliberated for hours. (Q) The trial was highly publicised. (R) Finally, they reached a verdict. (S) The accused was acquitted.", options: ["Q P R S", "Q R P S", "P Q R S", "Q P S R"], answer: 0, explain: "Q (setup) → P (process) → R (decision) → S (outcome)." },
      { q: "Arrange: (P) He worked hard every night. (Q) Ravi wanted to top the exam. (R) His perseverance paid off. (S) He secured the first rank.", options: ["Q P R S", "Q R P S", "P Q R S", "Q P S R"], answer: 0, explain: "Q (goal) → P (effort) → R (reward) → S (specific result)." },
      { q: "Arrange: (P) Pollution levels are rising. (Q) Cities face environmental threats. (R) Immediate action is essential. (S) Otherwise, the crisis will deepen.", options: ["Q P R S", "Q R P S", "P Q R S", "Q P S R"], answer: 0, explain: "Q (problem) → P (specific) → R (call to action) → S (warning)." },
      { q: "Arrange: (P) It began with a small idea. (Q) The startup grew rapidly. (R) Soon it became a global brand. (S) Investors flocked to fund it.", options: ["Q P S R", "Q P R S", "P Q R S", "P Q S R"], answer: 3, explain: "P (beginning) → Q (growth) → S (investors) → R (global). Best: P Q S R." },
    ],
  },
  {
    id: "rc",
    name: "Reading Comprehension",
    questions: [
      { q: "Passage A: 'Environmental stewardship encompasses more than mere conservation; it represents a proactive commitment to sustaining the biosphere through ethical engagement, scientific insight, and social responsibility.' — Stewardship is described as more than:", options: ["Mere conservation", "Scientific insight", "Social responsibility", "Ethical engagement"], answer: 0, explain: "Text: 'more than mere conservation'." },
      { q: "Passage A (cont.): Ecological stability is contingent upon:", options: ["Balance rather than domination", "Human domination", "Rapid industrialisation", "Isolation of species"], answer: 0, explain: "Text: 'contingent upon balance rather than domination'." },
      { q: "Passage A: Which societies are cited as exemplary?", options: ["Those that harmonized with natural rhythms", "Those that maximized industry", "Those that avoided agriculture", "Those that ignored ecology"], answer: 0, explain: "Text cites agrarian practices, sacred groves, community water systems." },
      { q: "Passage A: The tone of the passage is best described as:", options: ["Reflective and advocative", "Sarcastic", "Indifferent", "Humorous"], answer: 0, explain: "It advocates stewardship thoughtfully → reflective/advocative." },
      { q: "Passage A: 'Abiotic factors' in the passage refers to:", options: ["Non-living components of an ecosystem", "Living species", "Human activities", "Sacred rituals"], answer: 0, explain: "Abiotic = non-living (water, air, soil)." },
      { q: "Passage B: 'Self-improvement is a circular process of learning and adjustment, driven by small habits that gradually rewire mental patterns.' — The journey is described as:", options: ["A circular process of learning and adjustment", "A straight path", "A competitive race", "An occasional crisis response"], answer: 0, explain: "Text: 'circular process of learning and adjustment'." },
      { q: "Passage B: What attitude is recommended toward personal flaws?", options: ["Gentle self-compassion and patience", "Harsh criticism", "Complete indifference", "Avoidance"], answer: 0, explain: "Text recommends gentle self-compassion." },
      { q: "Passage B: According to the passage, small habits are effective because they:", options: ["Gradually rewire mental patterns", "Give instant results", "Require no effort", "Eliminate reflection"], answer: 0, explain: "Text: small habits 'gradually rewire mental patterns'." },
      { q: "Passage B: The central idea of the final sentence is that improvement is about:", options: ["Authenticity and alignment with one's values", "Imitating others' success", "Abandoning old identities", "External achievements"], answer: 0, explain: "Text emphasises authenticity and value-alignment." },
      { q: "Passage B: 'Reorients' in the passage most nearly means:", options: ["Shifts focus or direction", "Repeats", "Ignores", "Destroys"], answer: 0, explain: "Reorient = change direction/focus." },
      { q: "Passage C: 'In the digital age, creativity is transformed into a marketable commodity, governed by algorithms and engagement metrics.' — Creativity is turned into:", options: ["A marketable commodity", "A sacred art", "A free expression", "An academic subject"], answer: 0, explain: "Text: 'transformed into a marketable commodity'." },
      { q: "Passage C: What governs creativity in the digital age per the passage?", options: ["Algorithms and engagement metrics", "Government policy", "Traditional patrons", "Random chance"], answer: 0, explain: "Text: 'governed by algorithms and engagement metrics'." },
      { q: "Passage C: 'Homogenizing' effect means artists are pushed to:", options: ["Follow standardized norms", "Express unique visions", "Abandon technology", "Work independently"], answer: 0, explain: "Homogenizing → conform to standardized entrepreneurial norms." },
      { q: "Passage C: 'Conflates' in the passage means engagement metrics:", options: ["Treat genuine connection as mere data", "Separate data from emotion", "Ignore interaction", "Enhance authenticity"], answer: 0, explain: "Conflate = merge two things as one; genuine connection = quantifiable data." },
      { q: "Passage C: The author's attitude toward digital-age creativity is:", options: ["Critical", "Celebratory", "Neutral", "Indifferent"], answer: 0, explain: "The passage critiques commodification/homogenization → critical." },
      { q: "Passage D: 'Quantum theories, still largely inscrutable to the uninitiated, remain a contentious subject among eminent physicists.' — 'Inscrutable' means:", options: ["Difficult to understand", "Easy to grasp", "Widely accepted", "Completely proven"], answer: 0, explain: "Inscrutable = impossible to understand/interpret." },
      { q: "Passage D: The subject is described as 'contentious', meaning:", options: ["Causing disagreement", "Universally settled", "Trivial", "Outdated"], answer: 0, explain: "Contentious = causing debate/disagreement." },
      { q: "Passage D: 'The uninitiated' refers to:", options: ["Those without specialized knowledge", "Expert physicists", "Students of history", "Government officials"], answer: 0, explain: "Uninitiated = people lacking specialized knowledge." },
      { q: "Passage D: The physicists are engaged in:", options: ["Spirited academic discourse", "Silent agreement", "Practical experiments only", "Avoiding the topic"], answer: 0, explain: "Text: 'engaging in spirited academic discourse'." },
      { q: "Passage D: The overall subject of the passage is:", options: ["The complexity and debate around quantum theory", "The history of physics teaching", "A biography of a physicist", "An experiment's results"], answer: 0, explain: "It discusses quantum theory's implications and debate." },
      { q: "Passage E: 'Urban planners face myriad challenges, from sustainable infrastructure to social equity, demanding an interdisciplinary approach.' — 'Myriad' means:", options: ["Countless/very many", "Very few", "Simple", "Specific"], answer: 0, explain: "Myriad = a very large number." },
      { q: "Passage E: The challenges 'demand' what kind of approach?", options: ["Interdisciplinary", "Isolated", "Traditional", "Minimalist"], answer: 0, explain: "Text: 'demands an interdisciplinary approach'." },
      { q: "Passage E: 'Social equity' as a challenge relates to:", options: ["Fairness among people", "Building height limits", "Traffic control", "Water pipelines"], answer: 0, explain: "Social equity = fairness/justice among social groups." },
      { q: "Passage E: The passage implies that single-discipline solutions are:", options: ["Insufficient", "Ideal", "Cheapest", "Fastest"], answer: 0, explain: "Because an interdisciplinary approach is needed, single-discipline is insufficient." },
      { q: "Passage E: The purpose of the passage is to:", options: ["Highlight complexity of urban planning", "Criticise urban planners", "Promote one city", "Describe a building"], answer: 0, explain: "It highlights the multifaceted challenges of urban planning." },
      { q: "Vocabulary-in-context: In 'burgeoning quantum theories', 'burgeoning' means:", options: ["Rapidly growing", "Declining", "Ancient", "Stagnant"], answer: 0, explain: "Burgeoning = growing/expanding rapidly." },
      { q: "Vocabulary-in-context: 'Proactive commitment' implies action that is:", options: ["Anticipatory and initiating", "Reactive", "Reluctant", "Accidental"], answer: 0, explain: "Proactive = acting in advance, taking initiative." },
      { q: "Inference: If ecosystems rely on 'interdependent species', removing one species will likely:", options: ["Disturb the balance", "Have no effect", "Improve stability", "Increase domination"], answer: 0, explain: "Interdependence → removing one disturbs the whole." },
      { q: "Inference: A person following the self-improvement passage's advice would:", options: ["Be patient and reflect on mistakes", "Criticise themselves harshly", "Seek instant results", "Avoid change"], answer: 0, explain: "Passage advises patience, self-compassion, reflection." },
      { q: "Tone: The phrase 'so-called disruption' suggests the author is:", options: ["Skeptical of the term", "Enthusiastic about it", "Neutral", "Unaware of it"], answer: 0, explain: "'So-called' signals skepticism/doubt about the label." },
    ],
  },
];
