// SSC CGL — General Awareness: GEOGRAPHY (100 questions)
// Bilingual (English + Hindi), CGL level.

export const geographyMeta = {
  title: "Geography — 100 Practice Questions",
  exam: "SSC CGL — General Awareness",
  total: 100,
  note: "SSC CGL level Geography questions (Physical, Indian, World). Bilingual English + हिंदी. Answers 'Show Answer Key' me.",
};

export const geographySections = [
  {
    id: "physical",
    name: "Physical Geography (World)",
    questions: [
      { q: "The largest planet in the solar system is:", hi: "सौरमंडल का सबसे बड़ा ग्रह कौन-सा है?", options: ["Jupiter", "Saturn", "Earth", "Neptune"], answer: 0, explain: "Jupiter (Brihaspati) sabse bada grah hai." },
      { q: "The planet nearest to the Sun is:", hi: "सूर्य के सबसे निकट का ग्रह कौन-सा है?", options: ["Mercury", "Venus", "Earth", "Mars"], answer: 0, explain: "Mercury (Budh) Sun ke sabse nazdik hai." },
      { q: "Which planet is known as the 'Red Planet'?", hi: "किस ग्रह को 'लाल ग्रह' कहा जाता है?", options: ["Mars", "Jupiter", "Venus", "Saturn"], answer: 0, explain: "Mars (Mangal) ko Red Planet kehte hain (iron oxide)." },
      { q: "The Earth's innermost layer is called the:", hi: "पृथ्वी की सबसे भीतरी परत क्या कहलाती है?", options: ["Core", "Crust", "Mantle", "Lithosphere"], answer: 0, explain: "Prithvi ki sabse bhitri parat 'Core' (kendra) hai." },
      { q: "The largest ocean in the world is:", hi: "विश्व का सबसे बड़ा महासागर कौन-सा है?", options: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], answer: 0, explain: "Pacific (Prashant) Ocean sabse bada mahasagar hai." },
      { q: "The longest river in the world is:", hi: "विश्व की सबसे लंबी नदी कौन-सी है?", options: ["Nile", "Amazon", "Ganga", "Yangtze"], answer: 0, explain: "Nile nadi (Africa) sabse lambi mani jaati hai (Amazon debated)." },
      { q: "The highest mountain peak in the world is:", hi: "विश्व की सबसे ऊँची पर्वत चोटी कौन-सी है?", options: ["Mount Everest", "K2", "Kanchenjunga", "Kilimanjaro"], answer: 0, explain: "Mount Everest (8848 m) sabse unchi choti hai (Nepal)." },
      { q: "The largest desert in the world is:", hi: "विश्व का सबसे बड़ा रेगिस्तान कौन-सा है?", options: ["Sahara", "Thar", "Gobi", "Arabian"], answer: 0, explain: "Sahara (Africa) sabse bada garam registan hai." },
      { q: "The imaginary line dividing the Earth into two equal halves is the:", hi: "पृथ्वी को दो बराबर भागों में बाँटने वाली काल्पनिक रेखा कौन-सी है?", options: ["Equator", "Tropic of Cancer", "Prime Meridian", "International Date Line"], answer: 0, explain: "Equator (bhoomadhya rekha) prithvi ko do barabar bhaagon me baaton hai." },
      { q: "The Prime Meridian (0° longitude) passes through:", hi: "प्रधान याम्योत्तर (0° देशांतर) कहाँ से गुजरती है?", options: ["Greenwich (London)", "Delhi", "New York", "Paris"], answer: 0, explain: "Prime Meridian Greenwich (London) se gujarti hai." },
      { q: "The layer of atmosphere where weather changes occur is the:", hi: "वायुमंडल की जिस परत में मौसम परिवर्तन होते हैं?", options: ["Troposphere", "Stratosphere", "Mesosphere", "Ionosphere"], answer: 0, explain: "Troposphere me mausam sambandhi ghatnaen hoti hain." },
      { q: "The ozone layer is found in the:", hi: "ओज़ोन परत किस परत में पाई जाती है?", options: ["Stratosphere", "Troposphere", "Mesosphere", "Exosphere"], answer: 0, explain: "Ozone layer Stratosphere me hoti hai (UV rays se raksha)." },
      { q: "A volcano that may erupt in future is called:", hi: "जो ज्वालामुखी भविष्य में फट सकता है, वह क्या कहलाता है?", options: ["Dormant", "Active", "Extinct", "Dead"], answer: 0, explain: "Dormant (supt) volcano bhavishya me phat sakta hai." },
      { q: "The point on the Earth's surface directly above the earthquake focus is the:", hi: "भूकंप के केंद्र के ठीक ऊपर पृथ्वी की सतह पर बिंदु क्या कहलाता है?", options: ["Epicentre", "Focus", "Fault", "Seismic point"], answer: 0, explain: "Epicentre (adhikendra) focus ke thik upar hota hai." },
      { q: "Instrument to measure earthquake intensity:", hi: "भूकंप की तीव्रता मापने का यंत्र?", options: ["Seismograph", "Barometer", "Anemometer", "Hygrometer"], answer: 0, explain: "Seismograph bhukamp ki tivrata naapta hai." },
      { q: "The largest freshwater lake in the world is:", hi: "विश्व की सबसे बड़ी मीठे पानी की झील कौन-सी है?", options: ["Lake Superior", "Caspian Sea", "Lake Victoria", "Baikal"], answer: 0, explain: "Lake Superior sabse badi freshwater lake (area) hai." },
      { q: "The Tropic of Cancer is located at:", hi: "कर्क रेखा किस अक्षांश पर है?", options: ["23.5° N", "23.5° S", "0°", "66.5° N"], answer: 0, explain: "Tropic of Cancer 23.5° North par hai." },
      { q: "The deepest ocean trench is the:", hi: "सबसे गहरी महासागरीय खाई कौन-सी है?", options: ["Mariana Trench", "Java Trench", "Tonga Trench", "Puerto Rico Trench"], answer: 0, explain: "Mariana Trench (Pacific) sabse gehri hai." },
      { q: "Which is the smallest planet in the solar system?", hi: "सौरमंडल का सबसे छोटा ग्रह कौन-सा है?", options: ["Mercury", "Mars", "Venus", "Pluto"], answer: 0, explain: "Mercury sabse chhota grah hai (Pluto ab dwarf planet)." },
      { q: "The natural satellite of the Earth is:", hi: "पृथ्वी का प्राकृतिक उपग्रह कौन है?", options: ["Moon", "Sun", "Mars", "Venus"], answer: 0, explain: "Chandrma (Moon) prithvi ka prakritik upgrah hai." },
    ],
  },
  {
    id: "india-physical",
    name: "Indian Geography — Physical",
    questions: [
      { q: "The southernmost point of mainland India is:", hi: "भारतीय मुख्य भूमि का सबसे दक्षिणी बिंदु कौन-सा है?", options: ["Kanyakumari", "Indira Point", "Rameswaram", "Kochi"], answer: 0, explain: "Mainland ka southernmost point Kanyakumari; poore India ka Indira Point (Nicobar)." },
      { q: "The longest river in India is:", hi: "भारत की सबसे लंबी नदी कौन-सी है?", options: ["Ganga", "Godavari", "Yamuna", "Brahmaputra"], answer: 0, explain: "Ganga Bharat ki sabse lambi nadi hai." },
      { q: "The Tropic of Cancer passes through how many Indian states?", hi: "कर्क रेखा भारत के कितने राज्यों से गुजरती है?", options: ["8", "6", "10", "5"], answer: 0, explain: "Tropic of Cancer 8 rajyon se gujarti hai." },
      { q: "The highest mountain peak in India is:", hi: "भारत की सबसे ऊँची पर्वत चोटी कौन-सी है?", options: ["Kanchenjunga", "K2", "Nanda Devi", "Everest"], answer: 0, explain: "Kanchenjunga India ki sabse unchi choti hai (K2 POK me)." },
      { q: "The largest state of India by area is:", hi: "क्षेत्रफल की दृष्टि से भारत का सबसे बड़ा राज्य कौन-सा है?", options: ["Rajasthan", "Madhya Pradesh", "Maharashtra", "UP"], answer: 0, explain: "Rajasthan area me sabse bada rajya hai." },
      { q: "Which is the largest river in South India?", hi: "दक्षिण भारत की सबसे बड़ी नदी कौन-सी है?", options: ["Godavari", "Krishna", "Kaveri", "Narmada"], answer: 0, explain: "Godavari South India ki sabse badi nadi hai ('Dakshin Ganga')." },
      { q: "The 'Sundarbans' delta is formed by:", hi: "'सुंदरबन' डेल्टा किस नदी से बनता है?", options: ["Ganga-Brahmaputra", "Godavari", "Krishna", "Narmada"], answer: 0, explain: "Sundarbans Ganga-Brahmaputra delta hai (world's largest)." },
      { q: "The Western Ghats are also known as:", hi: "पश्चिमी घाट को और किस नाम से जाना जाता है?", options: ["Sahyadri", "Vindhya", "Aravalli", "Nilgiri"], answer: 0, explain: "Western Ghats ko Sahyadri kehte hain." },
      { q: "The oldest mountain range in India is:", hi: "भारत की सबसे प्राचीन पर्वत श्रृंखला कौन-सी है?", options: ["Aravalli", "Himalayas", "Satpura", "Vindhya"], answer: 0, explain: "Aravalli Bharat ki sabse prachin parvat shrinkhala hai." },
      { q: "Which river is called the 'Sorrow of Bihar'?", hi: "किस नदी को 'बिहार का शोक' कहा जाता है?", options: ["Kosi", "Damodar", "Ganga", "Gandak"], answer: 0, explain: "Kosi nadi ko 'Sorrow of Bihar' kaha jaata hai (baadh)." },
      { q: "Which river is called the 'Sorrow of Bengal'?", hi: "किस नदी को 'बंगाल का शोक' कहा जाता है?", options: ["Damodar", "Kosi", "Hooghly", "Teesta"], answer: 0, explain: "Damodar nadi ko 'Sorrow of Bengal' kaha jaata tha." },
      { q: "The Narmada river flows into the:", hi: "नर्मदा नदी किसमें गिरती है?", options: ["Arabian Sea", "Bay of Bengal", "Indian Ocean", "Ganga"], answer: 0, explain: "Narmada Arabian Sea me girti hai (west-flowing)." },
      { q: "The highest waterfall in India is:", hi: "भारत का सबसे ऊँचा जलप्रपात कौन-सा है?", options: ["Kunchikal Falls", "Jog Falls", "Dudhsagar", "Nohkalikai"], answer: 0, explain: "Kunchikal Falls (Karnataka) sabse uncha waterfall hai." },
      { q: "The Palk Strait separates India from:", hi: "पाक जलडमरूमध्य भारत को किससे अलग करता है?", options: ["Sri Lanka", "Bangladesh", "Myanmar", "Maldives"], answer: 0, explain: "Palk Strait India ko Sri Lanka se alag karta hai." },
      { q: "The largest saltwater lake in India is:", hi: "भारत की सबसे बड़ी खारे पानी की झील कौन-सी है?", options: ["Chilika Lake", "Wular Lake", "Sambhar Lake", "Dal Lake"], answer: 0, explain: "Chilika Lake (Odisha) sabse badi saltwater/brackish lake hai." },
      { q: "The 'Deccan Plateau' is mainly made of:", hi: "'दक्कन का पठार' मुख्यतः किससे बना है?", options: ["Basalt (volcanic rock)", "Granite", "Sandstone", "Limestone"], answer: 0, explain: "Deccan Plateau mainly basalt (jwalamukhi chattान) se bana hai." },
      { q: "The 'Duars' plains are found in:", hi: "'दुआर' मैदान कहाँ पाए जाते हैं?", options: ["West Bengal/Assam", "Punjab", "Rajasthan", "Kerala"], answer: 0, explain: "Duars plains West Bengal/Assam (Himalayan foothills) me hain." },
      { q: "The Wular Lake, largest freshwater lake in India, is in:", hi: "भारत की सबसे बड़ी मीठे पानी की झील वुलर कहाँ है?", options: ["Jammu & Kashmir", "Rajasthan", "Odisha", "Kerala"], answer: 0, explain: "Wular Lake Jammu & Kashmir me hai (largest freshwater)." },
      { q: "The Thar Desert is located mainly in:", hi: "थार मरुस्थल मुख्यतः कहाँ स्थित है?", options: ["Rajasthan", "Gujarat", "Punjab", "Haryana"], answer: 0, explain: "Thar Desert mukhyata Rajasthan me hai." },
      { q: "Which Indian state has the longest coastline?", hi: "भारत के किस राज्य की तटरेखा सबसे लंबी है?", options: ["Gujarat", "Andhra Pradesh", "Tamil Nadu", "Maharashtra"], answer: 0, explain: "Gujarat ki coastline (~1600 km) sabse lambi hai." },
    ],
  },
  {
    id: "india-economic",
    name: "Indian Geography — Resources & Economic",
    questions: [
      { q: "Which state is the largest producer of coal in India?", hi: "भारत में कोयले का सबसे बड़ा उत्पादक राज्य कौन-सा है?", options: ["Jharkhand", "Odisha", "Chhattisgarh", "West Bengal"], answer: 0, explain: "Jharkhand coal ka sabse bada producer hai." },
      { q: "The 'Green Revolution' in India was most successful in:", hi: "भारत में 'हरित क्रांति' सबसे अधिक सफल कहाँ रही?", options: ["Punjab & Haryana", "Bihar", "Kerala", "Assam"], answer: 0, explain: "Green Revolution Punjab aur Haryana me sabse safal rahi (wheat)." },
      { q: "India's largest tea-producing state is:", hi: "भारत का सबसे बड़ा चाय उत्पादक राज्य कौन-सा है?", options: ["Assam", "West Bengal", "Kerala", "Tamil Nadu"], answer: 0, explain: "Assam chai (tea) ka sabse bada producer hai." },
      { q: "The 'Manchester of India' is:", hi: "'भारत का मैनचेस्टर' किसे कहते हैं?", options: ["Ahmedabad", "Mumbai", "Kanpur", "Surat"], answer: 0, explain: "Ahmedabad ko 'Manchester of India' kaha jaata hai (cotton textile)." },
      { q: "The largest producer of sugarcane in India is:", hi: "भारत में गन्ने का सबसे बड़ा उत्पादक राज्य कौन-सा है?", options: ["Uttar Pradesh", "Maharashtra", "Karnataka", "Bihar"], answer: 0, explain: "Uttar Pradesh ganne ka sabse bada producer hai." },
      { q: "Which soil is best for cotton cultivation?", hi: "कपास की खेती के लिए कौन-सी मिट्टी सर्वोत्तम है?", options: ["Black soil (Regur)", "Red soil", "Alluvial soil", "Laterite soil"], answer: 0, explain: "Black soil (Regur/kaali mitti) cotton ke liye best hai (Deccan)." },
      { q: "The most widespread soil type in India is:", hi: "भारत में सबसे अधिक फैली मिट्टी कौन-सी है?", options: ["Alluvial soil", "Black soil", "Red soil", "Laterite"], answer: 0, explain: "Alluvial soil (jalodh mitti) sabse zyada faili hai (Indo-Gangetic plains)." },
      { q: "Which state is the largest producer of iron ore in India?", hi: "भारत में लौह अयस्क का सबसे बड़ा उत्पादक राज्य कौन-सा है?", options: ["Odisha", "Jharkhand", "Karnataka", "Goa"], answer: 0, explain: "Odisha iron ore ka sabse bada producer hai." },
      { q: "The 'Detroit of India' (automobile hub) is:", hi: "'भारत का डेट्रॉइट' (ऑटोमोबाइल हब) कौन है?", options: ["Chennai", "Pune", "Gurgaon", "Mumbai"], answer: 0, explain: "Chennai ko 'Detroit of India' kaha jaata hai (auto industry)." },
      { q: "Which crop is known as a Kharif crop?", hi: "कौन-सी फसल खरीफ फसल कहलाती है?", options: ["Rice", "Wheat", "Barley", "Mustard"], answer: 0, explain: "Rice (dhaan) Kharif crop hai (monsoon me boya jaata)." },
      { q: "Wheat is which type of crop?", hi: "गेहूँ किस प्रकार की फसल है?", options: ["Rabi", "Kharif", "Zaid", "Cash crop"], answer: 0, explain: "Wheat Rabi crop hai (winter me boya jaata)." },
      { q: "The largest producer of milk in India is:", hi: "भारत में दूध का सबसे बड़ा उत्पादक राज्य कौन-सा है?", options: ["Uttar Pradesh", "Rajasthan", "Gujarat", "Punjab"], answer: 0, explain: "Uttar Pradesh doodh ka sabse bada producer hai." },
      { q: "The 'White Revolution' in India is related to:", hi: "भारत में 'श्वेत क्रांति' किससे संबंधित है?", options: ["Milk production", "Wheat", "Fish", "Eggs"], answer: 0, explain: "White Revolution (Operation Flood) doodh utpadan se juda hai (Verghese Kurien)." },
      { q: "The 'Blue Revolution' is related to:", hi: "'नीली क्रांति' किससे संबंधित है?", options: ["Fish production", "Milk", "Wheat", "Water"], answer: 0, explain: "Blue Revolution matsya (fish) utpadan se juda hai." },
      { q: "Which is the largest producer of tobacco in India?", hi: "भारत में तंबाकू का सबसे बड़ा उत्पादक कौन है?", options: ["Andhra Pradesh", "Gujarat", "Karnataka", "UP"], answer: 0, explain: "Andhra Pradesh tambaku ka bada producer hai." },
    ],
  },
  {
    id: "world-geo",
    name: "World Geography — Places & Facts",
    questions: [
      { q: "The largest country in the world by area is:", hi: "क्षेत्रफल की दृष्टि से विश्व का सबसे बड़ा देश कौन-सा है?", options: ["Russia", "Canada", "China", "USA"], answer: 0, explain: "Russia area me sabse bada desh hai." },
      { q: "The largest continent is:", hi: "सबसे बड़ा महाद्वीप कौन-सा है?", options: ["Asia", "Africa", "Europe", "North America"], answer: 0, explain: "Asia sabse bada mahadweep hai." },
      { q: "The 'Sahara Desert' is located in:", hi: "'सहारा रेगिस्तान' कहाँ स्थित है?", options: ["Africa", "Asia", "Australia", "South America"], answer: 0, explain: "Sahara Africa me hai." },
      { q: "Mount Kilimanjaro is located in:", hi: "माउंट किलिमंजारो कहाँ स्थित है?", options: ["Tanzania (Africa)", "Nepal", "USA", "Chile"], answer: 0, explain: "Kilimanjaro Tanzania (Africa) me hai (highest in Africa)." },
      { q: "The Great Barrier Reef is located near:", hi: "ग्रेट बैरियर रीफ किसके पास है?", options: ["Australia", "USA", "India", "Japan"], answer: 0, explain: "Great Barrier Reef Australia ke paas hai (world's largest coral reef)." },
      { q: "The 'Land of the Rising Sun' is:", hi: "'उगते सूरज का देश' कौन-सा है?", options: ["Japan", "China", "Korea", "Thailand"], answer: 0, explain: "Japan ko 'Land of the Rising Sun' kehte hain." },
      { q: "The Amazon rainforest is mostly in:", hi: "अमेज़न वर्षावन अधिकतर किस देश में है?", options: ["Brazil", "Peru", "Colombia", "Venezuela"], answer: 0, explain: "Amazon rainforest zyadatar Brazil me hai." },
      { q: "The Suez Canal is located in:", hi: "स्वेज नहर कहाँ स्थित है?", options: ["Egypt", "Panama", "Turkey", "Iraq"], answer: 0, explain: "Suez Canal Egypt me hai (Mediterranean-Red Sea)." },
      { q: "The Panama Canal connects the Atlantic Ocean to the:", hi: "पनामा नहर अटलांटिक महासागर को किससे जोड़ती है?", options: ["Pacific Ocean", "Indian Ocean", "Arctic Ocean", "Red Sea"], answer: 0, explain: "Panama Canal Atlantic ko Pacific Ocean se jodti hai." },
      { q: "The country known as the 'Roof of the World' is:", hi: "'विश्व की छत' किस क्षेत्र को कहते हैं?", options: ["Tibet (Plateau)", "Nepal", "Switzerland", "Bhutan"], answer: 0, explain: "Tibet Plateau ko 'Roof of the World' kaha jaata hai." },
      { q: "The largest island in the world is:", hi: "विश्व का सबसे बड़ा द्वीप कौन-सा है?", options: ["Greenland", "Australia", "Madagascar", "Borneo"], answer: 0, explain: "Greenland sabse bada dweep hai (Australia continent hai)." },
      { q: "Which line separates North Korea and South Korea approximately?", hi: "उत्तर कोरिया और दक्षिण कोरिया को लगभग कौन-सी रेखा अलग करती है?", options: ["38th Parallel", "Radcliffe Line", "McMahon Line", "Durand Line"], answer: 0, explain: "38th Parallel North aur South Korea ko alag karti hai." },
      { q: "The 'McMahon Line' is the boundary between India and:", hi: "'मैकमोहन रेखा' भारत और किसके बीच सीमा है?", options: ["China", "Pakistan", "Nepal", "Bangladesh"], answer: 0, explain: "McMahon Line India-China border hai." },
      { q: "The 'Durand Line' separates Pakistan from:", hi: "'ड्यूरंड रेखा' पाकिस्तान को किससे अलग करती है?", options: ["Afghanistan", "India", "Iran", "China"], answer: 0, explain: "Durand Line Pakistan-Afghanistan border hai." },
      { q: "The world's highest plateau is the:", hi: "विश्व का सबसे ऊँचा पठार कौन-सा है?", options: ["Tibetan Plateau", "Deccan Plateau", "Colorado Plateau", "Bolivian Plateau"], answer: 0, explain: "Tibetan Plateau sabse uncha pathar hai." },
      { q: "The 'City of Seven Hills' is:", hi: "'सात पहाड़ियों का शहर' कौन-सा है?", options: ["Rome", "Paris", "London", "Athens"], answer: 0, explain: "Rome ko 'City of Seven Hills' kehte hain." },
      { q: "Which country has the largest population in the world (2023 onwards)?", hi: "विश्व में सबसे अधिक जनसंख्या वाला देश कौन है (2023 से)?", options: ["India", "China", "USA", "Indonesia"], answer: 0, explain: "India 2023 se sabse zyada aabadi wala desh ban gaya." },
      { q: "The equator passes through which continent?", hi: "भूमध्य रेखा किस महाद्वीप से गुजरती है?", options: ["Africa", "Europe", "Australia", "Antarctica"], answer: 0, explain: "Equator Africa (aur South America, Asia) se gujarti hai." },
      { q: "The 'Great Wall of China' can be best described as a:", hi: "'चीन की महान दीवार' सबसे अच्छे रूप में क्या है?", options: ["Man-made structure", "Natural barrier", "River", "Mountain"], answer: 0, explain: "Great Wall ek man-made (manav-nirmit) structure hai." },
      { q: "Which is the coldest continent?", hi: "सबसे ठंडा महाद्वीप कौन-सा है?", options: ["Antarctica", "Asia", "Europe", "North America"], answer: 0, explain: "Antarctica sabse thanda mahadweep hai." },
    ],
  },
  {
    id: "geo-misc",
    name: "Geography — Miscellaneous",
    questions: [
      { q: "The instrument used to measure atmospheric pressure is:", hi: "वायुमंडलीय दाब मापने का यंत्र कौन-सा है?", options: ["Barometer", "Thermometer", "Hygrometer", "Anemometer"], answer: 0, explain: "Barometer vayumandaliya dab naapta hai." },
      { q: "Wind speed is measured by:", hi: "हवा की गति किससे मापी जाती है?", options: ["Anemometer", "Barometer", "Hygrometer", "Seismograph"], answer: 0, explain: "Anemometer hawa ki gati naapta hai." },
      { q: "Humidity is measured by:", hi: "आर्द्रता किससे मापी जाती है?", options: ["Hygrometer", "Barometer", "Thermometer", "Anemometer"], answer: 0, explain: "Hygrometer aardrata (humidity) naapta hai." },
      { q: "The monsoon winds in India blow mainly from the:", hi: "भारत में मानसूनी हवाएँ मुख्यतः किस दिशा से चलती हैं?", options: ["Southwest", "Northeast", "North", "West"], answer: 0, explain: "Summer monsoon Southwest se aati hai (Arabian Sea + Bay of Bengal)." },
      { q: "Cherrapunji/Mawsynram, among the wettest places, are in:", hi: "सबसे अधिक वर्षा वाले चेरापूंजी/मॉसिनराम कहाँ हैं?", options: ["Meghalaya", "Assam", "Kerala", "West Bengal"], answer: 0, explain: "Mawsynram/Cherrapunji Meghalaya me hain (highest rainfall)." },
      { q: "The Coriolis effect is caused by the Earth's:", hi: "कोरिओलिस प्रभाव पृथ्वी के किस कारण होता है?", options: ["Rotation", "Revolution", "Tilt", "Gravity"], answer: 0, explain: "Coriolis effect prithvi ke rotation (ghumav) ke kaaran hota hai." },
      { q: "Which type of rainfall occurs due to mountains?", hi: "पर्वतों के कारण होने वाली वर्षा किस प्रकार की होती है?", options: ["Orographic", "Convectional", "Cyclonic", "Frontal"], answer: 0, explain: "Orographic rainfall parvaton ke kaaran hoti hai." },
      { q: "The largest gulf in the world is:", hi: "विश्व की सबसे बड़ी खाड़ी कौन-सी है?", options: ["Gulf of Mexico", "Persian Gulf", "Gulf of Aden", "Gulf of Bengal"], answer: 0, explain: "Gulf of Mexico sabse badi gulf hai." },
      { q: "The 'Roaring Forties' are strong winds found in the:", hi: "'गरजती चालीसा' प्रबल हवाएँ कहाँ पाई जाती हैं?", options: ["Southern Hemisphere (40° S)", "Equator", "Arctic", "Northern Hemisphere"], answer: 0, explain: "Roaring Forties Southern Hemisphere (40° S) me tez pashchimi hawaen hain." },
      { q: "The imaginary line where the date changes is the:", hi: "जिस काल्पनिक रेखा पर तिथि बदलती है वह क्या कहलाती है?", options: ["International Date Line", "Equator", "Prime Meridian", "Tropic of Cancer"], answer: 0, explain: "International Date Line (180° longitude) par tithi badalti hai." },
      { q: "Which is the largest delta in the world?", hi: "विश्व का सबसे बड़ा डेल्टा कौन-सा है?", options: ["Sundarbans (Ganga-Brahmaputra)", "Nile Delta", "Amazon Delta", "Mississippi Delta"], answer: 0, explain: "Sundarbans (Ganga-Brahmaputra) sabse bada delta hai." },
      { q: "El Nino is associated with the warming of which ocean?", hi: "अल नीनो किस महासागर के गर्म होने से संबंधित है?", options: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], answer: 0, explain: "El Nino Pacific Ocean ke garm hone se juda hai (monsoon par asar)." },
      { q: "The 'Latitude' of the Equator is:", hi: "भूमध्य रेखा का अक्षांश कितना है?", options: ["0°", "23.5°", "45°", "90°"], answer: 0, explain: "Equator ka latitude 0° hai." },
      { q: "Which planet is known as the 'Morning/Evening Star'?", hi: "किस ग्रह को 'भोर/संध्या का तारा' कहा जाता है?", options: ["Venus", "Mars", "Jupiter", "Mercury"], answer: 0, explain: "Venus (Shukra) ko Morning/Evening Star kehte hain (brightest)." },
      { q: "The point on Earth's orbit nearest to the Sun is called:", hi: "पृथ्वी की कक्षा में सूर्य के निकटतम बिंदु को क्या कहते हैं?", options: ["Perihelion", "Aphelion", "Equinox", "Solstice"], answer: 0, explain: "Perihelion prithvi ka Sun ke nazdik point hai (~Jan 3)." },
      { q: "The largest producer of coffee in India is:", hi: "भारत में कॉफी का सबसे बड़ा उत्पादक राज्य कौन-सा है?", options: ["Karnataka", "Kerala", "Tamil Nadu", "Assam"], answer: 0, explain: "Karnataka coffee ka sabse bada producer hai." },
      { q: "The 'Konkan Coast' lies between Mumbai and:", hi: "'कोंकण तट' मुंबई और किसके बीच स्थित है?", options: ["Goa", "Kochi", "Chennai", "Mangalore"], answer: 0, explain: "Konkan Coast Mumbai se Goa tak faila hai (west coast)." },
      { q: "The Jog Falls is located on which river?", hi: "जोग जलप्रपात किस नदी पर है?", options: ["Sharavati", "Kaveri", "Krishna", "Godavari"], answer: 0, explain: "Jog Falls Sharavati nadi (Karnataka) par hai." },
      { q: "The 'Loktak Lake' (floating lake) is in which state?", hi: "'लोकतक झील' (तैरती झील) किस राज्य में है?", options: ["Manipur", "Assam", "Meghalaya", "Nagaland"], answer: 0, explain: "Loktak Lake Manipur me hai (phumdis - floating islands)." },
      { q: "India's standard time (IST) is based on the longitude passing through:", hi: "भारतीय मानक समय (IST) किस देशांतर पर आधारित है?", options: ["82.5° E (Mirzapur)", "77° E", "90° E", "88° E"], answer: 0, explain: "IST 82.5° E longitude (Mirzapur, UP) par based hai." },
      { q: "The 'Nilgiri Hills' are located in:", hi: "'नीलगिरि पहाड़ियाँ' कहाँ स्थित हैं?", options: ["South India (Tamil Nadu/Kerala/Karnataka)", "North India", "Central India", "Northeast"], answer: 0, explain: "Nilgiri Hills South India (Western Ghats junction) me hain." },
      { q: "The Chambal river is a tributary of which river?", hi: "चंबल नदी किस नदी की सहायक है?", options: ["Yamuna", "Ganga", "Narmada", "Godavari"], answer: 0, explain: "Chambal Yamuna ki sahayak nadi hai." },
      { q: "The 'Palghat Gap' connects Tamil Nadu with:", hi: "'पालघाट दर्रा' तमिलनाडु को किससे जोड़ता है?", options: ["Kerala", "Karnataka", "Andhra Pradesh", "Goa"], answer: 0, explain: "Palghat Gap (Western Ghats) Tamil Nadu ko Kerala se jodta hai." },
      { q: "Which is the northernmost point of India?", hi: "भारत का सबसे उत्तरी बिंदु कौन-सा है?", options: ["Indira Col (Siachen)", "Kanyakumari", "Kibithu", "Indira Point"], answer: 0, explain: "India ka northernmost point Indira Col (Siachen area) hai." },
      { q: "The 'Zaid' crops are grown mainly in which season?", hi: "'ज़ायद' फसलें मुख्यतः किस मौसम में उगाई जाती हैं?", options: ["Summer (March-June)", "Winter", "Monsoon", "Autumn"], answer: 0, explain: "Zaid crops (watermelon, cucumber) garmi (March-June) me ugte hain." },
    ],
  },
];
