// SSC CGL — General Awareness: HISTORY (1000 questions)
// Bilingual (English + Hindi), CGL level. Mostly Indian history + some World history.
// { q, hi, options[4], answer index 0-3, explain }
// Built in topic batches for accuracy. Sections combined into one bank.

export const historyMeta = {
  title: "History — 200+ Practice Questions",
  exam: "SSC CGL — General Awareness",
  total: 201,
  note: "SSC CGL level History questions (Ancient, Medieval, Modern India + freedom struggle + World history). Bilingual English + हिंदी. Answers + explanation 'Show Answer Key' me.",
};

export const historySections = [
  {
    id: "ancient-ivc",
    name: "Ancient India — Indus Valley Civilization",
    questions: [
      { q: "The Indus Valley Civilization is also known as:", hi: "सिंधु घाटी सभ्यता को किस अन्य नाम से जाना जाता है?", options: ["Harappan Civilization", "Vedic Civilization", "Dravidian Civilization", "Mauryan Civilization"], answer: 0, explain: "Harappa pehla khoja gaya sthal tha, isliye ise Harappan Civilization bhi kehte hain." },
      { q: "Who discovered the Harappan site of Mohenjo-daro?", hi: "मोहनजोदड़ो की खोज किसने की थी?", options: ["R. D. Banerji", "Daya Ram Sahni", "John Marshall", "Rakhal Das"], answer: 0, explain: "R. D. Banerji ne 1922 me Mohenjo-daro ki khoj ki thi." },
      { q: "Harappa was discovered by:", hi: "हड़प्पा की खोज किसने की?", options: ["Daya Ram Sahni", "R. D. Banerji", "John Marshall", "Mortimer Wheeler"], answer: 0, explain: "Daya Ram Sahni ne 1921 me Harappa ki khoj ki." },
      { q: "The Great Bath was found at which site?", hi: "विशाल स्नानागार (Great Bath) किस स्थल पर मिला?", options: ["Mohenjo-daro", "Harappa", "Lothal", "Kalibangan"], answer: 0, explain: "Great Bath Mohenjo-daro me mila, jo public bathing/ritual ke liye tha." },
      { q: "Which Harappan site is known as the port city?", hi: "कौन-सा हड़प्पा स्थल बंदरगाह नगर के रूप में जाना जाता है?", options: ["Lothal", "Harappa", "Kalibangan", "Ropar"], answer: 0, explain: "Lothal (Gujarat) me dockyard mila, ye ek prasiddh bandargah tha." },
      { q: "The Indus Valley Civilization belonged to which age?", hi: "सिंधु घाटी सभ्यता किस युग से संबंधित थी?", options: ["Bronze Age", "Iron Age", "Stone Age", "Copper Age"], answer: 0, explain: "IVC Bronze Age (Kansya Yug) ki sabhyata thi." },
      { q: "Dholavira, a Harappan site, is located in which state?", hi: "हड़प्पा स्थल धौलावीरा किस राज्य में स्थित है?", options: ["Gujarat", "Rajasthan", "Punjab", "Haryana"], answer: 0, explain: "Dholavira Gujarat ke Kutch me hai, apne water management ke liye prasiddh." },
      { q: "Which metal was NOT known to the Indus Valley people?", hi: "सिंधु घाटी के लोगों को कौन-सी धातु ज्ञात नहीं थी?", options: ["Iron", "Copper", "Bronze", "Gold"], answer: 0, explain: "IVC ke logon ko loha (iron) ka gyaan nahi tha; woh tanba, kansya, sona jaante the." },
      { q: "The famous 'Dancing Girl' bronze statue was found at:", hi: "प्रसिद्ध 'नर्तकी' (Dancing Girl) की कांस्य मूर्ति कहाँ मिली?", options: ["Mohenjo-daro", "Harappa", "Lothal", "Chanhudaro"], answer: 0, explain: "Dancing Girl ki kansya murti Mohenjo-daro se mili." },
      { q: "Kalibangan, known for ploughed fields, is in which state?", hi: "जुते हुए खेतों के लिए प्रसिद्ध कालीबंगन किस राज्य में है?", options: ["Rajasthan", "Gujarat", "Punjab", "Haryana"], answer: 0, explain: "Kalibangan (Rajasthan) me jute hue khet (ploughed field) ke pramaan mile." },
      { q: "The Harappan script is:", hi: "हड़प्पा लिपि कैसी है?", options: ["Undeciphered (pictographic)", "Brahmi based", "Devanagari", "Fully deciphered"], answer: 0, explain: "Harappan lipi ab tak padhi nahi ja saki; ye pictographic (boustrophedon) thi." },
      { q: "Which animal was NOT known to the Indus people (not depicted on seals)?", hi: "सिंधु लोगों को कौन-सा जानवर ज्ञात नहीं था (मुहरों पर नहीं मिला)?", options: ["Horse", "Bull", "Elephant", "Tiger"], answer: 0, explain: "Ghoda (horse) IVC seals par nahi mila; bull, elephant, tiger mile." },
      { q: "The Indus Valley Civilization was primarily a/an:", hi: "सिंधु घाटी सभ्यता मुख्यतः कैसी थी?", options: ["Urban civilization", "Rural civilization", "Nomadic society", "Forest society"], answer: 0, explain: "IVC ek nagariya (urban) sabhyata thi with planned cities." },
      { q: "Which site is famous for a dockyard?", hi: "गोदी (dockyard) के लिए कौन-सा स्थल प्रसिद्ध है?", options: ["Lothal", "Kalibangan", "Ropar", "Banawali"], answer: 0, explain: "Lothal me duniya ka pehla gyaat dockyard mila." },
      { q: "The Indus cities had a well-planned:", hi: "सिंधु नगरों में सुव्यवस्थित क्या था?", options: ["Drainage system", "Railway system", "Postal system", "Banking system"], answer: 0, explain: "IVC apni advanced drainage (jal-nikasi) system ke liye prasiddh thi." },
      { q: "Which river was most important to the Harappan Civilization?", hi: "हड़प्पा सभ्यता के लिए कौन-सी नदी सबसे महत्वपूर्ण थी?", options: ["Indus", "Ganga", "Yamuna", "Godavari"], answer: 0, explain: "Sindhu (Indus) nadi IVC ke liye sabse mahatvapurna thi." },
      { q: "Banawali, a Harappan site, is located in:", hi: "हड़प्पा स्थल बनावली कहाँ स्थित है?", options: ["Haryana", "Gujarat", "Rajasthan", "Punjab"], answer: 0, explain: "Banawali Haryana me sthit hai." },
      { q: "The seals of the Indus Valley were mostly made of:", hi: "सिंधु घाटी की मुहरें मुख्यतः किससे बनी थीं?", options: ["Steatite", "Gold", "Iron", "Wood"], answer: 0, explain: "Seals mostly steatite (sendhwa patthar) se bani thi." },
      { q: "The most common motif on Indus seals was:", hi: "सिंधु मुहरों पर सबसे आम चित्र कौन-सा था?", options: ["Unicorn (one-horned bull)", "Lion", "Horse", "Peacock"], answer: 0, explain: "Ek-singh wala saand (unicorn) sabse common seal motif tha." },
      { q: "Chanhudaro is famous for:", hi: "चन्हूदड़ो किसके लिए प्रसिद्ध है?", options: ["Bead-making", "Great Bath", "Dockyard", "Fire altars"], answer: 0, explain: "Chanhudaro bead-making (manka nirmaan) ke liye prasiddh tha." },
    ],
  },
  {
    id: "ancient-vedic",
    name: "Ancient India — Vedic Period",
    questions: [
      { q: "The Vedas are how many in number?", hi: "वेद कितने हैं?", options: ["Four", "Three", "Five", "Two"], answer: 0, explain: "Chaar Ved hain: Rigveda, Samaveda, Yajurveda, Atharvaveda." },
      { q: "Which is the oldest Veda?", hi: "सबसे प्राचीन वेद कौन-सा है?", options: ["Rigveda", "Samaveda", "Yajurveda", "Atharvaveda"], answer: 0, explain: "Rigveda sabse prachin Ved hai." },
      { q: "The Gayatri Mantra is found in which Veda?", hi: "गायत्री मंत्र किस वेद में है?", options: ["Rigveda", "Samaveda", "Yajurveda", "Atharvaveda"], answer: 0, explain: "Gayatri Mantra Rigveda me hai, Rishi Vishwamitra dwara rachit." },
      { q: "The Veda dealing with music is:", hi: "संगीत से संबंधित वेद कौन-सा है?", options: ["Samaveda", "Rigveda", "Yajurveda", "Atharvaveda"], answer: 0, explain: "Samaveda sangeet (music) se juda hai; Indian music ka source." },
      { q: "'Satyameva Jayate' is taken from which Upanishad?", hi: "'सत्यमेव जयते' किस उपनिषद से लिया गया है?", options: ["Mundaka Upanishad", "Katha Upanishad", "Isha Upanishad", "Kena Upanishad"], answer: 0, explain: "'Satyameva Jayate' Mundaka Upanishad se liya gaya hai." },
      { q: "The four Vedas together with Brahmanas, Aranyakas and Upanishads are called:", hi: "चारों वेद, ब्राह्मण, आरण्यक और उपनिषद मिलाकर क्या कहलाते हैं?", options: ["Vedic literature", "Puranas", "Smritis", "Sutras"], answer: 0, explain: "Ye sab milkar Vedic literature kehlate hain." },
      { q: "The term 'Aryan' primarily refers to:", hi: "'आर्य' शब्द मुख्यतः किसे दर्शाता है?", options: ["A language group / noble", "A race", "A religion", "A kingdom"], answer: 0, explain: "'Arya' ek bhasha-samuh/‘noble’ ke arth me use hota hai, race nahi." },
      { q: "In the Rigvedic period, the head of the family was called:", hi: "ऋग्वैदिक काल में परिवार का मुखिया क्या कहलाता था?", options: ["Grihapati / Kulapa", "Rajan", "Purohita", "Senani"], answer: 0, explain: "Parivar ka mukhiya Kulapa/Grihapati kehlata tha." },
      { q: "The Rigvedic god associated with rain and thunder was:", hi: "वर्षा और गर्जन से संबंधित ऋग्वैदिक देवता कौन था?", options: ["Indra", "Agni", "Varuna", "Surya"], answer: 0, explain: "Indra varsha aur vajra (thunder) ke devta the, Rigveda me sabse zyada mantra unke liye." },
      { q: "The god Agni was the mediator between:", hi: "अग्नि देवता किसके बीच मध्यस्थ थे?", options: ["Gods and men", "Kings and people", "Earth and sky", "Life and death"], answer: 0, explain: "Agni devtaon aur manushyon ke beech madhyasth mane jaate the." },
      { q: "Which river is most mentioned in the Rigveda?", hi: "ऋग्वेद में किस नदी का सर्वाधिक उल्लेख है?", options: ["Sindhu (Indus)", "Ganga", "Saraswati", "Yamuna"], answer: 0, explain: "Rigveda me Sindhu nadi ka sabse zyada zikra hai." },
      { q: "The Later Vedic period saw the rise of which social system?", hi: "उत्तर वैदिक काल में किस सामाजिक व्यवस्था का उदय हुआ?", options: ["Varna (caste) system", "Feudalism", "Slavery", "Guild system"], answer: 0, explain: "Uttar Vedic kaal me varna vyavastha (chaturvarna) majboot hui." },
      { q: "The famous 'Purushasukta', explaining the varna system, is in:", hi: "वर्ण व्यवस्था बताने वाला प्रसिद्ध 'पुरुषसूक्त' किसमें है?", options: ["Rigveda (10th Mandala)", "Samaveda", "Atharvaveda", "Yajurveda"], answer: 0, explain: "Purushasukta Rigveda ke 10ve mandala me hai." },
      { q: "The word 'Gotra' first appears in which text?", hi: "'गोत्र' शब्द सर्वप्रथम किस ग्रंथ में मिलता है?", options: ["Atharvaveda", "Rigveda", "Samaveda", "Yajurveda"], answer: 0, explain: "'Gotra' shabd Atharvaveda me pehli baar aaya." },
      { q: "The 'Sabha' and 'Samiti' in the Vedic age were:", hi: "वैदिक काल में 'सभा' और 'समिति' क्या थीं?", options: ["Popular assemblies", "Military units", "Trade guilds", "Religious orders"], answer: 0, explain: "Sabha aur Samiti janapadiya/lok assemblies thi jo rajan ko salah deti thi." },
      { q: "The four Ashramas in Vedic life were Brahmacharya, Grihastha, Vanaprastha and:", hi: "वैदिक जीवन के चार आश्रम— ब्रह्मचर्य, गृहस्थ, वानप्रस्थ और?", options: ["Sanyasa", "Rajya", "Yajna", "Dharma"], answer: 0, explain: "Chautha ashram Sanyasa (tyaag) tha." },
      { q: "The Aranyakas are also called:", hi: "आरण्यकों को और क्या कहा जाता है?", options: ["Forest books", "Song books", "Law books", "War books"], answer: 0, explain: "Aranyaka 'van ki pustakein' (forest books) kehlate hain." },
      { q: "The Purusharthas are Dharma, Artha, Kama and:", hi: "पुरुषार्थ हैं— धर्म, अर्थ, काम और?", options: ["Moksha", "Yajna", "Karma", "Bhakti"], answer: 0, explain: "Chautha purushartha Moksha hai." },
      { q: "'Dharmashastra' texts deal with:", hi: "'धर्मशास्त्र' ग्रंथ किससे संबंधित हैं?", options: ["Law and conduct", "Astronomy", "Medicine", "Warfare"], answer: 0, explain: "Dharmashastra kanoon aur aachaar-vyavahaar se sambandhit hain (jaise Manusmriti)." },
      { q: "The Later Vedic people mainly worshipped which god (who rose in importance)?", hi: "उत्तर वैदिक लोग मुख्यतः किस देवता की पूजा करते थे (जिसका महत्व बढ़ा)?", options: ["Prajapati", "Indra", "Agni", "Varuna"], answer: 0, explain: "Uttar Vedic kaal me Prajapati (creator) ka mahatva badha." },
    ],
  },
  {
    id: "ancient-religion",
    name: "Ancient India — Buddhism, Jainism & Mahajanapadas",
    questions: [
      { q: "Gautam Buddha was born at:", hi: "गौतम बुद्ध का जन्म कहाँ हुआ था?", options: ["Lumbini", "Bodh Gaya", "Sarnath", "Kushinagar"], answer: 0, explain: "Buddha ka janm Lumbini (Nepal) me hua tha." },
      { q: "Buddha attained enlightenment at:", hi: "बुद्ध को ज्ञान की प्राप्ति कहाँ हुई?", options: ["Bodh Gaya", "Lumbini", "Sarnath", "Kushinagar"], answer: 0, explain: "Bodh Gaya (Bihar) me peepal ke ped ke neeche gyaan mila." },
      { q: "Buddha delivered his first sermon at:", hi: "बुद्ध ने अपना पहला उपदेश कहाँ दिया?", options: ["Sarnath", "Bodh Gaya", "Lumbini", "Rajgir"], answer: 0, explain: "Pehla upadesh Sarnath me diya — ise 'Dharma Chakra Pravartana' kehte hain." },
      { q: "Buddha attained Mahaparinirvana (death) at:", hi: "बुद्ध का महापरिनिर्वाण (मृत्यु) कहाँ हुआ?", options: ["Kushinagar", "Sarnath", "Bodh Gaya", "Lumbini"], answer: 0, explain: "Buddha ka nirvana Kushinagar (UP) me hua." },
      { q: "Who founded Jainism as the 24th Tirthankara?", hi: "24वें तीर्थंकर के रूप में जैन धर्म को किसने आगे बढ़ाया?", options: ["Mahavira", "Parshvanatha", "Rishabhanatha", "Gautam Buddha"], answer: 0, explain: "Mahavira 24ve (aur antim) Tirthankar the; Rishabhanatha pehle the." },
      { q: "The three jewels (Triratna) of Jainism are Right Faith, Right Knowledge and:", hi: "जैन धर्म के त्रिरत्न— सम्यक् दर्शन, सम्यक् ज्ञान और?", options: ["Right Conduct", "Right Speech", "Right Action", "Right Living"], answer: 0, explain: "Teesra ratna Samyak Charitra (Right Conduct) hai." },
      { q: "The first Buddhist Council was held at:", hi: "प्रथम बौद्ध संगीति कहाँ हुई थी?", options: ["Rajgriha", "Vaishali", "Pataliputra", "Kashmir"], answer: 0, explain: "Pehli Buddhist Council Rajgriha me Ajatashatru ke samay hui." },
      { q: "The fourth Buddhist Council was held during the reign of:", hi: "चौथी बौद्ध संगीति किसके शासनकाल में हुई?", options: ["Kanishka", "Ashoka", "Ajatashatru", "Kalashoka"], answer: 0, explain: "Chauthi Council Kanishka ke samay Kashmir me hui; yahan Buddhism Hinayana-Mahayana me bata." },
      { q: "Mahavira attained Kaivalya (enlightenment) at:", hi: "महावीर को कैवल्य (ज्ञान) की प्राप्ति कहाँ हुई?", options: ["Jrimbhikagrama", "Pavapuri", "Kundagrama", "Vaishali"], answer: 0, explain: "Mahavira ko Jrimbhikagrama me Rijupalika nadi ke tat par kaivalya mila." },
      { q: "Buddhism is based on the Four Noble Truths and the:", hi: "बौद्ध धर्म चार आर्य सत्य और किस पर आधारित है?", options: ["Eightfold Path", "Ten Commandments", "Five Vows", "Three Jewels"], answer: 0, explain: "Ashtangik Marg (Eightfold Path) Buddhism ka aadhaar hai." },
      { q: "How many Mahajanapadas existed in the 6th century BCE?", hi: "छठी शताब्दी ईसा पूर्व में कितने महाजनपद थे?", options: ["16", "12", "8", "20"], answer: 0, explain: "6th century BCE me 16 Mahajanapadas the (Buddhist text Anguttara Nikaya me)." },
      { q: "Which Mahajanapada eventually became the most powerful?", hi: "कौन-सा महाजनपद अंततः सबसे शक्तिशाली बना?", options: ["Magadha", "Kosala", "Avanti", "Vatsa"], answer: 0, explain: "Magadha sabse shaktishali bana aur Mauryan samrajya ka aadhaar bana." },
      { q: "The language used by Buddha to preach was:", hi: "बुद्ध ने उपदेश किस भाषा में दिए?", options: ["Pali", "Sanskrit", "Prakrit", "Magadhi"], answer: 0, explain: "Buddha ne Pali bhasha me upadesh diye (aam janta ki bhasha)." },
      { q: "The Jain text written in Prakrit is:", hi: "प्राकृत में लिखा जैन ग्रंथ कौन-सा है?", options: ["Angas", "Tripitaka", "Vedas", "Puranas"], answer: 0, explain: "Jain Agamas/Angas Prakrit (Ardhamagadhi) me likhe gaye." },
      { q: "Bimbisara belonged to which dynasty of Magadha?", hi: "बिम्बिसार मगध के किस वंश से थे?", options: ["Haryanka", "Nanda", "Shishunaga", "Maurya"], answer: 0, explain: "Bimbisara Haryanka vansh ke the, Magadha ke pratapi raja." },
      { q: "The Buddhist sacred texts are collectively called:", hi: "बौद्ध पवित्र ग्रंथ सामूहिक रूप से क्या कहलाते हैं?", options: ["Tripitaka", "Angas", "Vedas", "Agamas"], answer: 0, explain: "Tripitaka (Vinaya, Sutta, Abhidhamma) Buddhist granth hain." },
    ],
  },
  {
    id: "ancient-mauryan",
    name: "Ancient India — Mauryan & Gupta Empires",
    questions: [
      { q: "Who founded the Mauryan Empire?", hi: "मौर्य साम्राज्य की स्थापना किसने की?", options: ["Chandragupta Maurya", "Ashoka", "Bindusara", "Chanakya"], answer: 0, explain: "Chandragupta Maurya ne 322 BCE me Mauryan samrajya sthapit kiya (Chanakya ki madad se)." },
      { q: "Chanakya (Kautilya) wrote which famous treatise?", hi: "चाणक्य (कौटिल्य) ने कौन-सा प्रसिद्ध ग्रंथ लिखा?", options: ["Arthashastra", "Indica", "Mudrarakshasa", "Ramcharitmanas"], answer: 0, explain: "Kautilya ne 'Arthashastra' likhi — rajya-neeti aur arthvyavastha ka granth." },
      { q: "Who wrote 'Indica'?", hi: "'इंडिका' किसने लिखी?", options: ["Megasthenes", "Kautilya", "Fa-Hien", "Hiuen Tsang"], answer: 0, explain: "Megasthenes (Greek ambassador) ne Chandragupta ke darbaar par 'Indica' likhi." },
      { q: "Ashoka embraced Buddhism after which war?", hi: "अशोक ने किस युद्ध के बाद बौद्ध धर्म अपनाया?", options: ["Kalinga War", "Battle of Hydaspes", "Battle of Kannauj", "Battle of Talikota"], answer: 0, explain: "Kalinga Yudh (261 BCE) ke rakt-paat ke baad Ashoka ne Buddhism apnaya." },
      { q: "Ashoka's inscriptions are mostly written in which script?", hi: "अशोक के अभिलेख अधिकतर किस लिपि में हैं?", options: ["Brahmi", "Kharosthi", "Devanagari", "Greek"], answer: 0, explain: "Ashoka ke shilalekh mostly Brahmi lipi me hain." },
      { q: "The Sarnath Lion Capital of Ashoka is India's:", hi: "अशोक की सारनाथ सिंह स्तंभ शीर्ष भारत का क्या है?", options: ["National Emblem", "National Flag", "National Animal", "National Flower"], answer: 0, explain: "Sarnath ka Lion Capital Bharat ka Rashtriya Chinh (National Emblem) hai." },
      { q: "Who was the last Mauryan ruler?", hi: "अंतिम मौर्य शासक कौन था?", options: ["Brihadratha", "Bindusara", "Dasharatha", "Samprati"], answer: 0, explain: "Antim Mauryan shasak Brihadratha tha, jise Pushyamitra Shunga ne mara." },
      { q: "The Gupta Empire is called the 'Golden Age' of:", hi: "गुप्त साम्राज्य को किसका 'स्वर्ण युग' कहा जाता है?", options: ["Ancient India", "Medieval India", "Modern India", "South India"], answer: 0, explain: "Gupta kaal prachin Bharat ka 'Swarna Yug' mana jaata hai (art, science, literature)." },
      { q: "Who founded the Gupta Empire?", hi: "गुप्त साम्राज्य की स्थापना किसने की?", options: ["Sri Gupta", "Chandragupta I", "Samudragupta", "Chandragupta II"], answer: 0, explain: "Sri Gupta ne Gupta vansh ki neev daali; Chandragupta I ne vistaar kiya." },
      { q: "Samudragupta is known as the 'Napoleon of India'. Who gave this title?", hi: "समुद्रगुप्त को 'भारत का नेपोलियन' किसने कहा?", options: ["V. A. Smith", "R. C. Majumdar", "D. D. Kosambi", "R. S. Sharma"], answer: 0, explain: "V. A. Smith ne Samudragupta ko 'Napoleon of India' kaha (uski vijayon ke kaaran)." },
      { q: "The famous Iron Pillar at Delhi (rust-free) belongs to the era of:", hi: "दिल्ली का प्रसिद्ध लौह स्तंभ (जंग-रहित) किसके काल का है?", options: ["Chandragupta II", "Ashoka", "Kanishka", "Harsha"], answer: 0, explain: "Delhi ka Iron Pillar Chandragupta II (Vikramaditya) ke samay ka mana jaata hai." },
      { q: "Aryabhata, the great mathematician-astronomer, lived during the:", hi: "महान गणितज्ञ-खगोलशास्त्री आर्यभट किस काल में थे?", options: ["Gupta period", "Mauryan period", "Mughal period", "Chola period"], answer: 0, explain: "Aryabhata Gupta kaal me the; unhone 'Aryabhatiya' likhi aur shunya/zero ka concept diya." },
      { q: "The Chinese pilgrim who visited during Chandragupta II's reign was:", hi: "चंद्रगुप्त द्वितीय के समय आने वाला चीनी यात्री कौन था?", options: ["Fa-Hien", "Hiuen Tsang", "I-Tsing", "Megasthenes"], answer: 0, explain: "Fa-Hien Chandragupta II ke samay Bharat aaya." },
      { q: "Kalidasa, the great poet, is associated with which ruler's court?", hi: "महान कवि कालिदास किसके दरबार से जुड़े थे?", options: ["Chandragupta II", "Ashoka", "Harsha", "Kanishka"], answer: 0, explain: "Kalidasa Chandragupta II (Vikramaditya) ke navratnas me the." },
      { q: "Who started the Saka era in 78 CE?", hi: "78 ईस्वी में शक संवत किसने आरंभ किया?", options: ["Kanishka", "Ashoka", "Samudragupta", "Harsha"], answer: 0, explain: "Kushana raja Kanishka ne 78 CE me Saka Samvat shuru kiya (jo India ka rashtriya calendar hai)." },
      { q: "Nalanda University flourished mainly during which period?", hi: "नालंदा विश्वविद्यालय मुख्यतः किस काल में फला-फूला?", options: ["Gupta period onwards", "Mauryan period", "Mughal period", "Chola period"], answer: 0, explain: "Nalanda Gupta kaal se aage tak Buddhist shiksha ka kendra raha." },
    ],
  },
  {
    id: "ancient-sangam",
    name: "Ancient India — Sangam Age & Post-Gupta",
    questions: [
      { q: "The Sangam literature was composed in which language?", hi: "संगम साहित्य किस भाषा में रचा गया?", options: ["Tamil", "Sanskrit", "Prakrit", "Pali"], answer: 0, explain: "Sangam sahitya Tamil bhasha me tha (South India)." },
      { q: "The three main dynasties of the Sangam Age were Cholas, Cheras and:", hi: "संगम काल के तीन मुख्य राजवंश— चोल, चेर और?", options: ["Pandyas", "Pallavas", "Chalukyas", "Rashtrakutas"], answer: 0, explain: "Teen mukhya vansh: Chola, Chera, Pandya." },
      { q: "Harshavardhana's capital was:", hi: "हर्षवर्धन की राजधानी कहाँ थी?", options: ["Kannauj", "Thanesar", "Pataliputra", "Ujjain"], answer: 0, explain: "Harsha ne apni rajdhani Thanesar se Kannauj sthanantrit ki." },
      { q: "The Chinese traveller who visited Harsha's court was:", hi: "हर्ष के दरबार में आने वाला चीनी यात्री कौन था?", options: ["Hiuen Tsang", "Fa-Hien", "I-Tsing", "Megasthenes"], answer: 0, explain: "Hiuen Tsang (Xuanzang) Harsha ke samay Bharat aaya." },
      { q: "Harsha wrote which Sanskrit plays?", hi: "हर्ष ने कौन-से संस्कृत नाटक लिखे?", options: ["Nagananda, Ratnavali, Priyadarshika", "Abhijnanashakuntalam", "Mrichchhakatika", "Mudrarakshasa"], answer: 0, explain: "Harsha ne Nagananda, Ratnavali, Priyadarshika likhe." },
      { q: "'Harshacharita', the biography of Harsha, was written by:", hi: "हर्ष की जीवनी 'हर्षचरित' किसने लिखी?", options: ["Banabhatta", "Kalidasa", "Vishakhadatta", "Kalhana"], answer: 0, explain: "Banabhatta ne Harshacharita likhi (Harsha ke darbaari kavi)." },
      { q: "The Pallava dynasty is famous for the rock-cut temples at:", hi: "पल्लव वंश किस स्थान के शैलकृत मंदिरों के लिए प्रसिद्ध है?", options: ["Mahabalipuram", "Ellora", "Ajanta", "Khajuraho"], answer: 0, explain: "Pallava Mahabalipuram (Mamallapuram) ke rock-cut mandiron ke liye prasiddh hain." },
      { q: "The Rashtrakutas built the famous Kailasa temple at:", hi: "राष्ट्रकूटों ने प्रसिद्ध कैलाश मंदिर कहाँ बनवाया?", options: ["Ellora", "Ajanta", "Elephanta", "Badami"], answer: 0, explain: "Ellora ka Kailasa mandir (Cave 16) Rashtrakuta raja Krishna I ne banवाya." },
      { q: "The Chola dynasty reached its peak under:", hi: "चोल वंश अपने चरम पर किसके अधीन पहुँचा?", options: ["Rajaraja I & Rajendra I", "Karikala", "Kulottunga", "Vijayalaya"], answer: 0, explain: "Rajaraja I aur Rajendra I ke samay Chola samrajya charam par tha." },
      { q: "The Brihadeshwara Temple at Thanjavur was built by:", hi: "तंजावुर का बृहदेश्वर मंदिर किसने बनवाया?", options: ["Rajaraja I", "Rajendra I", "Krishnadeva Raya", "Pulakeshin II"], answer: 0, explain: "Rajaraja I (Chola) ne Brihadeshwara (Rajarajeshwara) mandir banवाya." },
    ],
  },
  {
    id: "medieval-sultanate",
    name: "Medieval India — Delhi Sultanate",
    questions: [
      { q: "Who founded the Slave Dynasty (Mamluk) of the Delhi Sultanate?", hi: "दिल्ली सल्तनत के गुलाम वंश की स्थापना किसने की?", options: ["Qutubuddin Aibak", "Iltutmish", "Balban", "Razia Sultan"], answer: 0, explain: "Qutubuddin Aibak ne 1206 me Slave (Mamluk) vansh sthapit kiya." },
      { q: "The Qutub Minar was started by Qutubuddin Aibak and completed by:", hi: "कुतुब मीनार कुतुबुद्दीन ऐबक ने शुरू की और किसने पूरी की?", options: ["Iltutmish", "Balban", "Alauddin Khilji", "Firoz Tughlaq"], answer: 0, explain: "Qutub Minar Aibak ne shuru ki, Iltutmish ne poori ki." },
      { q: "Who was the first woman ruler of the Delhi Sultanate?", hi: "दिल्ली सल्तनत की पहली महिला शासक कौन थी?", options: ["Razia Sultan", "Chand Bibi", "Nur Jahan", "Rani Durgavati"], answer: 0, explain: "Razia Sultan (Iltutmish ki beti) Delhi Sultanate ki pehli mahila shasak thi." },
      { q: "The Khilji dynasty was founded by:", hi: "खिलजी वंश की स्थापना किसने की?", options: ["Jalaluddin Khilji", "Alauddin Khilji", "Qutubuddin Aibak", "Balban"], answer: 0, explain: "Jalaluddin Khilji ne 1290 me Khilji vansh sthapit kiya." },
      { q: "Who introduced market/price control reforms?", hi: "बाजार/मूल्य नियंत्रण सुधार किसने लागू किए?", options: ["Alauddin Khilji", "Balban", "Firoz Tughlaq", "Iltutmish"], answer: 0, explain: "Alauddin Khilji ne market/price control (bazaar niyantran) lागू kiya." },
      { q: "Malik Kafur was the general of which Sultan?", hi: "मलिक काफूर किस सुल्तान का सेनापति था?", options: ["Alauddin Khilji", "Balban", "Muhammad Tughlaq", "Firoz Tughlaq"], answer: 0, explain: "Malik Kafur Alauddin Khilji ka senapati tha jisne South India jeeta." },
      { q: "Who transferred the capital from Delhi to Daulatabad?", hi: "राजधानी दिल्ली से दौलताबाद किसने स्थानांतरित की?", options: ["Muhammad bin Tughlaq", "Firoz Tughlaq", "Alauddin Khilji", "Balban"], answer: 0, explain: "Muhammad bin Tughlaq ne rajdhani Daulatabad le gaye (asafal prayog)." },
      { q: "Who introduced token currency in India?", hi: "भारत में सांकेतिक मुद्रा (token currency) किसने चलाई?", options: ["Muhammad bin Tughlaq", "Alauddin Khilji", "Firoz Tughlaq", "Sher Shah"], answer: 0, explain: "Muhammad bin Tughlaq ne token currency (tanbe/kaanse ke sikke) chalayi." },
      { q: "The Lodi dynasty was the last dynasty of the Delhi Sultanate. Its founder was:", hi: "लोदी वंश दिल्ली सल्तनत का अंतिम वंश था। इसका संस्थापक कौन था?", options: ["Bahlul Lodi", "Ibrahim Lodi", "Sikandar Lodi", "Daulat Khan"], answer: 0, explain: "Bahlul Lodi ne Lodi vansh sthapit kiya (1451)." },
      { q: "Who was the last ruler of the Delhi Sultanate, defeated by Babur?", hi: "दिल्ली सल्तनत का अंतिम शासक कौन था, जिसे बाबर ने हराया?", options: ["Ibrahim Lodi", "Sikandar Lodi", "Bahlul Lodi", "Daulat Khan"], answer: 0, explain: "Ibrahim Lodi ko Babur ne 1526 (Panipat) me haraya." },
      { q: "The 'Diwan-i-Kohi' (agriculture department) was set up by:", hi: "'दीवान-ए-कोही' (कृषि विभाग) किसने बनाया?", options: ["Muhammad bin Tughlaq", "Alauddin Khilji", "Firoz Tughlaq", "Balban"], answer: 0, explain: "Muhammad bin Tughlaq ne Diwan-i-Kohi (krishi vibhag) banवाya." },
      { q: "Firoz Shah Tughlaq is known for building:", hi: "फिरोज शाह तुगलक किसके निर्माण के लिए जाने जाते हैं?", options: ["Canals and cities", "Qutub Minar", "Taj Mahal", "Red Fort"], approxCheck: true, answer: 0, explain: "Firoz Tughlaq ne nahren (canals) aur sheher (Firozabad, Hisar) banवाye." },
      { q: "The theory of Kingship 'Divine Right' in the Sultanate was propounded by:", hi: "सल्तनत में राजत्व का 'दैवीय अधिकार' सिद्धांत किसने दिया?", options: ["Balban", "Iltutmish", "Alauddin Khilji", "Aibak"], answer: 0, explain: "Balban ne kingship ka 'divine right' (Zil-i-Ilahi) siddhant diya." },
      { q: "Amir Khusrau, the famous poet, lived during the:", hi: "प्रसिद्ध कवि अमीर खुसरो किस काल में थे?", options: ["Delhi Sultanate", "Gupta period", "Mauryan period", "Mughal peak"], answer: 0, explain: "Amir Khusrau Delhi Sultanate ke samay the; unhe 'Tota-e-Hind' kaha jaata hai." },
    ],
  },
  {
    id: "medieval-south",
    name: "Medieval India — Vijayanagar, Bahmani & Bhakti-Sufi",
    questions: [
      { q: "The Vijayanagar Empire was founded by Harihara and:", hi: "विजयनगर साम्राज्य की स्थापना हरिहर और किसने की?", options: ["Bukka", "Krishnadeva Raya", "Deva Raya", "Rama Raya"], answer: 0, explain: "Harihara aur Bukka (Sangama bandhu) ne 1336 me Vijayanagar sthapit kiya." },
      { q: "The greatest ruler of Vijayanagar was:", hi: "विजयनगर का सबसे महान शासक कौन था?", options: ["Krishnadeva Raya", "Harihara", "Bukka", "Rama Raya"], answer: 0, explain: "Krishnadeva Raya (Tuluva vansh) Vijayanagar ka sabse mahान shasak tha." },
      { q: "The Vijayanagar Empire was defeated in the Battle of Talikota (1565) by:", hi: "विजयनगर साम्राज्य तालीकोटा युद्ध (1565) में किससे हारा?", options: ["Deccan Sultanates alliance", "Mughals", "Marathas", "British"], answer: 0, explain: "Talikota (1565) me Deccan Sultanates ke sangh ne Vijayanagar ko haraya." },
      { q: "The Bahmani kingdom's most famous minister was:", hi: "बहमनी राज्य का सबसे प्रसिद्ध मंत्री कौन था?", options: ["Mahmud Gawan", "Malik Kafur", "Todar Mal", "Birbal"], answer: 0, explain: "Mahmud Gawan Bahmani rajya ka prasiddh mantri (Prime Minister) tha." },
      { q: "The founder of the Bhakti movement in the South was:", hi: "दक्षिण में भक्ति आंदोलन के प्रवर्तक कौन थे?", options: ["Ramanuja", "Kabir", "Nanak", "Chaitanya"], answer: 0, explain: "Ramanujacharya ne South me Bhakti/Vishishtadvaita ka prachar kiya." },
      { q: "Kabir was a disciple of:", hi: "कबीर किसके शिष्य थे?", options: ["Ramananda", "Ramanuja", "Nanak", "Chaitanya"], answer: 0, explain: "Kabir, Ramananda ke shishya mane jaate hain (nirgun bhakti)." },
      { q: "Guru Nanak was the founder of:", hi: "गुरु नानक किसके संस्थापक थे?", options: ["Sikhism", "Bhakti cult", "Sufism", "Jainism"], answer: 0, explain: "Guru Nanak Dev ji Sikh dharm ke sansthapak (pehle Guru) the." },
      { q: "Chaitanya Mahaprabhu spread the worship of:", hi: "चैतन्य महाप्रभु ने किसकी भक्ति फैलाई?", options: ["Krishna", "Shiva", "Rama", "Vishnu"], answer: 0, explain: "Chaitanya Mahaprabhu ne Krishna bhakti (Gaudiya Vaishnavism) faili." },
      { q: "The Sufi saint associated with Ajmer is:", hi: "अजमेर से जुड़े सूफी संत कौन हैं?", options: ["Moinuddin Chishti", "Nizamuddin Auliya", "Baba Farid", "Salim Chishti"], answer: 0, explain: "Khwaja Moinuddin Chishti ki dargah Ajmer me hai (Chishti silsila)." },
      { q: "Meerabai was a devotee of:", hi: "मीराबाई किसकी भक्त थीं?", options: ["Krishna", "Shiva", "Rama", "Durga"], answer: 0, explain: "Meerabai Krishna ki param bhakt thi (Rajasthan)." },
      { q: "The two main Sufi orders in India were Chishti and:", hi: "भारत में दो प्रमुख सूफी सिलसिले— चिश्ती और?", options: ["Suhrawardi", "Qadiri", "Naqshbandi", "Firdausi"], answer: 0, explain: "Chishti aur Suhrawardi do mukhya prarambhik Sufi silsile the." },
      { q: "Tulsidas, who wrote Ramcharitmanas, was a devotee of:", hi: "रामचरितमानस लिखने वाले तुलसीदास किसके भक्त थे?", options: ["Rama", "Krishna", "Shiva", "Vishnu"], answer: 0, explain: "Tulsidas Ram bhakt the; unhone Ramcharitmanas (Awadhi) likhi." },
    ],
  },
  {
    id: "medieval-mughal",
    name: "Medieval India — Mughals & Marathas",
    questions: [
      { q: "Who founded the Mughal Empire in India?", hi: "भारत में मुगल साम्राज्य की स्थापना किसने की?", options: ["Babur", "Humayun", "Akbar", "Aurangzeb"], answer: 0, explain: "Babur ne 1526 me Panipat ke pehle yudh ke baad Mughal samrajya sthapit kiya." },
      { q: "The First Battle of Panipat (1526) was between Babur and:", hi: "पानीपत का प्रथम युद्ध (1526) बाबर और किसके बीच हुआ?", options: ["Ibrahim Lodi", "Rana Sanga", "Hemu", "Sher Shah"], answer: 0, explain: "Babur ne Ibrahim Lodi ko Panipat (1526) me haraya." },
      { q: "Who defeated Humayun and established the Sur Empire?", hi: "हुमायूँ को हराकर सूर साम्राज्य किसने स्थापित किया?", options: ["Sher Shah Suri", "Babur", "Bairam Khan", "Hemu"], answer: 0, explain: "Sher Shah Suri ne Humayun ko Chausa (1539) aur Kannauj (1540) me haraya." },
      { q: "The Grand Trunk Road was built/renovated by:", hi: "ग्रैंड ट्रंक रोड किसने बनवाई/सुधारी?", options: ["Sher Shah Suri", "Akbar", "Ashoka", "Babur"], answer: 0, explain: "Sher Shah Suri ne GT Road (Sadak-e-Azam) ka nirmaan/renovation karवाya." },
      { q: "Akbar ascended the throne at the age of:", hi: "अकबर किस उम्र में गद्दी पर बैठा?", options: ["13", "18", "20", "15"], answer: 0, explain: "Akbar 13 saal ki umra me (1556) gaddi par baitha; Bairam Khan uska sanrakshak tha." },
      { q: "The Second Battle of Panipat (1556) was fought between Akbar's forces and:", hi: "पानीपत का दूसरा युद्ध (1556) अकबर की सेना और किसके बीच हुआ?", options: ["Hemu", "Ibrahim Lodi", "Rana Pratap", "Sher Shah"], answer: 0, explain: "Akbar (Bairam Khan) ne Hemu ko Panipat ke doosre yudh (1556) me haraya." },
      { q: "Akbar's religious policy was called:", hi: "अकबर की धार्मिक नीति क्या कहलाती थी?", options: ["Din-i-Ilahi / Sulh-i-Kul", "Jaziya", "Zabti", "Mansabdari"], answer: 0, explain: "Akbar ne Din-i-Ilahi (1582) chalayi aur Sulh-i-Kul (universal peace) apnaya." },
      { q: "The Battle of Haldighati (1576) was fought between Akbar and:", hi: "हल्दीघाटी का युद्ध (1576) अकबर और किसके बीच हुआ?", options: ["Rana Pratap", "Hemu", "Rana Sanga", "Shivaji"], answer: 0, explain: "Haldighati (1576) me Akbar (Man Singh) aur Maharana Pratap ke beech yudh hua." },
      { q: "Who built the Taj Mahal?", hi: "ताजमहल किसने बनवाया?", options: ["Shah Jahan", "Akbar", "Humayun", "Aurangzeb"], answer: 0, explain: "Shah Jahan ne apni patni Mumtaz Mahal ki yaad me Taj Mahal (Agra) banवाya." },
      { q: "Who built the Red Fort and Jama Masjid in Delhi?", hi: "दिल्ली में लाल किला और जामा मस्जिद किसने बनवाई?", options: ["Shah Jahan", "Akbar", "Aurangzeb", "Humayun"], answer: 0, explain: "Shah Jahan ne Red Fort aur Jama Masjid (Shahjahanabad) banवाye." },
      { q: "The last powerful Mughal emperor was:", hi: "अंतिम शक्तिशाली मुगल सम्राट कौन था?", options: ["Aurangzeb", "Shah Jahan", "Jahangir", "Bahadur Shah Zafar"], answer: 0, explain: "Aurangzeb antim shaktishali Mughal samrat tha; uske baad samrajya kamzor hua." },
      { q: "Who re-imposed Jaziya tax on non-Muslims?", hi: "गैर-मुस्लिमों पर जजिया कर किसने फिर से लगाया?", options: ["Aurangzeb", "Akbar", "Jahangir", "Shah Jahan"], answer: 0, explain: "Aurangzeb ne Jaziya (jo Akbar ne hataya tha) dobara lagaya." },
      { q: "The founder of the Maratha Empire was:", hi: "मराठा साम्राज्य के संस्थापक कौन थे?", options: ["Shivaji", "Baji Rao I", "Balaji Vishwanath", "Shahu"], answer: 0, explain: "Chhatrapati Shivaji Maharaj ne Maratha samrajya ki sthapna ki (1674 rajyabhishek)." },
      { q: "Shivaji's system of administration included a council of ministers called:", hi: "शिवाजी की प्रशासन व्यवस्था में मंत्रिपरिषद क्या कहलाती थी?", options: ["Ashtapradhan", "Mansabdari", "Diwan", "Sabha"], answer: 0, explain: "Shivaji ke 8 mantriyon ki parishad 'Ashtapradhan' kehlati thi." },
      { q: "The Third Battle of Panipat (1761) was fought between the Marathas and:", hi: "पानीपत का तीसरा युद्ध (1761) मराठों और किसके बीच हुआ?", options: ["Ahmad Shah Abdali", "Mughals", "British", "Nadir Shah"], answer: 0, explain: "Panipat ka teesra yudh (1761) Marathon aur Ahmad Shah Abdali ke beech hua; Marathe haare." },
      { q: "The Peshwas were the effective rulers of the Maratha confederacy with capital at:", hi: "पेशवा मराठा संघ के वास्तविक शासक थे, जिनकी राजधानी कहाँ थी?", options: ["Pune", "Satara", "Nagpur", "Indore"], answer: 0, explain: "Peshwaon ki rajdhani Pune thi (Shivaji ke uttaradhikari ke baad asli shakti Peshwa ke paas gayi)." },
    ],
  },
  {
    id: "modern-british",
    name: "Modern India — British Expansion & Governance",
    questions: [
      { q: "The Battle of Plassey (1757) was won by the British against:", hi: "प्लासी का युद्ध (1757) अंग्रेजों ने किसके विरुद्ध जीता?", options: ["Siraj-ud-Daulah", "Mir Jafar", "Tipu Sultan", "Mir Qasim"], answer: 0, explain: "Robert Clive ne Siraj-ud-Daulah (Bengal) ko Plassey (1757) me haraya — British rule ki neev." },
      { q: "The Battle of Buxar (1764) was won by the British against the combined forces of:", hi: "बक्सर का युद्ध (1764) अंग्रेजों ने किसकी संयुक्त सेना के विरुद्ध जीता?", options: ["Mir Qasim, Shuja-ud-Daulah, Shah Alam II", "Siraj-ud-Daulah", "Tipu Sultan", "Marathas"], answer: 0, explain: "Buxar (1764) me British ne Mir Qasim + Awadh Nawab + Mughal samrat ki sena ko haraya." },
      { q: "The 'Doctrine of Lapse' was introduced by:", hi: "'व्यपगत का सिद्धांत' (Doctrine of Lapse) किसने लागू किया?", options: ["Lord Dalhousie", "Lord Wellesley", "Lord Cornwallis", "Lord Curzon"], answer: 0, explain: "Lord Dalhousie ne Doctrine of Lapse lagाya (nishantaan raja ke rajya ka British me vilay)." },
      { q: "The Permanent Settlement (1793) in Bengal was introduced by:", hi: "बंगाल में स्थायी बंदोबस्त (1793) किसने लागू किया?", options: ["Lord Cornwallis", "Lord Dalhousie", "Warren Hastings", "Lord Ripon"], answer: 0, explain: "Lord Cornwallis ne Permanent Settlement (Zamindari system) Bengal me lागू kiya." },
      { q: "The first Governor-General of India was:", hi: "भारत का पहला गवर्नर-जनरल कौन था?", options: ["Warren Hastings", "Lord Cornwallis", "Lord William Bentinck", "Robert Clive"], answer: 0, explain: "Warren Hastings Bengal ke pehle Governor-General the (1774)." },
      { q: "Sati was abolished (1829) during the tenure of:", hi: "सती प्रथा (1829) किसके कार्यकाल में समाप्त हुई?", options: ["Lord William Bentinck", "Lord Dalhousie", "Lord Ripon", "Lord Curzon"], answer: 0, explain: "Lord William Bentinck ne Raja Ram Mohan Roy ke saath Sati (1829) khatam ki." },
      { q: "The capital of British India was shifted from Calcutta to Delhi in:", hi: "ब्रिटिश भारत की राजधानी कलकत्ता से दिल्ली कब स्थानांतरित हुई?", options: ["1911", "1905", "1919", "1935"], answer: 0, explain: "1911 me (George V ke Durbar me) rajdhani Calcutta se Delhi le gayi." },
      { q: "The Partition of Bengal (1905) was done by:", hi: "बंगाल विभाजन (1905) किसने किया?", options: ["Lord Curzon", "Lord Dalhousie", "Lord Ripon", "Lord Minto"], answer: 0, explain: "Lord Curzon ne 1905 me Bengal ka vibhajan kiya (jo Swadeshi Andolan ka kaaran bana)." },
      { q: "Who is called the 'Father of Local Self-Government' in India?", hi: "भारत में 'स्थानीय स्वशासन का जनक' किसे कहा जाता है?", options: ["Lord Ripon", "Lord Curzon", "Lord Mayo", "Lord Dalhousie"], answer: 0, explain: "Lord Ripon ko Local Self-Government ka janak kaha jaata hai (1882 resolution)." },
      { q: "The first railway line in India (1853) ran between:", hi: "भारत की पहली रेल लाइन (1853) कहाँ से कहाँ चली?", options: ["Bombay to Thane", "Delhi to Agra", "Calcutta to Delhi", "Madras to Bangalore"], answer: 0, explain: "Pehli railway Bombay-Thane (1853) me Lord Dalhousie ke samay chali." },
      { q: "The 'Subsidiary Alliance' system was introduced by:", hi: "'सहायक संधि' प्रणाली किसने लागू की?", options: ["Lord Wellesley", "Lord Dalhousie", "Lord Cornwallis", "Warren Hastings"], answer: 0, explain: "Lord Wellesley ne Subsidiary Alliance (sahayak sandhi) system lागू kiya." },
      { q: "Tipu Sultan was the ruler of:", hi: "टीपू सुल्तान किसका शासक था?", options: ["Mysore", "Hyderabad", "Bengal", "Awadh"], answer: 0, explain: "Tipu Sultan Mysore ka shasak tha; Fourth Anglo-Mysore War (1799) me shaheed hua." },
      { q: "The last Governor-General and first Viceroy of India was:", hi: "भारत का अंतिम गवर्नर-जनरल और पहला वायसराय कौन था?", options: ["Lord Canning", "Lord Curzon", "Lord Mountbatten", "Lord Ripon"], answer: 0, explain: "Lord Canning antim GG aur pehla Viceroy tha (1858, Crown rule shuru)." },
      { q: "The English East India Company was established in:", hi: "अंग्रेजी ईस्ट इंडिया कंपनी की स्थापना कब हुई?", options: ["1600", "1757", "1858", "1526"], answer: 0, explain: "English East India Company 1600 me (Queen Elizabeth I ke charter se) bani." },
      { q: "The first Viceroy after 1858 Crown Rule was Canning. British rule fully transferred to Crown by which Act?", hi: "1858 में शासन क्राउन को किस अधिनियम से स्थानांतरित हुआ?", options: ["Government of India Act 1858", "Regulating Act 1773", "Pitt's India Act 1784", "Charter Act 1833"], answer: 0, explain: "Government of India Act 1858 ke tehat shasan Company se British Crown ko gaya." },
    ],
  },
  {
    id: "modern-revolt-reform",
    name: "Modern India — Revolt of 1857 & Socio-Religious Reforms",
    questions: [
      { q: "The Revolt of 1857 began at:", hi: "1857 का विद्रोह कहाँ से शुरू हुआ?", options: ["Meerut", "Delhi", "Kanpur", "Jhansi"], answer: 0, explain: "1857 ka vidroh Meerut (10 May 1857) se shuru hua." },
      { q: "The immediate cause of the 1857 Revolt was:", hi: "1857 विद्रोह का तात्कालिक कारण क्या था?", options: ["Greased cartridges (Enfield rifle)", "Doctrine of Lapse", "High taxes", "Partition"], answer: 0, explain: "Enfield rifle ke greased cartridges (gaay/suar ki charbi) turant kaaran bane." },
      { q: "The leader of the 1857 Revolt at Kanpur was:", hi: "1857 विद्रोह में कानपुर का नेता कौन था?", options: ["Nana Saheb", "Tantia Tope", "Rani Lakshmibai", "Kunwar Singh"], answer: 0, explain: "Nana Saheb ne Kanpur me 1857 vidroh ka netrutva kiya." },
      { q: "Rani Lakshmibai led the revolt at:", hi: "रानी लक्ष्मीबाई ने किस स्थान पर विद्रोह का नेतृत्व किया?", options: ["Jhansi", "Kanpur", "Lucknow", "Delhi"], answer: 0, explain: "Rani Lakshmibai ne Jhansi me 1857 vidroh ka netrutva kiya." },
      { q: "During the 1857 Revolt, the rebels declared whom as the Emperor?", hi: "1857 विद्रोह में विद्रोहियों ने किसे सम्राट घोषित किया?", options: ["Bahadur Shah Zafar", "Nana Saheb", "Tantia Tope", "Kunwar Singh"], answer: 0, explain: "Vidrohiyon ne Bahadur Shah Zafar (antim Mughal) ko samrat ghoshit kiya." },
      { q: "Raja Ram Mohan Roy founded the:", hi: "राजा राम मोहन राय ने किसकी स्थापना की?", options: ["Brahmo Samaj", "Arya Samaj", "Ramakrishna Mission", "Prarthana Samaj"], answer: 0, explain: "Raja Ram Mohan Roy ne Brahmo Samaj (1828) sthapit kiya — 'Father of Indian Renaissance'." },
      { q: "The Arya Samaj was founded by:", hi: "आर्य समाज की स्थापना किसने की?", options: ["Swami Dayanand Saraswati", "Ram Mohan Roy", "Vivekananda", "Ranade"], answer: 0, explain: "Swami Dayanand Saraswati ne Arya Samaj (1875) sthapit kiya; 'Vedon ki or lauto'." },
      { q: "'Satyarth Prakash' was written by:", hi: "'सत्यार्थ प्रकाश' किसने लिखी?", options: ["Dayanand Saraswati", "Ram Mohan Roy", "Vivekananda", "Tilak"], answer: 0, explain: "Swami Dayanand Saraswati ne 'Satyarth Prakash' likhi." },
      { q: "The Ramakrishna Mission was founded by:", hi: "रामकृष्ण मिशन की स्थापना किसने की?", options: ["Swami Vivekananda", "Ramakrishna Paramhansa", "Dayanand", "Ranade"], answer: 0, explain: "Swami Vivekananda ne 1897 me Ramakrishna Mission sthapit kiya." },
      { q: "Swami Vivekananda delivered his famous speech (1893) at the World Parliament of Religions in:", hi: "स्वामी विवेकानंद ने अपना प्रसिद्ध भाषण (1893) कहाँ दिया?", options: ["Chicago", "London", "New York", "Paris"], answer: 0, explain: "Vivekananda ka Chicago (1893) me Parliament of Religions me prasiddh bhashan." },
      { q: "The Aligarh Movement was started by:", hi: "अलीगढ़ आंदोलन किसने शुरू किया?", options: ["Sir Syed Ahmed Khan", "Iqbal", "Jinnah", "Abul Kalam Azad"], answer: 0, explain: "Sir Syed Ahmed Khan ne Aligarh Movement (aur MAO College, jo AMU bana) shuru kiya." },
      { q: "Ishwar Chandra Vidyasagar is famous for promoting:", hi: "ईश्वर चंद्र विद्यासागर किसके लिए प्रसिद्ध हैं?", options: ["Widow remarriage", "Sati abolition", "Child labour ban", "Female infanticide law"], answer: 0, explain: "Vidyasagar ne Widow Remarriage Act (1856) ke liye kaam kiya." },
      { q: "Who was the first Indian to be elected to the British House of Commons?", hi: "ब्रिटिश हाउस ऑफ कॉमन्स में चुने जाने वाले पहले भारतीय कौन थे?", options: ["Dadabhai Naoroji", "Gandhi", "Gokhale", "Tilak"], answer: 0, explain: "Dadabhai Naoroji British House of Commons ke pehle Indian member the; 'Drain Theory' diya." },
      { q: "The Theosophical Society in India was led by:", hi: "भारत में थियोसोफिकल सोसाइटी का नेतृत्व किसने किया?", options: ["Annie Besant", "Blavatsky", "Olcott", "Ranade"], answer: 0, explain: "Annie Besant ne Theosophical Society (Adyar, Chennai) ka netrutva kiya." },
    ],
  },
  {
    id: "modern-freedom",
    name: "Modern India — Freedom Struggle & Gandhi Era",
    questions: [
      { q: "The Indian National Congress was founded in 1885 by:", hi: "भारतीय राष्ट्रीय कांग्रेस की स्थापना 1885 में किसने की?", options: ["A. O. Hume", "Gandhi", "Tilak", "Gokhale"], answer: 0, explain: "A. O. Hume ne INC (1885) ki sthapna ki; pehle adhyaksh W. C. Bonnerjee." },
      { q: "The first session of the INC (1885) was held in:", hi: "INC का पहला अधिवेशन (1885) कहाँ हुआ?", options: ["Bombay", "Calcutta", "Delhi", "Madras"], answer: 0, explain: "Pehla INC adhiveshan Bombay (1885) me W. C. Bonnerjee ki adhyakshता me hua." },
      { q: "'Swaraj is my birthright' was the slogan of:", hi: "'स्वराज मेरा जन्मसिद्ध अधिकार है' किसका नारा था?", options: ["Bal Gangadhar Tilak", "Gandhi", "Nehru", "Bose"], answer: 0, explain: "Bal Gangadhar Tilak ne kaha 'Swaraj is my birthright and I shall have it'." },
      { q: "The Jallianwala Bagh massacre took place in:", hi: "जलियांवाला बाग हत्याकांड कब हुआ?", options: ["1919", "1920", "1857", "1930"], answer: 0, explain: "Jallianwala Bagh (Amritsar) hatyakand 13 April 1919 ko General Dyer ne kiya." },
      { q: "The Non-Cooperation Movement was launched by Gandhi in:", hi: "असहयोग आंदोलन गांधी ने कब शुरू किया?", options: ["1920", "1930", "1942", "1919"], answer: 0, explain: "Non-Cooperation Movement 1920 me shuru hua (Chauri Chaura ke baad 1922 me wapas liya)." },
      { q: "The Dandi March (Salt Satyagraha) began in:", hi: "दांडी मार्च (नमक सत्याग्रह) कब शुरू हुआ?", options: ["1930", "1920", "1942", "1919"], answer: 0, explain: "Dandi March 12 March 1930 ko Sabarmati se shuru hua (Civil Disobedience)." },
      { q: "The 'Quit India Movement' was launched in:", hi: "'भारत छोड़ो आंदोलन' कब शुरू हुआ?", options: ["1942", "1930", "1920", "1857"], answer: 0, explain: "Quit India Movement 8 August 1942 ko shuru hua; nara 'Do or Die'." },
      { q: "Who founded the Indian National Army (Azad Hind Fauj)?", hi: "आजाद हिंद फौज (INA) की स्थापना किसने की?", options: ["Subhas Chandra Bose (revived it)", "Bhagat Singh", "Nehru", "Gandhi"], answer: 0, explain: "INA ki neev Rash Behari Bose/Mohan Singh ne daali, Subhas Chandra Bose ne netrutva kiya. Bose is most associated." },
      { q: "'Give me blood, I will give you freedom' was the slogan of:", hi: "'तुम मुझे खून दो, मैं तुम्हें आजादी दूंगा' किसका नारा था?", options: ["Subhas Chandra Bose", "Bhagat Singh", "Tilak", "Nehru"], answer: 0, explain: "Subhas Chandra Bose ne ye nara diya." },
      { q: "Bhagat Singh, Rajguru and Sukhdev were hanged in:", hi: "भगत सिंह, राजगुरु और सुखदेव को कब फांसी दी गई?", options: ["1931", "1929", "1930", "1935"], answer: 0, explain: "23 March 1931 ko Bhagat Singh, Rajguru, Sukhdev ko phansi di gayi (Lahore case)." },
      { q: "The Kakori Conspiracy (train robbery) took place in:", hi: "काकोरी कांड (ट्रेन डकैती) कब हुआ?", options: ["1925", "1919", "1930", "1942"], answer: 0, explain: "Kakori Kand 1925 me hua (Ram Prasad Bismil, Ashfaqullah Khan)." },
      { q: "The Rowlatt Act was passed in:", hi: "रौलट एक्ट कब पारित हुआ?", options: ["1919", "1920", "1909", "1935"], answer: 0, explain: "Rowlatt Act 1919 (bina mukadme girftari); iske virodh me Jallianwala hua." },
      { q: "Who gave the title 'Mahatma' to Gandhi?", hi: "गांधी को 'महात्मा' की उपाधि किसने दी?", options: ["Rabindranath Tagore", "Nehru", "Bose", "Tilak"], answer: 0, explain: "Rabindranath Tagore ne Gandhi ko 'Mahatma' kaha; Gandhi ne Tagore ko 'Gurudev'." },
      { q: "The Simon Commission (1928) was boycotted because:", hi: "साइमन कमीशन (1928) का बहिष्कार क्यों हुआ?", options: ["It had no Indian member", "It raised taxes", "It banned Congress", "It divided Bengal"], answer: 0, explain: "Simon Commission me koi Indian member nahi tha → 'Simon Go Back'." },
      { q: "India attained independence on:", hi: "भारत को स्वतंत्रता कब मिली?", options: ["15 August 1947", "26 January 1950", "15 August 1946", "26 January 1947"], answer: 0, explain: "Bharat 15 August 1947 ko swatantra hua (Mountbatten Plan / Indian Independence Act 1947)." },
      { q: "The first President of the Indian National Congress was:", hi: "भारतीय राष्ट्रीय कांग्रेस के पहले अध्यक्ष कौन थे?", options: ["W. C. Bonnerjee", "Dadabhai Naoroji", "A. O. Hume", "Gokhale"], answer: 0, explain: "W. C. Bonnerjee INC ke pehle adhyaksh the (1885, Bombay)." },
      { q: "Who is known as the 'Iron Man of India'?", hi: "'भारत का लौह पुरुष' किसे कहा जाता है?", options: ["Sardar Vallabhbhai Patel", "Nehru", "Bose", "Gandhi"], answer: 0, explain: "Sardar Vallabhbhai Patel ko 'Iron Man of India' kaha jaata hai (rajyon ka ekikaran)." },
      { q: "The partition of India in 1947 was based on the:", hi: "1947 में भारत का विभाजन किस आधार पर हुआ?", options: ["Mountbatten Plan", "Cabinet Mission", "Cripps Mission", "August Offer"], answer: 0, explain: "Mountbatten Plan (3 June 1947) ke aadhaar par vibhajan hua." },
    ],
  },
  {
    id: "world-history",
    name: "World History",
    questions: [
      { q: "The French Revolution began in:", hi: "फ्रांसीसी क्रांति कब शुरू हुई?", options: ["1789", "1776", "1804", "1815"], answer: 0, explain: "French Revolution 1789 me shuru hui (Bastille ka patan 14 July 1789)." },
      { q: "The slogan of the French Revolution was Liberty, Equality and:", hi: "फ्रांसीसी क्रांति का नारा— स्वतंत्रता, समानता और?", options: ["Fraternity", "Justice", "Democracy", "Unity"], answer: 0, explain: "Nara: Liberty, Equality, Fraternity (Swatantrata, Samanata, Bhaichara)." },
      { q: "The American Declaration of Independence was adopted in:", hi: "अमेरिकी स्वतंत्रता की घोषणा कब हुई?", options: ["1776", "1789", "1783", "1799"], answer: 0, explain: "US Declaration of Independence 4 July 1776 ko apnaya gaya." },
      { q: "The main author of the American Declaration of Independence was:", hi: "अमेरिकी स्वतंत्रता घोषणा के मुख्य लेखक कौन थे?", options: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "Benjamin Franklin"], answer: 0, explain: "Thomas Jefferson Declaration of Independence ke mukhya lekhak the." },
      { q: "The first President of the United States was:", hi: "संयुक्त राज्य अमेरिका के पहले राष्ट्रपति कौन थे?", options: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], answer: 0, explain: "George Washington USA ke pehle rashtrapati the." },
      { q: "The Russian Revolution (Bolshevik) took place in:", hi: "रूसी (बोल्शेविक) क्रांति कब हुई?", options: ["1917", "1905", "1789", "1848"], answer: 0, explain: "Bolshevik Revolution 1917 me hui, Lenin ke netrutva me." },
      { q: "The leader of the Bolshevik Revolution was:", hi: "बोल्शेविक क्रांति के नेता कौन थे?", options: ["Lenin", "Stalin", "Marx", "Trotsky"], answer: 0, explain: "Vladimir Lenin ne 1917 Bolshevik Kranti ka netrutva kiya." },
      { q: "'Das Kapital' and 'The Communist Manifesto' were written by:", hi: "'दास कैपिटल' और 'कम्युनिस्ट मेनिफेस्टो' किसने लिखी?", options: ["Karl Marx", "Lenin", "Stalin", "Engels alone"], answer: 0, explain: "Karl Marx (Engels ke saath) ne ye likhe — communism ke janak." },
      { q: "World War I began in:", hi: "प्रथम विश्व युद्ध कब शुरू हुआ?", options: ["1914", "1939", "1918", "1945"], answer: 0, explain: "World War I 1914-1918 tak chala (assassination of Archduke Ferdinand se shuru)." },
      { q: "World War II began in:", hi: "द्वितीय विश्व युद्ध कब शुरू हुआ?", options: ["1939", "1914", "1945", "1941"], answer: 0, explain: "World War II 1939 me shuru hua (Germany ne Poland par aakraman kiya)." },
      { q: "The atom bombs in WWII were dropped on Hiroshima and:", hi: "द्वितीय विश्व युद्ध में परमाणु बम हिरोशिमा और किस पर गिराए गए?", options: ["Nagasaki", "Tokyo", "Osaka", "Kyoto"], answer: 0, explain: "USA ne Hiroshima (6 Aug) aur Nagasaki (9 Aug 1945) par atom bomb giraye." },
      { q: "The League of Nations was formed after:", hi: "राष्ट्र संघ (League of Nations) किसके बाद बना?", options: ["World War I", "World War II", "French Revolution", "Cold War"], answer: 0, explain: "League of Nations WWI ke baad 1920 me bani (UN ka poorvroop)." },
      { q: "The United Nations was established in:", hi: "संयुक्त राष्ट्र (UN) की स्थापना कब हुई?", options: ["1945", "1920", "1919", "1950"], answer: 0, explain: "UN 24 October 1945 ko sthapit hua (WWII ke baad)." },
      { q: "The Renaissance began in which country?", hi: "पुनर्जागरण (Renaissance) किस देश में शुरू हुआ?", options: ["Italy", "France", "England", "Germany"], answer: 0, explain: "Renaissance Italy (Florence) se shuru hua (14th-16th century)." },
      { q: "'Mona Lisa' was painted by:", hi: "'मोना लिसा' किसने बनाई?", options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Picasso"], answer: 0, explain: "Leonardo da Vinci ne Mona Lisa banayi (Renaissance)." },
      { q: "The Industrial Revolution began in:", hi: "औद्योगिक क्रांति किस देश में शुरू हुई?", options: ["England", "France", "USA", "Germany"], answer: 0, explain: "Industrial Revolution England me 18th century me shuru hui." },
      { q: "The steam engine was improved by:", hi: "भाप के इंजन में सुधार किसने किया?", options: ["James Watt", "Newton", "Edison", "Faraday"], answer: 0, explain: "James Watt ne steam engine ko improve kiya (Industrial Revolution)." },
      { q: "Adolf Hitler was the dictator of:", hi: "एडोल्फ हिटलर किसका तानाशाह था?", options: ["Germany", "Italy", "Russia", "Japan"], answer: 0, explain: "Hitler Germany ka tanashah tha (Nazi Party); WWII ka mukhya kaaran." },
      { q: "Benito Mussolini was the fascist leader of:", hi: "बेनितो मुसोलिनी किस देश का फासीवादी नेता था?", options: ["Italy", "Germany", "Spain", "France"], answer: 0, explain: "Mussolini Italy ka fascist neta tha." },
      { q: "The Cold War was primarily between the USA and:", hi: "शीत युद्ध मुख्यतः अमेरिका और किसके बीच था?", options: ["USSR", "China", "Germany", "Japan"], answer: 0, explain: "Cold War USA aur USSR (Soviet Union) ke beech tha (1945-1991)." },
      { q: "The Chinese Revolution (1949) was led by:", hi: "चीनी क्रांति (1949) का नेतृत्व किसने किया?", options: ["Mao Zedong", "Sun Yat-sen", "Chiang Kai-shek", "Deng Xiaoping"], answer: 0, explain: "Mao Zedong ne 1949 Chinese Communist Revolution ka netrutva kiya." },
      { q: "The Magna Carta was signed in England in:", hi: "इंग्लैंड में मैग्ना कार्टा पर हस्ताक्षर कब हुए?", options: ["1215", "1066", "1492", "1776"], answer: 0, explain: "Magna Carta 1215 me King John ne sign ki (constitutional rights ki neev)." },
      { q: "Christopher Columbus discovered America in:", hi: "क्रिस्टोफर कोलंबस ने अमेरिका की खोज कब की?", options: ["1492", "1498", "1453", "1600"], answer: 0, explain: "Columbus ne 1492 me America ki khoj ki." },
      { q: "Vasco da Gama reached India (Calicut) in:", hi: "वास्को डी गामा भारत (कालीकट) कब पहुँचा?", options: ["1498", "1492", "1600", "1526"], answer: 0, explain: "Vasco da Gama 1498 me Calicut pahuncha (sea route to India)." },
      { q: "The Bastille, stormed in the French Revolution, was a:", hi: "फ्रांसीसी क्रांति में तोड़ा गया बास्तील क्या था?", options: ["Prison/fortress", "Palace", "Church", "Bank"], answer: 0, explain: "Bastille ek jail/kila tha; iska patan (1789) French Revolution ka prateek bana." },
      { q: "The Meiji Restoration modernized which country?", hi: "मेइजी पुनर्स्थापना ने किस देश का आधुनिकीकरण किया?", options: ["Japan", "China", "Korea", "Vietnam"], answer: 0, explain: "Meiji Restoration (1868) ne Japan ka aadhunikikaran kiya." },
      { q: "Abraham Lincoln is famous for abolishing:", hi: "अब्राहम लिंकन किसे समाप्त करने के लिए प्रसिद्ध हैं?", options: ["Slavery", "Monarchy", "Colonialism", "Feudalism"], answer: 0, explain: "Abraham Lincoln ne USA me slavery (daasta) khatam ki." },
      { q: "The American Civil War was fought between:", hi: "अमेरिकी गृह युद्ध किसके बीच लड़ा गया?", options: ["North and South (Union vs Confederacy)", "USA and Britain", "USA and Mexico", "USA and Spain"], answer: 0, explain: "American Civil War (1861-65) Uttar (Union) aur Dakshin (Confederacy) ke beech, slavery par." },
      { q: "The Berlin Wall, which divided Germany, fell in:", hi: "जर्मनी को बाँटने वाली बर्लिन की दीवार कब गिरी?", options: ["1989", "1961", "1991", "1945"], answer: 0, explain: "Berlin Wall 1989 me gira (Cold War ke ant ka prateek)." },
      { q: "The Soviet Union (USSR) dissolved in:", hi: "सोवियत संघ (USSR) कब विघटित हुआ?", options: ["1991", "1989", "1985", "1945"], answer: 0, explain: "USSR 1991 me vighatit hua; Cold War khatam." },
    ],
  },
];
