// SSC CGL — General Awareness: POLITY (100 questions)
// Bilingual (English + Hindi), CGL level. { q, hi, options[4], answer, explain }

export const polityMeta = {
  title: "Indian Polity — 100 Practice Questions",
  exam: "SSC CGL — General Awareness",
  total: 100,
  note: "SSC CGL level Polity questions (Constitution, Fundamental Rights, Parliament, President/PM, Judiciary, Constitutional Bodies). Bilingual English + हिंदी. Answers 'Show Answer Key' me.",
};

export const politySections = [
  {
    id: "constitution",
    name: "Constitution — Making & Features",
    questions: [
      { q: "The Constitution of India was adopted on:", hi: "भारत का संविधान कब अंगीकृत हुआ?", options: ["26 November 1949", "26 January 1950", "15 August 1947", "26 January 1949"], answer: 0, explain: "Samvidhan 26 November 1949 ko adopt hua; laागू 26 January 1950 ko." },
      { q: "The Constitution of India came into force on:", hi: "भारत का संविधान कब लागू हुआ?", options: ["26 January 1950", "26 November 1949", "15 August 1947", "26 January 1949"], answer: 0, explain: "26 January 1950 ko samvidhan laागू hua (Republic Day)." },
      { q: "Who was the Chairman of the Drafting Committee?", hi: "प्रारूप समिति के अध्यक्ष कौन थे?", options: ["Dr. B. R. Ambedkar", "Rajendra Prasad", "Nehru", "Sardar Patel"], answer: 0, explain: "Dr. B. R. Ambedkar Drafting Committee ke adhyaksh the ('Father of Indian Constitution')." },
      { q: "Who was the President of the Constituent Assembly?", hi: "संविधान सभा के अध्यक्ष कौन थे?", options: ["Dr. Rajendra Prasad", "Ambedkar", "Nehru", "Sachchidananda Sinha"], answer: 0, explain: "Dr. Rajendra Prasad Constituent Assembly ke sthayi adhyaksh the." },
      { q: "How long did it take to frame the Constitution?", hi: "संविधान बनाने में कितना समय लगा?", options: ["2 years 11 months 18 days", "3 years", "1 year", "5 years"], answer: 0, explain: "Samvidhan banane me 2 saal 11 mahine 18 din lage." },
      { q: "The idea of a Constituent Assembly was first given by:", hi: "संविधान सभा का विचार सर्वप्रथम किसने दिया?", options: ["M. N. Roy", "Nehru", "Gandhi", "Ambedkar"], answer: 0, explain: "M. N. Roy ne 1934 me Constituent Assembly ka vichar diya." },
      { q: "The Preamble was amended by which amendment (adding Socialist, Secular)?", hi: "प्रस्तावना में 'समाजवादी, धर्मनिरपेक्ष' शब्द किस संशोधन से जुड़े?", options: ["42nd Amendment (1976)", "44th Amendment", "1st Amendment", "73rd Amendment"], answer: 0, explain: "42nd Amendment (1976) ne Socialist, Secular, Integrity shabd jode." },
      { q: "The Indian Constitution is:", hi: "भारतीय संविधान कैसा है?", options: ["Partly rigid, partly flexible", "Fully rigid", "Fully flexible", "Unwritten"], answer: 0, explain: "Bharatiya samvidhan aংshik roop se rigid aur flexible dono hai." },
      { q: "The Preamble describes India as a Sovereign, Socialist, Secular, Democratic:", hi: "प्रस्तावना भारत को संप्रभु, समाजवादी, धर्मनिरपेक्ष, लोकतांत्रिक क्या बताती है?", options: ["Republic", "Monarchy", "Union", "Federation"], answer: 0, explain: "Preamble India ko 'Republic' (ganrajya) batati hai." },
      { q: "The Fundamental Duties were added by the:", hi: "मौलिक कर्तव्य किस संशोधन से जोड़े गए?", options: ["42nd Amendment", "44th Amendment", "1st Amendment", "73rd Amendment"], answer: 0, explain: "Fundamental Duties (Part IVA) 42nd Amendment (1976) se jode gaye (Swaran Singh Committee)." },
      { q: "The Constitution of India originally had how many Articles?", hi: "भारत के संविधान में मूलतः कितने अनुच्छेद थे?", options: ["395", "448", "300", "500"], answer: 0, explain: "Mool samvidhan me 395 Articles, 22 Parts, 8 Schedules the." },
      { q: "How many Schedules does the Constitution have now?", hi: "अब संविधान में कितनी अनुसूचियाँ हैं?", options: ["12", "8", "10", "22"], answer: 0, explain: "Vartaman me 12 Schedules (anusuchiyan) hain." },
      { q: "The concept of 'Directive Principles' was borrowed from:", hi: "'नीति-निदेशक तत्वों' की अवधारणा कहाँ से ली गई?", options: ["Ireland", "USA", "UK", "Canada"], answer: 0, explain: "DPSP Ireland ke samvidhan se liye gaye." },
      { q: "The 'Fundamental Rights' were borrowed from the Constitution of:", hi: "'मौलिक अधिकार' किस देश के संविधान से लिए गए?", options: ["USA", "UK", "Ireland", "Canada"], answer: 0, explain: "Fundamental Rights USA ke samvidhan (Bill of Rights) se liye gaye." },
      { q: "The parliamentary form of government was borrowed from:", hi: "संसदीय शासन प्रणाली कहाँ से ली गई?", options: ["UK (Britain)", "USA", "France", "Canada"], answer: 0, explain: "Parliamentary system Britain (UK) se liya gaya." },
      { q: "The federal system with a strong centre was borrowed from:", hi: "मजबूत केंद्र वाली संघीय व्यवस्था कहाँ से ली गई?", options: ["Canada", "USA", "UK", "Australia"], answer: 0, explain: "Strong-centre federal system Canada se liya gaya." },
      { q: "The 'Concurrent List' idea was borrowed from:", hi: "'समवर्ती सूची' का विचार कहाँ से लिया गया?", options: ["Australia", "Canada", "USA", "Ireland"], answer: 0, explain: "Concurrent List Australia se li gayi." },
      { q: "The Preamble begins with the words:", hi: "प्रस्तावना किन शब्दों से शुरू होती है?", options: ["We, the People of India", "India, that is Bharat", "The Union of India", "In the name of God"], answer: 0, explain: "Preamble 'We, the People of India' se shuru hoti hai." },
      { q: "The Preamble is based on the 'Objectives Resolution' moved by:", hi: "प्रस्तावना किस 'उद्देश्य प्रस्ताव' पर आधारित है जो किसने रखा?", options: ["Jawaharlal Nehru", "Ambedkar", "Rajendra Prasad", "Patel"], answer: 0, explain: "Nehru ne Objectives Resolution (1946) rakha jo Preamble ka aadhaar bana." },
      { q: "Which part of the Constitution is called its 'soul' (Dr. Ambedkar)?", hi: "संविधान के किस भाग को इसकी 'आत्मा' कहा गया?", options: ["Right to Constitutional Remedies (Art 32)", "Preamble", "DPSP", "Fundamental Duties"], answer: 0, explain: "Ambedkar ne Article 32 (Right to Constitutional Remedies) ko 'heart and soul' kaha." },
    ],
  },
  {
    id: "rights",
    name: "Fundamental Rights, Duties & DPSP",
    questions: [
      { q: "Fundamental Rights are contained in which Part of the Constitution?", hi: "मौलिक अधिकार संविधान के किस भाग में हैं?", options: ["Part III", "Part II", "Part IV", "Part I"], answer: 0, explain: "Fundamental Rights Part III (Articles 12-35) me hain." },
      { q: "How many Fundamental Rights are there currently?", hi: "वर्तमान में कितने मौलिक अधिकार हैं?", options: ["Six", "Seven", "Five", "Eight"], answer: 0, explain: "Ab 6 Fundamental Rights hain (Right to Property hataya gaya)." },
      { q: "Right to Equality is covered under Articles:", hi: "समानता का अधिकार किन अनुच्छेदों में है?", options: ["14-18", "19-22", "23-24", "25-28"], answer: 0, explain: "Right to Equality Articles 14-18 me hai." },
      { q: "Right to Freedom is covered under Articles:", hi: "स्वतंत्रता का अधिकार किन अनुच्छेदों में है?", options: ["19-22", "14-18", "23-24", "25-28"], answer: 0, explain: "Right to Freedom Articles 19-22 me hai." },
      { q: "Which Article abolishes untouchability?", hi: "कौन-सा अनुच्छेद अस्पृश्यता समाप्त करता है?", options: ["Article 17", "Article 14", "Article 21", "Article 19"], answer: 0, explain: "Article 17 achhutta (untouchability) ko samapt karta hai." },
      { q: "Right to Education (Article 21A) was added by which amendment?", hi: "शिक्षा का अधिकार (अनुच्छेद 21A) किस संशोधन से जुड़ा?", options: ["86th Amendment", "42nd Amendment", "44th Amendment", "73rd Amendment"], answer: 0, explain: "Right to Education (Art 21A) 86th Amendment (2002) se juda (6-14 varsh)." },
      { q: "Article 21 guarantees:", hi: "अनुच्छेद 21 क्या सुनिश्चित करता है?", options: ["Right to Life and Personal Liberty", "Right to Equality", "Right to Education", "Right to Vote"], answer: 0, explain: "Article 21 Right to Life aur Personal Liberty deta hai." },
      { q: "Which Fundamental Right was deleted by the 44th Amendment?", hi: "44वें संशोधन द्वारा कौन-सा मौलिक अधिकार हटाया गया?", options: ["Right to Property", "Right to Equality", "Right to Freedom", "Right to Religion"], answer: 0, explain: "Right to Property 44th Amendment (1978) se Fundamental Right se hataya gaya (ab legal right, Art 300A)." },
      { q: "The Directive Principles of State Policy are in which Part?", hi: "राज्य के नीति-निदेशक तत्व किस भाग में हैं?", options: ["Part IV", "Part III", "Part II", "Part V"], answer: 0, explain: "DPSP Part IV (Articles 36-51) me hain." },
      { q: "The Directive Principles are:", hi: "नीति-निदेशक तत्व कैसे हैं?", options: ["Non-justiciable", "Justiciable", "Fundamental", "Enforceable in court"], answer: 0, explain: "DPSP non-justiciable hain (court me laागू nahi kiye ja sakte)." },
      { q: "How many Fundamental Duties are there now?", hi: "अब कितने मौलिक कर्तव्य हैं?", options: ["Eleven", "Ten", "Twelve", "Nine"], answer: 0, explain: "Ab 11 Fundamental Duties hain (11va 86th Amendment se juda)." },
      { q: "Which writ is issued to produce a detained person before court?", hi: "किसी हिरासत में लिए व्यक्ति को न्यायालय में पेश करने हेतु कौन-सा रिट जारी होता है?", options: ["Habeas Corpus", "Mandamus", "Quo Warranto", "Certiorari"], answer: 0, explain: "Habeas Corpus ('you may have the body') detained vyakti ko court me pesh karne hetu." },
      { q: "The writ 'Mandamus' means:", hi: "रिट 'परमादेश' (Mandamus) का अर्थ है?", options: ["We command", "You may have the body", "By what authority", "To be certified"], answer: 0, explain: "Mandamus ('we command') public official ko duty nibhane ka aadesh." },
      { q: "The writ issued against usurpation of a public office is:", hi: "किसी सार्वजनिक पद के अवैध कब्ज़े के विरुद्ध कौन-सा रिट है?", options: ["Quo Warranto", "Habeas Corpus", "Mandamus", "Prohibition"], answer: 0, explain: "Quo Warranto ('by what authority') galat tarike se pad par baithe vyakti ke khilaf." },
      { q: "The concept of a Welfare State is enshrined in:", hi: "कल्याणकारी राज्य की अवधारणा किसमें निहित है?", options: ["Directive Principles", "Fundamental Rights", "Preamble only", "Fundamental Duties"], answer: 0, explain: "Welfare State ki avdharna DPSP me nihit hai." },
    ],
  },
  {
    id: "parliament",
    name: "Parliament, President & PM",
    questions: [
      { q: "The Indian Parliament consists of the President, Lok Sabha and:", hi: "भारतीय संसद में राष्ट्रपति, लोकसभा और क्या शामिल है?", options: ["Rajya Sabha", "Supreme Court", "Council of Ministers", "Governor"], answer: 0, explain: "Parliament = President + Lok Sabha + Rajya Sabha." },
      { q: "The maximum strength of the Lok Sabha is:", hi: "लोकसभा की अधिकतम सदस्य संख्या कितनी है?", options: ["552", "545", "250", "500"], answer: 0, explain: "Lok Sabha ki adhikatam sankhya 552 hai (Constitution ke anusar)." },
      { q: "The maximum strength of the Rajya Sabha is:", hi: "राज्यसभा की अधिकतम सदस्य संख्या कितनी है?", options: ["250", "245", "552", "300"], answer: 0, explain: "Rajya Sabha ki adhikatam sankhya 250 hai (238 elected + 12 nominated)." },
      { q: "The tenure of a Rajya Sabha member is:", hi: "राज्यसभा सदस्य का कार्यकाल कितना है?", options: ["6 years", "5 years", "4 years", "2 years"], answer: 0, explain: "Rajya Sabha member ka karyakaal 6 saal (1/3 har 2 saal me retire)." },
      { q: "Money Bills can be introduced only in:", hi: "धन विधेयक केवल कहाँ प्रस्तुत हो सकते हैं?", options: ["Lok Sabha", "Rajya Sabha", "Either House", "President's office"], answer: 0, explain: "Money Bill sirf Lok Sabha me introduce ho sakta hai (Art 110)." },
      { q: "The minimum age to become a member of the Lok Sabha is:", hi: "लोकसभा सदस्य बनने की न्यूनतम आयु कितनी है?", options: ["25 years", "30 years", "35 years", "21 years"], answer: 0, explain: "Lok Sabha member ke liye nyunatam aayu 25 saal." },
      { q: "The minimum age to become a member of the Rajya Sabha is:", hi: "राज्यसभा सदस्य बनने की न्यूनतम आयु कितनी है?", options: ["30 years", "25 years", "35 years", "21 years"], answer: 0, explain: "Rajya Sabha member ke liye nyunatam aayu 30 saal." },
      { q: "The President of India is elected by:", hi: "भारत के राष्ट्रपति का चुनाव कौन करता है?", options: ["Electoral College", "Lok Sabha only", "People directly", "Prime Minister"], answer: 0, explain: "President ka chunav Electoral College (elected MPs + MLAs) karta hai." },
      { q: "The minimum age to become the President of India is:", hi: "राष्ट्रपति बनने की न्यूनतम आयु कितनी है?", options: ["35 years", "30 years", "40 years", "25 years"], answer: 0, explain: "President ke liye nyunatam aayu 35 saal." },
      { q: "The term of office of the President is:", hi: "राष्ट्रपति का कार्यकाल कितना है?", options: ["5 years", "6 years", "4 years", "7 years"], answer: 0, explain: "President ka karyakaal 5 saal hota hai." },
      { q: "Who appoints the Prime Minister of India?", hi: "भारत के प्रधानमंत्री को कौन नियुक्त करता है?", options: ["President", "Lok Sabha Speaker", "Chief Justice", "Vice President"], answer: 0, explain: "President Prime Minister ko niyukt karta hai (majority party leader)." },
      { q: "The Vice President of India is the ex-officio Chairman of:", hi: "भारत का उपराष्ट्रपति किसका पदेन सभापति होता है?", options: ["Rajya Sabha", "Lok Sabha", "Supreme Court", "Planning Commission"], answer: 0, explain: "Vice President Rajya Sabha ka ex-officio Chairman hota hai." },
      { q: "The Speaker of the Lok Sabha is elected by:", hi: "लोकसभा अध्यक्ष का चुनाव कौन करता है?", options: ["Members of Lok Sabha", "President", "PM", "People"], answer: 0, explain: "Lok Sabha Speaker ka chunav Lok Sabha ke members karte hain." },
      { q: "A financial emergency is declared under which Article?", hi: "वित्तीय आपातकाल किस अनुच्छेद के तहत घोषित होता है?", options: ["Article 360", "Article 352", "Article 356", "Article 370"], answer: 0, explain: "Financial Emergency Article 360 ke tehat." },
      { q: "The National Emergency is declared under Article:", hi: "राष्ट्रीय आपातकाल किस अनुच्छेद के तहत घोषित होता है?", options: ["352", "356", "360", "365"], answer: 0, explain: "National Emergency Article 352 ke tehat." },
      { q: "President's Rule (State Emergency) is imposed under Article:", hi: "राष्ट्रपति शासन (राज्य आपातकाल) किस अनुच्छेद के तहत लगता है?", options: ["356", "352", "360", "370"], answer: 0, explain: "President's Rule Article 356 ke tehat lagta hai." },
      { q: "The Council of Ministers is collectively responsible to:", hi: "मंत्रिपरिषद सामूहिक रूप से किसके प्रति उत्तरदायी है?", options: ["Lok Sabha", "Rajya Sabha", "President", "Supreme Court"], answer: 0, explain: "Council of Ministers samuhik roop se Lok Sabha ke prati uttardayi hai." },
      { q: "The quorum for a House of Parliament is:", hi: "संसद के किसी सदन का कोरम कितना होता है?", options: ["1/10th of total members", "1/4th", "1/2", "1/3rd"], answer: 0, explain: "Quorum kul sadasyon ka 1/10 hota hai." },
      { q: "Who administers the oath of office to the President?", hi: "राष्ट्रपति को पद की शपथ कौन दिलाता है?", options: ["Chief Justice of India", "Vice President", "PM", "Speaker"], answer: 0, explain: "Chief Justice of India President ko shapath dilata hai." },
      { q: "The 'Zero Hour' in Parliament refers to:", hi: "संसद में 'शून्य काल' किसे कहते हैं?", options: ["Time immediately after Question Hour", "First hour of session", "Last hour", "Lunch break"], answer: 0, explain: "Zero Hour Question Hour ke turant baad ka samay hota hai (12 baje)." },
    ],
  },
  {
    id: "judiciary",
    name: "Judiciary & Constitutional Bodies",
    questions: [
      { q: "The Supreme Court of India was established in:", hi: "भारत का सर्वोच्च न्यायालय कब स्थापित हुआ?", options: ["1950", "1947", "1935", "1949"], answer: 0, explain: "Supreme Court 28 January 1950 ko sthapit hua." },
      { q: "The Chief Justice of India is appointed by:", hi: "भारत के मुख्य न्यायाधीश को कौन नियुक्त करता है?", options: ["President", "PM", "Parliament", "Law Minister"], answer: 0, explain: "CJI ko President niyukt karta hai." },
      { q: "The retirement age of a Supreme Court judge is:", hi: "सर्वोच्च न्यायालय के न्यायाधीश की सेवानिवृत्ति आयु कितनी है?", options: ["65 years", "62 years", "60 years", "70 years"], answer: 0, explain: "Supreme Court judge 65 saal ki umra me retire hote hain." },
      { q: "The retirement age of a High Court judge is:", hi: "उच्च न्यायालय के न्यायाधीश की सेवानिवृत्ति आयु कितनी है?", options: ["62 years", "65 years", "60 years", "58 years"], answer: 0, explain: "High Court judge 62 saal ki umra me retire hote hain." },
      { q: "The power of Judicial Review is exercised by:", hi: "न्यायिक पुनरावलोकन की शक्ति किसके पास है?", options: ["Supreme Court & High Courts", "President", "Parliament", "PM"], answer: 0, explain: "Judicial Review Supreme Court aur High Courts karte hain." },
      { q: "Who is the guardian of the Fundamental Rights?", hi: "मौलिक अधिकारों का संरक्षक कौन है?", options: ["Supreme Court", "President", "Parliament", "PM"], answer: 0, explain: "Supreme Court Fundamental Rights ka sanrakshak hai (Art 32)." },
      { q: "The Comptroller and Auditor General (CAG) is appointed by:", hi: "नियंत्रक एवं महालेखा परीक्षक (CAG) को कौन नियुक्त करता है?", options: ["President", "PM", "Parliament", "Finance Minister"], answer: 0, explain: "CAG ko President niyukt karta hai (Art 148)." },
      { q: "The CAG is often called the:", hi: "CAG को अक्सर क्या कहा जाता है?", options: ["Guardian of public purse", "Guardian of rights", "Head of judiciary", "Chief accountant"], answer: 0, explain: "CAG ko 'Guardian of the Public Purse' kaha jaata hai." },
      { q: "The Election Commission of India is a:", hi: "भारत निर्वाचन आयोग कैसा है?", options: ["Constitutional body", "Statutory body", "Executive body", "Advisory body"], answer: 0, explain: "Election Commission ek Constitutional body hai (Art 324)." },
      { q: "The Attorney General of India is the:", hi: "भारत का महान्यायवादी क्या है?", options: ["Chief legal advisor to Govt", "Head of judiciary", "Chief prosecutor", "Law minister"], answer: 0, explain: "Attorney General sarkaar ka mukhya kaanooni salahkaar hai (Art 76)." },
      { q: "The UPSC (Union Public Service Commission) is a:", hi: "संघ लोक सेवा आयोग (UPSC) कैसा है?", options: ["Constitutional body", "Statutory body", "Advisory body", "Executive body"], answer: 0, explain: "UPSC Constitutional body hai (Art 315)." },
      { q: "The first woman judge of the Supreme Court was:", hi: "सर्वोच्च न्यायालय की पहली महिला न्यायाधीश कौन थीं?", options: ["Fatima Beevi", "Leila Seth", "Ruma Pal", "Indira Jaising"], answer: 0, explain: "Justice Fatima Beevi Supreme Court ki pehli mahila judge thi (1989)." },
      { q: "The Finance Commission is constituted every:", hi: "वित्त आयोग का गठन कितने वर्षों में होता है?", options: ["5 years", "6 years", "4 years", "3 years"], answer: 0, explain: "Finance Commission har 5 saal me banti hai (Art 280)." },
      { q: "The doctrine of 'Basic Structure' was propounded in which case?", hi: "'आधारभूत ढाँचा' सिद्धांत किस मामले में दिया गया?", options: ["Kesavananda Bharati case", "Golaknath case", "Minerva Mills case", "Maneka Gandhi case"], answer: 0, explain: "Basic Structure doctrine Kesavananda Bharati case (1973) me diya gaya." },
      { q: "Public Interest Litigation (PIL) was introduced in India by:", hi: "जनहित याचिका (PIL) की शुरुआत किसने की?", options: ["Justice P. N. Bhagwati", "Justice Fatima Beevi", "Nani Palkhivala", "Ambedkar"], answer: 0, explain: "PIL ka concept Justice P. N. Bhagwati (aur Justice Krishna Iyer) ne diya." },
    ],
  },
  {
    id: "misc",
    name: "Amendments, States & Miscellaneous",
    questions: [
      { q: "The procedure for amending the Constitution is given in Article:", hi: "संविधान संशोधन की प्रक्रिया किस अनुच्छेद में है?", options: ["368", "356", "352", "370"], answer: 0, explain: "Amendment procedure Article 368 me hai." },
      { q: "The 73rd Amendment (1992) is related to:", hi: "73वाँ संशोधन (1992) किससे संबंधित है?", options: ["Panchayati Raj", "Municipalities", "GST", "Education"], answer: 0, explain: "73rd Amendment Panchayati Raj (rural local govt) se sambandhit hai." },
      { q: "The 74th Amendment (1992) is related to:", hi: "74वाँ संशोधन (1992) किससे संबंधित है?", options: ["Municipalities (urban)", "Panchayats", "GST", "Anti-defection"], answer: 0, explain: "74th Amendment Municipalities (urban local govt) se sambandhit hai." },
      { q: "The 'Anti-Defection Law' is contained in which Schedule?", hi: "'दल-बदल विरोधी कानून' किस अनुसूची में है?", options: ["Tenth Schedule", "Ninth Schedule", "Eighth Schedule", "Seventh Schedule"], answer: 0, explain: "Anti-Defection Law 10th Schedule me hai (52nd Amendment, 1985)." },
      { q: "The Eighth Schedule of the Constitution deals with:", hi: "संविधान की आठवीं अनुसूची किससे संबंधित है?", options: ["Languages", "Anti-defection", "States and UTs", "Panchayats"], answer: 0, explain: "8th Schedule me recognised languages (22) hain." },
      { q: "How many languages are recognised in the Eighth Schedule?", hi: "आठवीं अनुसूची में कितनी भाषाएँ मान्यता प्राप्त हैं?", options: ["22", "18", "24", "20"], answer: 0, explain: "8th Schedule me 22 bhashaon ko manyata hai." },
      { q: "The GST (Goods and Services Tax) was introduced by which amendment?", hi: "GST किस संशोधन द्वारा लागू हुआ?", options: ["101st Amendment", "42nd Amendment", "44th Amendment", "73rd Amendment"], answer: 0, explain: "GST 101st Constitutional Amendment (2016/2017) se laागू hua." },
      { q: "The Seventh Schedule deals with the division of powers through:", hi: "सातवीं अनुसूची शक्तियों के विभाजन को किसके माध्यम से करती है?", options: ["Union, State, Concurrent Lists", "Languages", "Anti-defection", "Emergency"], answer: 0, explain: "7th Schedule me Union List, State List, Concurrent List hain." },
      { q: "Which article deals with the abolition of untouchability... (Right against exploitation is in):", hi: "शोषण के विरुद्ध अधिकार किन अनुच्छेदों में है?", options: ["Articles 23-24", "Articles 14-18", "Articles 19-22", "Articles 25-28"], answer: 0, explain: "Right against Exploitation Articles 23-24 me hai (forced labour, child labour ban)." },
      { q: "The Right to Freedom of Religion is covered under Articles:", hi: "धार्मिक स्वतंत्रता का अधिकार किन अनुच्छेदों में है?", options: ["25-28", "23-24", "29-30", "19-22"], answer: 0, explain: "Right to Freedom of Religion Articles 25-28 me hai." },
      { q: "Cultural and Educational Rights are given in Articles:", hi: "सांस्कृतिक एवं शैक्षिक अधिकार किन अनुच्छेदों में हैं?", options: ["29-30", "25-28", "23-24", "14-18"], answer: 0, explain: "Cultural and Educational Rights Articles 29-30 me hain (minorities)." },
      { q: "The 'Right to Vote' in India is a:", hi: "भारत में 'मतदान का अधिकार' कैसा है?", options: ["Constitutional/legal right", "Fundamental Right", "Natural right", "Directive Principle"], answer: 0, explain: "Right to Vote ek constitutional/legal right hai (Art 326), Fundamental Right nahi." },
      { q: "Article 370 (special status), now abrogated, was related to:", hi: "अनुच्छेद 370 (विशेष दर्जा), अब निरस्त, किससे संबंधित था?", options: ["Jammu & Kashmir", "Nagaland", "Sikkim", "Assam"], answer: 0, explain: "Article 370 Jammu & Kashmir ko special status deta tha (2019 me abrogate)." },
      { q: "The minimum voting age was reduced from 21 to 18 by which amendment?", hi: "मतदान की आयु 21 से 18 किस संशोधन द्वारा हुई?", options: ["61st Amendment", "42nd Amendment", "44th Amendment", "52nd Amendment"], answer: 0, explain: "Voting age 21→18, 61st Amendment (1988) se hua." },
      { q: "The 'Rule of Law' concept in the Indian Constitution is borrowed from:", hi: "भारतीय संविधान में 'विधि का शासन' कहाँ से लिया गया?", options: ["UK (Britain)", "USA", "France", "Canada"], answer: 0, explain: "Rule of Law UK se liya gaya (A. V. Dicey)." },
      { q: "How many types of emergencies are provided in the Constitution?", hi: "संविधान में कितने प्रकार के आपातकाल हैं?", options: ["Three", "Two", "Four", "One"], answer: 0, explain: "Teen prakaar: National (352), State/President's Rule (356), Financial (360)." },
      { q: "The Governor of a State is appointed by:", hi: "किसी राज्य के राज्यपाल को कौन नियुक्त करता है?", options: ["President", "PM", "Chief Minister", "Chief Justice"], answer: 0, explain: "Governor ko President niyukt karta hai (Art 155)." },
      { q: "The Chief Minister of a State is appointed by:", hi: "किसी राज्य के मुख्यमंत्री को कौन नियुक्त करता है?", options: ["Governor", "President", "PM", "Speaker"], answer: 0, explain: "Chief Minister ko Governor niyukt karta hai (majority party)." },
      { q: "The maximum gap between two Parliament sessions cannot exceed:", hi: "संसद के दो सत्रों के बीच अधिकतम अंतराल कितना हो सकता है?", options: ["6 months", "3 months", "1 year", "9 months"], answer: 0, explain: "Do sessions ke beech 6 mahine se zyada gap nahi ho sakta." },
      { q: "The Panchayati Raj system was first introduced in India in:", hi: "पंचायती राज व्यवस्था भारत में पहली बार कहाँ शुरू हुई?", options: ["Rajasthan (Nagaur, 1959)", "Gujarat", "Maharashtra", "UP"], answer: 0, explain: "Panchayati Raj pehli baar Rajasthan (Nagaur, 2 Oct 1959) me shuru hua." },
      { q: "The National Human Rights Commission (NHRC) is a:", hi: "राष्ट्रीय मानवाधिकार आयोग (NHRC) कैसा है?", options: ["Statutory body", "Constitutional body", "Executive body", "Advisory body"], answer: 0, explain: "NHRC ek statutory body hai (Protection of Human Rights Act 1993)." },
      { q: "The three-tier Panchayati Raj structure includes Gram Panchayat, Panchayat Samiti and:", hi: "त्रि-स्तरीय पंचायती राज में ग्राम पंचायत, पंचायत समिति और?", options: ["Zila Parishad", "Municipality", "Nagar Nigam", "Gram Sabha"], answer: 0, explain: "Teen star: Gram Panchayat (village), Panchayat Samiti (block), Zila Parishad (district)." },
      { q: "The concept of single citizenship in India is borrowed from:", hi: "भारत में इकहरी नागरिकता की अवधारणा कहाँ से ली गई?", options: ["UK (Britain)", "USA", "Canada", "Australia"], answer: 0, explain: "Single citizenship UK se li gayi (USA me dual citizenship hai)." },
      { q: "Who has the power to declare war or conclude peace (constitutionally)?", hi: "संवैधानिक रूप से युद्ध घोषित करने या शांति स्थापित करने की शक्ति किसके पास है?", options: ["President", "PM", "Defence Minister", "Parliament"], answer: 0, explain: "President ke paas ye shakti hai (Council of Ministers ki salah par)." },
      { q: "The salaries of Supreme Court judges are charged to the:", hi: "सर्वोच्च न्यायालय के न्यायाधीशों का वेतन किस पर भारित होता है?", options: ["Consolidated Fund of India", "Contingency Fund", "Public Account", "State Fund"], answer: 0, explain: "SC judges ka salary Consolidated Fund of India par charged hai." },
      { q: "Which Article deals with the Uniform Civil Code (a Directive Principle)?", hi: "समान नागरिक संहिता (एक नीति-निदेशक तत्व) किस अनुच्छेद में है?", options: ["Article 44", "Article 21", "Article 14", "Article 32"], answer: 0, explain: "Uniform Civil Code Article 44 (DPSP) me hai." },
      { q: "The office of the Lokpal was established under which Act?", hi: "लोकपाल का पद किस अधिनियम के तहत बना?", options: ["Lokpal and Lokayuktas Act 2013", "RTI Act 2005", "RTE Act 2009", "Prevention of Corruption Act"], answer: 0, explain: "Lokpal, Lokpal and Lokayuktas Act 2013 ke tehat bana." },
      { q: "The 'Right to Information (RTI)' Act was passed in:", hi: "'सूचना का अधिकार (RTI)' अधिनियम कब पारित हुआ?", options: ["2005", "2002", "2009", "2013"], answer: 0, explain: "RTI Act 2005 me pass hua." },
      { q: "The term of office of the Vice President of India is:", hi: "भारत के उपराष्ट्रपति का कार्यकाल कितना है?", options: ["5 years", "6 years", "4 years", "2 years"], answer: 0, explain: "Vice President ka karyakaal 5 saal hota hai." },
      { q: "The first President of India was:", hi: "भारत के पहले राष्ट्रपति कौन थे?", options: ["Dr. Rajendra Prasad", "Radhakrishnan", "Zakir Husain", "Nehru"], answer: 0, explain: "Dr. Rajendra Prasad pehle rashtrapati the (1950-1962)." },
    ],
  },
];
