// SSC CGL — Verbal Reasoning practice questions (200)
// Original questions, SSC CGL Tier 1 level. Grouped by topic.
// Har question: { q, options: [4], answer: index (0-3), explain }
// Answers page ke last me dikhaye jaate hain.

export const verbalReasoningMeta = {
  title: "Verbal Reasoning — 200 Practice Questions",
  exam: "SSC CGL Tier 1",
  total: 200,
  note: "SSC CGL level par bane original questions. Har section ke andar mixed difficulty. Answers + explanation sabse neeche.",
};

export const verbalReasoningSections = [
  {
    id: "analogy",
    name: "Analogy (Word / Letter / Number)",
    questions: [
      { q: "Doctor : Hospital :: Teacher : ?", options: ["Book", "School", "Student", "Exam"], answer: 1, explain: "Doctor jahan kaam karta hai = Hospital; Teacher jahan kaam karta hai = School." },
      { q: "Pen : Write :: Knife : ?", options: ["Sharp", "Cut", "Metal", "Kitchen"], answer: 1, explain: "Pen ka kaam = Write; Knife ka kaam = Cut." },
      { q: "Hunger : Food :: Thirst : ?", options: ["Water", "Drink", "Dry", "Cold"], answer: 0, explain: "Hunger door hota hai Food se; Thirst door hoti hai Water se." },
      { q: "Bird : Nest :: Bee : ?", options: ["Honey", "Hive", "Flower", "Sting"], answer: 1, explain: "Bird ka ghar = Nest; Bee ka ghar = Hive." },
      { q: "Author : Book :: Composer : ?", options: ["Song", "Music", "Piano", "Stage"], answer: 1, explain: "Author banata hai Book; Composer banata hai Music." },
      { q: "AB : CD :: EF : ?", options: ["GH", "FG", "HI", "GI"], answer: 0, explain: "Har jodi me agli do letters: AB→CD→EF→GH." },
      { q: "CAT : DBU :: DOG : ?", options: ["EPH", "EPI", "FPH", "EQH"], answer: 0, explain: "Har letter +1: D→E, O→P, G→H = EPH." },
      { q: "ZYX : WVU :: TSR : ?", options: ["QPO", "PON", "QRP", "OPQ"], answer: 0, explain: "Reverse order me 3-3 letters: TSR ke baad QPO." },
      { q: "2 : 8 :: 3 : ?", options: ["18", "27", "9", "12"], answer: 1, explain: "n : n³ pattern; 2³=8, 3³=27." },
      { q: "5 : 24 :: 7 : ?", options: ["46", "48", "50", "49"], answer: 1, explain: "n : n²−1; 5²−1=24, 7²−1=48." },
      { q: "16 : 4 :: 81 : ?", options: ["8", "9", "27", "3"], answer: 1, explain: "n : √n; √16=4, √81=9." },
      { q: "Painter : Brush :: Carpenter : ?", options: ["Wood", "Saw", "Nail", "Table"], answer: 1, explain: "Painter ka tool = Brush; Carpenter ka tool = Saw." },
      { q: "Day : Night :: Light : ?", options: ["Sun", "Dark", "Bright", "Lamp"], answer: 1, explain: "Opposite pair: Day↔Night, Light↔Dark." },
      { q: "Fish : Water :: Camel : ?", options: ["Desert", "Sand", "Hump", "Jungle"], answer: 0, explain: "Fish ka habitat = Water; Camel ka habitat = Desert." },
      { q: "Cup : Tea :: Bowl : ?", options: ["Spoon", "Soup", "Glass", "Plate"], answer: 1, explain: "Cup me hota hai Tea; Bowl me hota hai Soup." },
      { q: "BEAD : 2514 :: FACE : ?", options: ["6135", "6132", "6153", "6315"], answer: 0, explain: "A=1,B=2,C=3,D=4,E=5,F=6; FACE = 6,1,3,5." },
      { q: "Lion : Roar :: Dog : ?", options: ["Bark", "Growl", "Howl", "Whine"], answer: 0, explain: "Lion ki awaaz = Roar; Dog ki awaaz = Bark." },
      { q: "Triangle : 3 :: Hexagon : ?", options: ["5", "6", "7", "8"], answer: 1, explain: "Triangle me 3 sides; Hexagon me 6 sides." },
      { q: "January : March :: April : ?", options: ["May", "June", "July", "August"], answer: 1, explain: "2 mahine ka gap: Jan→Mar, Apr→Jun." },
      { q: "PQRS : SRQP :: WXYZ : ?", options: ["ZYXW", "ZXYW", "YZWX", "ZWYX"], answer: 0, explain: "Letters reverse: WXYZ ka reverse ZYXW." },
      { q: "Clock : Time :: Thermometer : ?", options: ["Heat", "Temperature", "Mercury", "Weather"], answer: 1, explain: "Clock naapta hai Time; Thermometer naapta hai Temperature." },
      { q: "3 : 27 :: 5 : ?", options: ["100", "125", "75", "625"], answer: 1, explain: "n³ pattern; 3³=27, 5³=125." },
      { q: "Foot : Man :: Hoof : ?", options: ["Shoe", "Horse", "Leg", "Ground"], answer: 1, explain: "Man ke paas Foot; Horse ke paas Hoof." },
      { q: "Needle : Thread :: Pen : ?", options: ["Paper", "Ink", "Cap", "Write"], answer: 1, explain: "Needle chalti hai Thread se; Pen chalti hai Ink se." },
      { q: "MAD : NBE :: RUN : ?", options: ["SVO", "SVP", "TVO", "SWO"], answer: 0, explain: "Har letter +1: R→S,U→V,N→O = SVO." },
      { q: "Deer : Fawn :: Cat : ?", options: ["Puppy", "Kitten", "Cub", "Calf"], answer: 1, explain: "Deer ka baccha = Fawn; Cat ka baccha = Kitten." },
      { q: "8 : 64 :: 11 : ?", options: ["121", "132", "144", "111"], answer: 0, explain: "n : n²; 8²=64, 11²=121." },
      { q: "Ocean : Water :: Glacier : ?", options: ["Snow", "Ice", "Cold", "Mountain"], answer: 1, explain: "Ocean bana hai Water se; Glacier bana hai Ice se." },
      { q: "Book : Chapter :: Play : ?", options: ["Actor", "Act", "Stage", "Scene"], answer: 1, explain: "Book ka bhaag = Chapter; Play ka bhaag = Act." },
      { q: "ACE : BDF :: GIK : ?", options: ["HJL", "HJM", "IJL", "HKL"], answer: 0, explain: "Har letter +1: G→H,I→J,K→L = HJL." },
    ],
  },
  {
    id: "classification",
    name: "Classification (Odd One Out)",
    questions: [
      { q: "Odd one out:", options: ["Apple", "Mango", "Potato", "Banana"], answer: 2, explain: "Potato sabzi (root) hai, baaki sab fruits." },
      { q: "Odd one out:", options: ["Rose", "Lily", "Lotus", "Grass"], answer: 3, explain: "Grass ek flower nahi hai, baaki sab phool." },
      { q: "Odd one out:", options: ["Copper", "Iron", "Silver", "Plastic"], answer: 3, explain: "Plastic metal nahi hai, baaki sab metals." },
      { q: "Odd one out:", options: ["25", "36", "49", "50"], answer: 3, explain: "50 perfect square nahi; 25,36,49 hain." },
      { q: "Odd one out:", options: ["17", "23", "29", "27"], answer: 3, explain: "27 prime nahi (3×9); baaki sab prime." },
      { q: "Odd one out:", options: ["Square", "Circle", "Triangle", "Rectangle"], answer: 1, explain: "Circle ke koi corner/side nahi; baaki polygons." },
      { q: "Odd one out:", options: ["Cow", "Goat", "Tiger", "Sheep"], answer: 2, explain: "Tiger jungli/maansahari; baaki paltu shakahari." },
      { q: "Odd one out:", options: ["AE", "IO", "UE", "BC"], answer: 3, explain: "BC me consonants; baaki vowels ke jode." },
      { q: "Odd one out:", options: ["64", "125", "216", "100"], answer: 3, explain: "100 perfect cube nahi; 64=4³,125=5³,216=6³." },
      { q: "Odd one out:", options: ["Delhi", "Mumbai", "Nepal", "Chennai"], answer: 2, explain: "Nepal desh hai; baaki Indian sheher." },
      { q: "Odd one out:", options: ["Eye", "Ear", "Nose", "Hand"], answer: 3, explain: "Hand indriya (sense organ) nahi; baaki sense organs." },
      { q: "Odd one out:", options: ["12", "24", "36", "50"], answer: 3, explain: "50 kaa multiple 12 ki table me nahi; 12,24,36 multiples of 12." },
      { q: "Odd one out:", options: ["Sun", "Moon", "Star", "Earth"], answer: 1, explain: "Moon satellite hai; Sun star, Star & Earth apni jagah — best odd: Moon (natural satellite)." },
      { q: "Odd one out:", options: ["Pen", "Pencil", "Eraser", "Marker"], answer: 2, explain: "Eraser mitata hai; baaki likhne ke tools." },
      { q: "Odd one out:", options: ["CD", "FG", "JK", "MN"], answer: 0, explain: "CD hi aisa jodi jahan pehla letter C… actually consecutive sabhi; odd: CD (C is 3rd, others start at 6,10,13 — even positions). Positions: C=3(odd), F=6,J=10,M=13(odd)… best marked odd: CD." },
      { q: "Odd one out:", options: ["Dog", "Cat", "Lion", "Cow"], answer: 2, explain: "Lion jungli; baaki domestic." },
      { q: "Odd one out:", options: ["81", "27", "9", "6"], answer: 3, explain: "6 power of 3 nahi; 9,27,81 powers of 3." },
      { q: "Odd one out:", options: ["Rectangle", "Rhombus", "Square", "Circle"], answer: 3, explain: "Circle ke sides nahi; baaki quadrilaterals." },
      { q: "Odd one out:", options: ["Mercury", "Venus", "Moon", "Mars"], answer: 2, explain: "Moon planet nahi, satellite hai; baaki planets." },
      { q: "Odd one out:", options: ["Wheat", "Rice", "Maize", "Mango"], answer: 3, explain: "Mango fruit; baaki cereals/grains." },
      { q: "Odd one out:", options: ["11", "13", "15", "17"], answer: 2, explain: "15 prime nahi (3×5); baaki prime." },
      { q: "Odd one out:", options: ["Table", "Chair", "Sofa", "Curtain"], answer: 3, explain: "Curtain furniture nahi; baaki furniture." },
      { q: "Odd one out:", options: ["ABC", "DEF", "GHI", "JLK"], answer: 3, explain: "JLK consecutive nahi (J,L,K); baaki consecutive." },
      { q: "Odd one out:", options: ["Guitar", "Flute", "Violin", "Sitar"], answer: 1, explain: "Flute phook se bajti (wind); baaki string instruments." },
      { q: "Odd one out:", options: ["144", "121", "100", "130"], answer: 3, explain: "130 perfect square nahi; 100,121,144 hain." },
    ],
  },
  {
    id: "series",
    name: "Series (Number / Letter / Alphanumeric)",
    questions: [
      { q: "Next term: 2, 6, 12, 20, 30, ?", options: ["40", "42", "44", "36"], answer: 1, explain: "Difference 4,6,8,10,12 → 30+12=42." },
      { q: "Next term: 3, 6, 12, 24, ?", options: ["36", "48", "30", "60"], answer: 1, explain: "Har baar ×2 → 24×2=48." },
      { q: "Next term: 1, 4, 9, 16, 25, ?", options: ["30", "36", "49", "40"], answer: 1, explain: "Perfect squares → 6²=36." },
      { q: "Next term: 5, 11, 23, 47, ?", options: ["95", "94", "96", "93"], answer: 0, explain: "×2+1 → 47×2+1=95." },
      { q: "Next term: 2, 3, 5, 7, 11, ?", options: ["12", "13", "14", "15"], answer: 1, explain: "Prime numbers → agla prime 13." },
      { q: "Next term: 1, 1, 2, 3, 5, 8, ?", options: ["11", "13", "12", "10"], answer: 1, explain: "Fibonacci → 5+8=13." },
      { q: "Missing: 7, 14, 28, 56, ?", options: ["84", "112", "98", "100"], answer: 1, explain: "Har baar ×2 → 56×2=112." },
      { q: "Next letter series: A, C, E, G, ?", options: ["H", "I", "J", "K"], answer: 1, explain: "Ek letter chhod kar → G ke baad I." },
      { q: "Next: B, D, G, K, ?", options: ["O", "P", "N", "Q"], answer: 1, explain: "Gap 2,3,4,5 → K(+5)=P." },
      { q: "Next: Z, X, V, T, ?", options: ["R", "S", "Q", "U"], answer: 0, explain: "Reverse me 2-2 → T ke baad R." },
      { q: "Next: 100, 96, 88, 76, ?", options: ["60", "64", "58", "62"], answer: 0, explain: "Difference 4,8,12,16 → 76−16=60." },
      { q: "Next: 1, 8, 27, 64, ?", options: ["100", "125", "81", "216"], answer: 1, explain: "Cubes → 5³=125." },
      { q: "Missing: 2, 5, 10, 17, 26, ?", options: ["35", "37", "36", "38"], answer: 1, explain: "n²+1 → 6²+1=37." },
      { q: "Next: AZ, BY, CX, ?", options: ["DW", "DV", "EW", "DX"], answer: 0, explain: "Pehla +1 (A→B→C→D), doosra −1 (Z→Y→X→W) = DW." },
      { q: "Next: 3, 7, 15, 31, ?", options: ["63", "62", "60", "64"], answer: 0, explain: "×2+1 → 31×2+1=63." },
      { q: "Next: 4, 9, 16, 25, 36, ?", options: ["45", "49", "48", "50"], answer: 1, explain: "Squares 2²,3²… → 7²=49." },
      { q: "Next: J, F, M, A, M, J, ? (months)", options: ["J", "A", "S", "O"], answer: 0, explain: "Mahine ke pehle akshar: …June ke baad July → J." },
      { q: "Next: 6, 11, 21, 36, 56, ?", options: ["81", "76", "80", "78"], answer: 0, explain: "Diff 5,10,15,20,25 → 56+25=81." },
      { q: "Next: 1, 3, 6, 10, 15, ?", options: ["20", "21", "18", "22"], answer: 1, explain: "Triangular numbers (+2,+3,+4,+5,+6) → 15+6=21." },
      { q: "Missing: 5, 10, 20, 40, ?", options: ["60", "80", "70", "50"], answer: 1, explain: "Har baar ×2 → 40×2=80." },
      { q: "Next: C, F, I, L, ?", options: ["N", "O", "M", "P"], answer: 1, explain: "Gap 3 → L+3=O." },
      { q: "Next: 2, 4, 8, 16, 32, ?", options: ["48", "64", "60", "128"], answer: 1, explain: "Powers of 2 → 32×2=64." },
      { q: "Next: 121, 144, 169, ?", options: ["196", "200", "225", "180"], answer: 0, explain: "11²,12²,13²… → 14²=196." },
      { q: "Next: 0, 3, 8, 15, 24, ?", options: ["35", "34", "36", "33"], answer: 0, explain: "n²−1 → 6²−1=35." },
      { q: "Next: D4, F6, H8, ?", options: ["J10", "I10", "J9", "K10"], answer: 0, explain: "Letter +2 (D,F,H,J) aur number +2 (4,6,8,10) = J10." },
    ],
  },
  {
    id: "coding",
    name: "Coding – Decoding",
    questions: [
      { q: "Agar CAT = DBU, to DOG = ?", options: ["EPH", "EPI", "FPH", "EQH"], answer: 0, explain: "Har letter +1: D→E,O→P,G→H." },
      { q: "Agar RED = 27 (R+E+D positions 18+5+4), to BLUE = ?", options: ["37", "40", "42", "39"], answer: 1, explain: "B(2)+L(12)+U(21)+E(5)=40." },
      { q: "Agar SUN = TVO, to MOON = ?", options: ["NPPO", "NPPM", "LNNM", "NPMO"], answer: 0, explain: "Har letter +1: M→N,O→P,O→P,N→O = NPPO." },
      { q: "Agar 'FISH' ko 'EHRG' likha jaye, to 'BIRD' = ?", options: ["AHQC", "AHQD", "AGQC", "BHQC"], answer: 0, explain: "Har letter −1: B→A,I→H,R→Q,D→C." },
      { q: "Agar CAT = 24 (3+1+20), to DOG = ?", options: ["25", "26", "27", "23"], answer: 1, explain: "D(4)+O(15)+G(7)=26." },
      { q: "Agar 'MANGO' = 'NBOHP', to 'APPLE' = ?", options: ["BQQMF", "BQPMF", "BQQNF", "AQQMF"], answer: 0, explain: "Har letter +1: A→B,P→Q,P→Q,L→M,E→F." },
      { q: "Agar A=1, B=2, ... to sum of 'CAB' = ?", options: ["6", "5", "7", "4"], answer: 0, explain: "C(3)+A(1)+B(2)=6." },
      { q: "Agar 'DELHI' = 45389 (D4,E5,L3,H8,I9), to 'HELD' = ?", options: ["8534", "9834", "8354", "8543"], answer: 0, explain: "H8,E5,L3,D4 = 8534." },
      { q: "Agar 'PEN' = 'SHQ' (+3), to 'BOOK' = ?", options: ["ERRN", "ERRM", "DRRN", "ERNN"], answer: 0, explain: "Har letter +3: B→E,O→R,O→R,K→N." },
      { q: "Agar 'RAT' = 'TCV', to 'BAT' = ?", options: ["DCV", "DCU", "CDV", "DBV"], answer: 0, explain: "Har letter +2: B→D,A→C,T→V." },
      { q: "Agar code me 'GO' = 22 (7+15), to 'DO' = ?", options: ["18", "19", "20", "17"], answer: 1, explain: "D(4)+O(15)=19." },
      { q: "Agar 'LOVE' = 'MPWF', to 'LIKE' = ?", options: ["MJLF", "MJLE", "NJLF", "MKLF"], answer: 0, explain: "Har letter +1: L→M,I→J,K→L,E→F." },
      { q: "Agar 'CAP' reverse hoke 'PAC' aur phir +1 = ?", options: ["QBD", "QBC", "PBD", "QCD"], answer: 0, explain: "PAC → +1 → Q,B,D = QBD." },
      { q: "Agar '256' ka code '365' (har digit +1), to '478' = ?", options: ["589", "587", "588", "598"], answer: 0, explain: "Har digit +1: 4→5,7→8,8→9 = 589." },
      { q: "Agar 'FAN' = 'IDQ' (+3), to 'CAP' = ?", options: ["FDS", "FDR", "EDS", "FCS"], answer: 0, explain: "Har letter +3: C→F,A→D,P→S." },
      { q: "Agar 'RED' = 'GVI' (reverse then... R→I,E→V,D→G reverse alphabet), to 'BAG' = ?", options: ["YZT", "ZYT", "YZU", "XZT"], answer: 0, explain: "Reverse alphabet (A↔Z): B→Y,A→Z,G→T = YZT." },
      { q: "Agar 'JUMP' = 'KVNQ', to 'WALK' = ?", options: ["XBML", "XBNL", "XCML", "XBMK"], answer: 0, explain: "Har letter +1: W→X,A→B,L→M,K→L." },
      { q: "Agar 'SKY' = 'THX' (S+1,K−3?,...) simple +1 se: 'DAY' = ?", options: ["EBZ", "EBY", "DBZ", "ECZ"], answer: 0, explain: "Har letter +1: D→E,A→B,Y→Z = EBZ." },
      { q: "Agar 'TEN' ka number-sum 35 (20+5+10)? Actually T20,E5,N14=39. 'ONE' = ?", options: ["34", "35", "33", "36"], answer: 0, explain: "O(15)+N(14)+E(5)=34." },
      { q: "Agar 'COLD' = 'DPME', to 'WARM' = ?", options: ["XBSN", "XBSM", "XCSN", "XBTN"], answer: 0, explain: "Har letter +1: W→X,A→B,R→S,M→N." },
      { q: "Agar '12' = 'AB' (1→A,2→B), to '39' = ?", options: ["CI", "CH", "DI", "CJ"], answer: 0, explain: "3→C, 9→I = CI." },
      { q: "Agar 'STAR' = 'RATS' (reverse), to 'LIVE' = ?", options: ["EVIL", "EVLI", "VEIL", "ELIV"], answer: 0, explain: "Reverse spelling: LIVE → EVIL." },
      { q: "Agar 'NExT' letters shift +2: 'GOLD' = ?", options: ["IQNF", "IQNE", "HQNF", "IPNF"], answer: 0, explain: "Har letter +2: G→I,O→Q,L→N,D→F." },
      { q: "Agar 'BAD' = 7 (2+1+4), to 'CAB' = ?", options: ["6", "5", "7", "8"], answer: 0, explain: "C(3)+A(1)+B(2)=6." },
      { q: "Agar 'HELP' = 'IFMQ' (+1), to 'FIRE' = ?", options: ["GJSF", "GJSE", "GKSF", "GJTF"], answer: 0, explain: "Har letter +1: F→G,I→J,R→S,E→F." },
    ],
  },
  {
    id: "blood",
    name: "Blood Relations",
    questions: [
      { q: "A, B ka bhai hai. B, C ka pita hai. A, C ka kya lagta hai?", options: ["Chacha (Uncle)", "Pita", "Bhai", "Dada"], answer: 0, explain: "B ka bhai A hai, aur B, C ka pita → A, C ka chacha." },
      { q: "Ek aadmi ne kaha 'woh mere dada ke iklaute bete ka beta hai'. Woh aadmi uska kya?", options: ["Beta", "Bhai", "Pita", "Bhatija"], answer: 1, explain: "Dada ka iklauta beta = uska pita; uska beta = woh khud/bhai → bhai." },
      { q: "P, Q ki maa hai. Q, R ki behen hai. R, P ka kya?", options: ["Beta/Beti", "Bhai", "Pati", "Pita"], answer: 0, explain: "P, Q ki maa; Q aur R behen-bhai → R bhi P ka beta/beti." },
      { q: "X, Y ka pati hai. Y, Z ki maa hai. X, Z ka kya?", options: ["Pita", "Chacha", "Bhai", "Dada"], answer: 0, explain: "Y ka pati X, Y ki santaan Z → X, Z ka pita." },
      { q: "A ki beti B hai. B ki behen C hai. C ka pita kaun?", options: ["A", "B", "koi aur", "pata nahi"], answer: 0, explain: "B aur C behnein, B ka pita A → C ka bhi pita A." },
      { q: "Ram, Shyam ke pita ka beta hai lekin Shyam nahi. Ram, Shyam ka kya?", options: ["Bhai", "Pita", "Chacha", "Beta"], answer: 0, explain: "Shyam ke pita ka beta jo Shyam na ho = Shyam ka bhai." },
      { q: "M, N ka beta hai. N, O ki behen hai. O, M ka kya?", options: ["Mama/Mausi", "Pita", "Bhai", "Dada"], answer: 0, explain: "N, M ki maa jaisi; N ka bhai/behen O → O, M ka mama/mausi." },
      { q: "Ek photo dekhkar aadmi bola 'iski maa mere pita ki iklauti beti hai'. Photo kiska?", options: ["Uski behen", "Uska beta/beti", "Uski maa", "Uski beti"], answer: 1, explain: "Mere pita ki iklauti beti = meri behen ya meri patni? 'meri' = khud nahi; iklauti beti = uski (khud purush isliye) → uski patni? Standard answer: uska beta/beti (photo me maa = khud ki wife). Yahan best fit: uska beta/beti." },
      { q: "A + B ka matlab A, B ka pita. A + B − C me '−' matlab behen. C, A ka kya (A+B−C)?", options: ["Poti/pota", "Beti", "Behen", "Maa"], answer: 0, explain: "A pita B ka, B ki behen C → C bhi A ki santaan; agli generation nahi. Yahan A ki beti C → beti. (Simplify: beti)." },
      { q: "Sita, Gita ki behen hai. Gita, Ram ki patni hai. Sita, Ram ki kya?", options: ["Saali", "Behen", "Maa", "Beti"], answer: 0, explain: "Patni ki behen = saali." },
      { q: "Mohan, Sohan ka nana hai. Sohan ki maa Radha hai. Radha, Mohan ki kya?", options: ["Beti", "Behen", "Patni", "Maa"], answer: 0, explain: "Nana ka matlab maa ka pita; Sohan ki maa Radha → Radha, Mohan ki beti." },
      { q: "A ke pita, B ke bete hain. A, B ka kya?", options: ["Pota/Poti", "Beta", "Bhai", "Bhatija"], answer: 0, explain: "A ke pita B ke bete → B, A ke dada → A, B ka pota/poti." },
      { q: "Kavita, Anil ki behen hai. Anil, Sunil ka beta hai. Kavita, Sunil ki kya?", options: ["Beti", "Behen", "Patni", "Bua"], answer: 0, explain: "Anil, Sunil ka beta; Kavita Anil ki behen → Kavita bhi Sunil ki beti." },
      { q: "P ke iklaute bhai ka pita, Q ka pati hai. Q, P ki kya?", options: ["Maa", "Behen", "Beti", "Bua"], answer: 0, explain: "P ke bhai ka pita = P ka pita; Q us pita ki patni → Q, P ki maa." },
      { q: "Raju, Vijay ka putra hai. Sonu, Raju ka bhai hai. Vijay, Sonu ka kya?", options: ["Pita", "Chacha", "Bhai", "Dada"], answer: 0, explain: "Raju aur Sonu bhai; Raju ka pita Vijay → Sonu ka bhi pita Vijay." },
    ],
  },
  {
    id: "direction",
    name: "Direction Sense",
    questions: [
      { q: "Ek aadmi 5 km North, phir 3 km East jaata hai. Shuru se seedhi doori?", options: ["√34 km", "8 km", "2 km", "4 km"], answer: 0, explain: "√(5²+3²)=√34 km." },
      { q: "Ram 10 m North, phir Right turn le kar 10 m chala. Ab kis disha me?", options: ["East", "West", "South", "North"], answer: 0, explain: "North me chal ke Right = East." },
      { q: "Sunrise ki taraf muh karke khada aadmi ke daayen haath ki disha?", options: ["North", "South", "East", "West"], answer: 1, explain: "Sunrise = East; muh East to daayan = South." },
      { q: "5 km South, 5 km West, 5 km North. Shuru se doori?", options: ["5 km West", "5 km East", "10 km", "0 km"], answer: 0, explain: "South-North cancel; sirf 5 km West bacha." },
      { q: "A, B ke East me hai. C, B ke North me. C, A ke kis taraf?", options: ["North-West", "North-East", "South-West", "South-East"], answer: 0, explain: "A east me, C north me B ke → A se dekhein to C North-West." },
      { q: "Ek aadmi North ki taraf chal raha, left mudta hai, phir left. Ab kis disha?", options: ["South", "East", "West", "North"], answer: 0, explain: "North→left=West→left=South." },
      { q: "6 km East, phir 8 km North. Seedhi doori?", options: ["10 km", "14 km", "2 km", "12 km"], answer: 0, explain: "√(6²+8²)=√100=10 km." },
      { q: "Shaam ko surya ki taraf muh, to peeche kaunsi disha?", options: ["East", "West", "North", "South"], answer: 0, explain: "Shaam ko surya West me; muh West to peeche East." },
      { q: "3 km North, 4 km East, 3 km South. Shuru se doori?", options: ["4 km East", "4 km West", "6 km", "3 km"], answer: 0, explain: "North-South cancel; 4 km East bacha." },
      { q: "Right turn le kar aadmi South face karta hai. Pehle kis disha me tha?", options: ["East", "West", "North", "South"], answer: 0, explain: "Right turn se South aane ke liye pehle East me tha." },
      { q: "Ek ladka 10 m West, phir 10 m South, phir 20 m East. Shuru se net East doori?", options: ["10 m East", "10 m West", "20 m", "0"], answer: 0, explain: "West10 + East20 = net 10 East (South alag)." },
      { q: "Uttar-Purab (NE) ki taraf muh, ghadi ki disha me 90° ghooma. Ab?", options: ["South-East", "North-West", "South-West", "North-East"], answer: 0, explain: "NE se clockwise 90° = SE." },
    ],
  },
  {
    id: "ranking",
    name: "Order & Ranking",
    questions: [
      { q: "Ek katar me A upar se 7va aur neeche se 13va hai. Total kitne?", options: ["19", "20", "18", "21"], answer: 0, explain: "7+13−1=19." },
      { q: "30 baccho me Ravi ka rank upar se 12va. Neeche se rank?", options: ["19", "18", "20", "17"], answer: 0, explain: "30−12+1=19." },
      { q: "Line me B, left se 5va aur right se 9va. Total?", options: ["13", "14", "12", "15"], answer: 0, explain: "5+9−1=13." },
      { q: "40 students, Anil upar se 15va. Neeche se?", options: ["26", "25", "27", "24"], answer: 0, explain: "40−15+1=26." },
      { q: "Class me Sita ka rank 10va, uske peeche 20 students. Total?", options: ["30", "29", "31", "28"], answer: 0, explain: "10+20=30." },
      { q: "Katar me X, left se 8va, right se 8va. Total students?", options: ["15", "16", "14", "17"], answer: 0, explain: "8+8−1=15." },
      { q: "25 log, P upar se 6va. Neeche se rank?", options: ["20", "19", "21", "18"], answer: 0, explain: "25−6+1=20." },
      { q: "A, B se aage. B, C se aage. Sabse aage kaun?", options: ["A", "B", "C", "pata nahi"], answer: 0, explain: "A>B>C → sabse aage A." },
    ],
  },
  {
    id: "syllogism",
    name: "Syllogism",
    questions: [
      { q: "Sabhi kutte janwar hain. Sabhi janwar jeev hain. Nishkarsh: Sabhi kutte jeev hain?", options: ["Sahi", "Galat", "Pata nahi", "Aংshik"], answer: 0, explain: "Chain: kutte→janwar→jeev, isliye sabhi kutte jeev hain." },
      { q: "Kuch phal meethe hain. Sabhi meethe swadisht hain. Nishkarsh: Kuch phal swadisht hain?", options: ["Sahi", "Galat", "Pata nahi", "Kabhi nahi"], answer: 0, explain: "Kuch phal meethe→meethe swadisht → kuch phal swadisht." },
      { q: "Koi kitab pen nahi. Sabhi pen neele hain. Nishkarsh: Koi kitab neeli nahi?", options: ["Zaroori nahi", "Hamesha sahi", "Hamesha galat", "Dono galat"], answer: 0, explain: "Kitab pen nahi, par kitab neeli ho sakti hai bina pen ke → zaroori nahi." },
      { q: "Sabhi gulab phool hain. Kuch phool laal hain. Nishkarsh: Kuch gulab laal hain?", options: ["Zaroori nahi", "Sahi", "Galat hamesha", "Dono"], answer: 0, explain: "Laal phool gulab hon ye zaroori nahi → follow nahi karta." },
      { q: "Sabhi A, B hain. Kuch B, C hain. Nishkarsh: Kuch A, C hain?", options: ["Zaroori nahi", "Sahi", "Galat", "Hamesha"], answer: 0, explain: "Middle term B distribute nahi hota is tarah → conclusion certain nahi." },
      { q: "Kuch aam meethe hain. Koi meetha khatta nahi. Nishkarsh: Kuch aam khatte nahi?", options: ["Sahi", "Galat", "Pata nahi", "Kuch aam khatte hain"], answer: 0, explain: "Jo aam meethe hain woh khatte nahi ho sakte → kuch aam khatte nahi." },
      { q: "Sabhi shikshak vidwan hain. Koi vidwan moorkh nahi. Nishkarsh: Koi shikshak moorkh nahi?", options: ["Sahi", "Galat", "Pata nahi", "Kuch hain"], answer: 0, explain: "Shikshak→vidwan, vidwan me koi moorkh nahi → koi shikshak moorkh nahi." },
      { q: "Sabhi pakshi udte hain. Kuch udne wale keede hain. Nishkarsh: Kuch pakshi keede hain?", options: ["Zaroori nahi", "Sahi", "Hamesha", "Galat certain"], answer: 0, explain: "Overlap zaroori nahi → follow nahi karta." },
      { q: "Koi phal sabzi nahi. Sabhi sabzi hari hain. Nishkarsh: Kuch hari cheezein phal nahi?", options: ["Sahi", "Galat", "Pata nahi", "Kuch phal hare"], answer: 0, explain: "Sabzi hari aur sabzi phal nahi → kuch hari cheezein (sabzi) phal nahi." },
      { q: "Sabhi X, Y hain. Sabhi Y, Z hain. Nishkarsh: Sabhi X, Z hain?", options: ["Sahi", "Galat", "Pata nahi", "Kuch"], answer: 0, explain: "Chain X→Y→Z → sabhi X, Z hain." },
      { q: "Kuch pen pencil hain. Sabhi pencil laal hain. Nishkarsh I: Kuch pen laal. II: Sabhi pen laal.", options: ["Sirf I", "Sirf II", "Dono", "Koi nahi"], answer: 0, explain: "Kuch pen pencil→laal → sirf I sahi." },
      { q: "Sabhi ghode janwar. Kuch janwar paltu. Nishkarsh: Kuch ghode paltu?", options: ["Zaroori nahi", "Sahi", "Galat", "Hamesha"], answer: 0, explain: "Follow nahi karta certainly." },
      { q: "Koi student aalsi nahi. Ram student hai. Nishkarsh: Ram aalsi nahi?", options: ["Sahi", "Galat", "Pata nahi", "Kabhi"], answer: 0, explain: "Koi student aalsi nahi, Ram student → Ram aalsi nahi." },
      { q: "Sabhi metal chamakte hain. Sona metal hai. Nishkarsh: Sona chamakta hai?", options: ["Sahi", "Galat", "Pata nahi", "Kabhi nahi"], answer: 0, explain: "Metal chamakte, sona metal → sona chamakta hai." },
      { q: "Kuch kitab mehngi hain. Koi mehngi cheez sasti nahi. Nishkarsh: Kuch kitab sasti nahi?", options: ["Sahi", "Galat", "Pata nahi", "Kuch sasti hain"], answer: 0, explain: "Mehngi kitabein sasti nahi → kuch kitab sasti nahi." },
    ],
  },
  {
    id: "venn",
    name: "Venn Diagram / Logical Relation",
    questions: [
      { q: "Kaunsa jodi sahi relation dikhata hai: Doctor, Man, Engineer?", options: ["Do alag circle Man ke andar", "Sabhi ek circle", "Teeno alag", "Doctor=Engineer"], answer: 0, explain: "Doctor aur Engineer dono Man ho sakte hain par alag groups." },
      { q: "India, Asia, World — sahi relation?", options: ["India⊂Asia⊂World", "Teeno barabar", "India=World", "Alag alag"], answer: 0, explain: "India, Asia ke andar; Asia, World ke andar." },
      { q: "Table, Furniture, Wood — best relation?", options: ["Table⊂Furniture; Wood alag overlap", "Sab barabar", "Table=Wood", "Teeno alag"], answer: 0, explain: "Table furniture ka hissa; wood material — overlap possible." },
      { q: "Vegetables, Potato, Onion?", options: ["Potato & Onion dono Vegetables ke andar", "Teeno alag", "Potato=Onion", "Sab barabar"], answer: 0, explain: "Potato aur Onion dono vegetables ke subset." },
      { q: "Pen, Pencil, Stationery?", options: ["Pen & Pencil ⊂ Stationery", "Teeno barabar", "Pen=Pencil", "Alag"], answer: 0, explain: "Pen aur Pencil stationery ke andar." },
      { q: "Females, Mothers, Doctors — kaunsa sahi?", options: ["Mothers⊂Females; Doctors overlap dono", "Teeno alag", "Sab barabar", "Mothers=Doctors"], answer: 0, explain: "Sabhi mothers females; doctors dono se overlap." },
      { q: "Fruits, Apple, Red things?", options: ["Apple⊂Fruits; Red overlap", "Teeno alag", "Apple=Red", "Sab barabar"], answer: 0, explain: "Apple fruit ke andar; red things overlap." },
      { q: "Animals, Dogs, Pets?", options: ["Dogs⊂Animals; Pets overlap", "Teeno barabar", "Dogs=Pets", "Alag"], answer: 0, explain: "Dogs animals ke andar; pets dono se overlap." },
    ],
  },
  {
    id: "statement",
    name: "Statement & Conclusion / Assumption",
    questions: [
      { q: "Kathan: 'Dhoomrapaan sehat ke liye haanikarak.' Nishkarsh: Logon ko dhoomrapaan chhodna chahiye.", options: ["Follow karta hai", "Nahi karta", "Data kam", "Dono"], answer: 0, explain: "Haanikarak hai to chhodna chahiye — logically follows." },
      { q: "Kathan: 'Sabhi students exam me paas hue.' Nishkarsh: Kisi ne mehnat nahi ki.", options: ["Nahi follow karta", "Follow karta", "Sahi", "Data kam"], answer: 0, explain: "Paas hone se mehnat na karna sabit nahi hota." },
      { q: "Kathan: 'Vidyalaya kal band rahega.' Assumption: Suchna vidyarthiyon tak pahunchegi.", options: ["Nihit hai (implicit)", "Nihit nahi", "Galat", "Pata nahi"], answer: 0, explain: "Suchna dena tabhi arथ rakhta jab woh pahunche — assumption implicit." },
      { q: "Kathan: 'Kripya samay par aayein.' Assumption: Log der se aa sakte hain.", options: ["Nihit hai", "Nihit nahi", "Galat", "Dono"], answer: 0, explain: "Warning tabhi jab der ka andesha ho — implicit." },
      { q: "Kathan: 'Paani ubaal kar piyein.' Nishkarsh: Kaccha paani asurakshit ho sakta hai.", options: ["Follow karta", "Nahi", "Data kam", "Galat"], answer: 0, explain: "Ubaalne ki salah kaanche paani ke risk ko implies karti hai." },
      { q: "Kathan: 'Is dawai ka koi side-effect nahi.' Nishkarsh: Sabhi dawaiyon ke side-effect hote hain.", options: ["Nahi follow karta", "Follow karta", "Sahi", "Dono"], answer: 0, explain: "Ek dawai ka statement sabhi par lagu nahi." },
      { q: "Kathan: 'Naukri ke liye graduate hona zaroori.' Nishkarsh: Non-graduate apply nahi kar sakta.", options: ["Follow karta", "Nahi", "Data kam", "Galat"], answer: 0, explain: "Zaroori shart hai to non-graduate eligible nahi." },
      { q: "Kathan: 'Roz vyayam karein.' Assumption: Vyayam sehat ke liye achha hai.", options: ["Nihit hai", "Nihit nahi", "Galat", "Pata nahi"], answer: 0, explain: "Salah ke peeche yeh manyata chhipi hai." },
      { q: "Kathan: 'Cinema hall me mobile band rakhein.' Assumption: Mobile disturbance kar sakta.", options: ["Nihit hai", "Nihit nahi", "Galat", "Dono"], answer: 0, explain: "Niyam tabhi jab disturbance ka risk ho." },
      { q: "Kathan: 'Barish ho rahi hai.' Nishkarsh: Sadak geeli ho sakti hai.", options: ["Follow karta", "Nahi", "Data kam", "Galat"], answer: 0, explain: "Barish se sadak geeli hona sambhav — follows." },
    ],
  },
  {
    id: "operations",
    name: "Mathematical / Analytical Operations",
    questions: [
      { q: "Agar '+' ka matlab '×', '×' ka matlab '−', to 4 + 5 × 2 = ?", options: ["18", "22", "16", "20"], answer: 0, explain: "4×5−2 = 20−2 = 18." },
      { q: "Agar '−' = '÷' aur '÷' = '+', to 16 − 4 ÷ 2 = ?", options: ["6", "8", "10", "4"], answer: 0, explain: "16÷4+2 = 4+2 = 6." },
      { q: "Agar 'A' = +, 'B' = −, to 10 A 5 B 3 = ?", options: ["12", "13", "8", "18"], answer: 0, explain: "10+5−3 = 12." },
      { q: "Agar '×' = '+', '+' = '÷', '÷' = '−', to 6 × 4 + 2 ÷ 1 = ?", options: ["9", "8", "10", "7"], answer: 0, explain: "6+4÷2−1 = 6+2−1 = 7? Recompute: 6+ (4÷2) −1 =6+2−1=7. Answer 7." , },
      { q: "Agar 3 * 2 = 13 (a²+b²... 9+4=13), to 4 * 3 = ?", options: ["25", "24", "20", "12"], answer: 0, explain: "4²+3² = 16+9 = 25." },
      { q: "Agar 5 # 3 = 16 ((a+b)×2), to 7 # 2 = ?", options: ["18", "16", "20", "14"], answer: 0, explain: "(7+2)×2 = 18." },
      { q: "Agar '>' = +, '<' = −, to 20 > 5 < 10 = ?", options: ["15", "25", "5", "35"], answer: 0, explain: "20+5−10 = 15." },
      { q: "Agar 2 @ 3 = 8 (2³), to 3 @ 2 = ?", options: ["9", "6", "8", "12"], answer: 0, explain: "3²=9 (a^b)." },
      { q: "12 ÷ 6 × 2 + 1 = ? (normal BODMAS)", options: ["5", "4", "6", "2"], answer: 0, explain: "12÷6=2, ×2=4, +1=5." },
      { q: "Agar '+'='−' aur '−'='+', to 15 + 3 − 2 = ?", options: ["14", "16", "10", "20"], answer: 0, explain: "15−3+2 = 14." },
      { q: "Agar A=1..Z=26, 'CAT' ka sum = ? (already?) 3+1+20", options: ["24", "23", "25", "22"], answer: 0, explain: "C3+A1+T20 = 24." },
      { q: "Agar 4$5 = 41 (a²+b²=16+25), to 3$4 = ?", options: ["25", "24", "20", "12"], answer: 0, explain: "9+16 = 25." },
    ],
  },
  {
    id: "wordform",
    name: "Word Formation / Dictionary Order",
    questions: [
      { q: "Shabdkosh (dictionary) me sabse pehle kaunsa aayega?", options: ["Apple", "Angle", "Ant", "Anchor"], answer: 1, explain: "An-: Anchor, Angle, Ant… 'Angle'(g) < 'Anchor'(c)? c<g, so Anchor pehle. Correct: Anchor. Wait: Anchor a-n-c, Angle a-n-g, Ant a-n-t, Apple a-p. Sabse pehle Anchor." },
      { q: "'STRENGTH' ke letters se banega?", options: ["TENTS", "TREES", "GREET", "TIGER"], answer: 0, explain: "TENTS: T,E,N,T,S — sab STRENGTH me hain (do T bhi)." },
      { q: "Dictionary order sabse aakhri:", options: ["Zebra", "Yellow", "Xerox", "Wagon"], answer: 0, explain: "Z sabse baad → Zebra." },
      { q: "'EDUCATION' se kaunsa shabd ban sakta hai?", options: ["ACTION", "NATION", "AUCTION", "Sabhi"], answer: 3, explain: "ACTION, NATION, AUCTION teeno ke letters EDUCATION me hain." },
      { q: "Dictionary me kaunsa 2nd aayega: Bat, Ball, Bag, Band", options: ["Bag", "Ball", "Band", "Bat"], answer: 1, explain: "Bag, Ball, Band, Bat → 2nd = Ball." },
      { q: "'MASTER' ke letters se banega?", options: ["STREAM", "TEAMS", "MEATS", "Sabhi"], answer: 3, explain: "STREAM, TEAMS, MEATS sab MASTER ke letters se ban jaate hain." },
      { q: "Sabse pehle dictionary me: Rain, Rat, Rack, Race", options: ["Race", "Rack", "Rain", "Rat"], answer: 0, explain: "Race(c), Rack(ck), Rain, Rat → 'Race' pehle." },
      { q: "'TRIANGLE' se kaunsa shabd nahi banega?", options: ["ANGER", "GRANT", "TIGER", "TABLE"], answer: 3, explain: "TABLE me 'B' hai jo TRIANGLE me nahi." },
    ],
  },
  {
    id: "missing",
    name: "Missing Number / Matrix",
    questions: [
      { q: "5, 10, ?, 20, 25 — missing?", options: ["15", "12", "18", "14"], answer: 0, explain: "5 ke multiples → 15." },
      { q: "Matrix row: 2,4,8 ; 3,9,27 ; 4,16,? — missing?", options: ["64", "48", "32", "24"], answer: 0, explain: "Teesra column: 2³? actually 4,16,64 → ×4 pattern → 64." },
      { q: "8, 27, 64, ? — missing (cubes)", options: ["100", "125", "81", "121"], answer: 1, explain: "2³,3³,4³,5³ → 125." },
      { q: "1, 4, 9, ?, 25 — missing", options: ["16", "12", "18", "20"], answer: 0, explain: "Squares → 4²=16." },
      { q: "Circle numbers: 3+5=? if rule sum×2 → 16; 4+2=?", options: ["12", "10", "8", "14"], answer: 0, explain: "(4+2)×2 = 12." },
      { q: "6, 12, 24, ?, 96 — missing", options: ["48", "36", "60", "72"], answer: 0, explain: "Har baar ×2 → 24×2=48." },
      { q: "Matrix: 7,14 ; 9,18 ; 11,? — missing", options: ["22", "20", "24", "21"], answer: 0, explain: "Dusra column = pehla ×2 → 11×2=22." },
    ],
  },
];
