// SSC CGL — General Awareness: GENERAL SCIENCE (100 questions)
// Bilingual (English + Hindi), CGL level. Physics, Chemistry, Biology.

export const scienceMeta = {
  title: "General Science — 100 Practice Questions",
  exam: "SSC CGL — General Awareness",
  total: 100,
  note: "SSC CGL level General Science questions (Physics, Chemistry, Biology). Bilingual English + हिंदी. Answers 'Show Answer Key' me.",
};

export const scienceSections = [
  {
    id: "physics",
    name: "Physics",
    questions: [
      { q: "The SI unit of force is:", hi: "बल की SI इकाई क्या है?", options: ["Newton", "Joule", "Watt", "Pascal"], answer: 0, explain: "Force ki SI unit Newton (N) hai." },
      { q: "The SI unit of electric current is:", hi: "विद्युत धारा की SI इकाई क्या है?", options: ["Ampere", "Volt", "Watt", "Ohm"], answer: 0, explain: "Electric current ki SI unit Ampere hai." },
      { q: "The SI unit of energy/work is:", hi: "ऊर्जा/कार्य की SI इकाई क्या है?", options: ["Joule", "Newton", "Watt", "Pascal"], answer: 0, explain: "Energy/Work ki SI unit Joule hai." },
      { q: "The SI unit of power is:", hi: "शक्ति की SI इकाई क्या है?", options: ["Watt", "Joule", "Newton", "Volt"], answer: 0, explain: "Power ki SI unit Watt hai." },
      { q: "The SI unit of pressure is:", hi: "दाब की SI इकाई क्या है?", options: ["Pascal", "Newton", "Joule", "Bar"], answer: 0, explain: "Pressure ki SI unit Pascal hai." },
      { q: "Which law states 'For every action there is an equal and opposite reaction'?", hi: "कौन-सा नियम कहता है 'हर क्रिया की समान और विपरीत प्रतिक्रिया होती है'?", options: ["Newton's Third Law", "Newton's First Law", "Ohm's Law", "Boyle's Law"], answer: 0, explain: "Newton ka teesra niyam (action-reaction)." },
      { q: "The speed of light in vacuum is approximately:", hi: "निर्वात में प्रकाश की गति लगभग कितनी है?", options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "3 × 10⁵ m/s"], answer: 0, explain: "Prakash ki gati ~3 × 10⁸ m/s hai." },
      { q: "The device used to measure electric current is:", hi: "विद्युत धारा मापने का यंत्र कौन-सा है?", options: ["Ammeter", "Voltmeter", "Galvanometer", "Ohmmeter"], answer: 0, explain: "Ammeter current naapta hai." },
      { q: "The phenomenon of light bending as it passes from one medium to another is:", hi: "एक माध्यम से दूसरे में जाने पर प्रकाश के मुड़ने की घटना क्या है?", options: ["Refraction", "Reflection", "Diffraction", "Dispersion"], answer: 0, explain: "Refraction (apvartan) me light madhyam badalne par mudti hai." },
      { q: "A rainbow is formed due to:", hi: "इंद्रधनुष किस कारण बनता है?", options: ["Dispersion of light", "Reflection only", "Absorption", "Refraction only"], answer: 0, explain: "Rainbow prakash ke dispersion (varn-vikiran) se banta hai." },
      { q: "The unit of resistance is:", hi: "प्रतिरोध की इकाई क्या है?", options: ["Ohm", "Ampere", "Volt", "Watt"], answer: 0, explain: "Resistance ki unit Ohm (Ω) hai." },
      { q: "Which mirror is used as a rear-view mirror in vehicles?", hi: "वाहनों में पीछे देखने के लिए कौन-सा दर्पण प्रयोग होता है?", options: ["Convex mirror", "Concave mirror", "Plane mirror", "Cylindrical mirror"], answer: 0, explain: "Convex mirror rear-view ke liye (wider view) use hota hai." },
      { q: "Sound cannot travel through:", hi: "ध्वनि किसमें यात्रा नहीं कर सकती?", options: ["Vacuum", "Air", "Water", "Solid"], answer: 0, explain: "Sound vacuum (nirvat) me travel nahi kar sakti (medium chahiye)." },
      { q: "The energy possessed by a body due to its motion is:", hi: "गति के कारण किसी वस्तु में मौजूद ऊर्जा क्या कहलाती है?", options: ["Kinetic energy", "Potential energy", "Heat energy", "Chemical energy"], answer: 0, explain: "Gati ke kaaran urja = Kinetic energy (gatij urja)." },
      { q: "The instrument used to measure temperature is:", hi: "तापमान मापने का यंत्र कौन-सा है?", options: ["Thermometer", "Barometer", "Hygrometer", "Ammeter"], answer: 0, explain: "Thermometer taapmaan naapta hai." },
      { q: "Which color of light has the longest wavelength?", hi: "किस रंग के प्रकाश की तरंगदैर्ध्य सबसे अधिक है?", options: ["Red", "Violet", "Blue", "Green"], answer: 0, explain: "Red (laal) ki wavelength sabse zyada hai (VIBGYOR)." },
      { q: "The principle used in a hydraulic lift is:", hi: "हाइड्रोलिक लिफ्ट में किस सिद्धांत का प्रयोग होता है?", options: ["Pascal's Law", "Archimedes' Principle", "Bernoulli's Principle", "Newton's Law"], answer: 0, explain: "Hydraulic lift Pascal's Law par kaam karti hai." },
      { q: "An object floats in water due to:", hi: "कोई वस्तु पानी में किस कारण तैरती है?", options: ["Buoyancy (Archimedes' Principle)", "Gravity", "Friction", "Inertia"], answer: 0, explain: "Buoyancy/Archimedes' Principle ke kaaran vastu tairti hai." },
      { q: "The frequency of AC supply in India is:", hi: "भारत में AC सप्लाई की आवृत्ति कितनी है?", options: ["50 Hz", "60 Hz", "100 Hz", "40 Hz"], answer: 0, explain: "India me AC supply frequency 50 Hz hai." },
      { q: "A fuse wire is made of a material with:", hi: "फ्यूज तार किस गुण वाली सामग्री से बनता है?", options: ["Low melting point", "High melting point", "High density", "Low conductivity"], answer: 0, explain: "Fuse wire low melting point wali material (tin-lead) se banti hai." },
    ],
  },
  {
    id: "chemistry",
    name: "Chemistry",
    questions: [
      { q: "The chemical symbol of gold is:", hi: "सोने का रासायनिक प्रतीक क्या है?", options: ["Au", "Ag", "Gd", "Go"], answer: 0, explain: "Gold ka symbol Au (Aurum) hai." },
      { q: "The chemical symbol of silver is:", hi: "चांदी का रासायनिक प्रतीक क्या है?", options: ["Ag", "Au", "Si", "Sr"], answer: 0, explain: "Silver ka symbol Ag (Argentum) hai." },
      { q: "The chemical formula of water is:", hi: "पानी का रासायनिक सूत्र क्या है?", options: ["H₂O", "CO₂", "H₂O₂", "NaCl"], answer: 0, explain: "Water ka formula H₂O hai." },
      { q: "The most abundant gas in the Earth's atmosphere is:", hi: "पृथ्वी के वायुमंडल में सर्वाधिक मात्रा में कौन-सी गैस है?", options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"], answer: 0, explain: "Nitrogen (~78%) sabse zyada hai." },
      { q: "The gas responsible for the greenhouse effect is:", hi: "ग्रीनहाउस प्रभाव के लिए मुख्य गैस कौन-सी है?", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"], answer: 0, explain: "Carbon dioxide (CO₂) greenhouse effect ke liye mukhya hai." },
      { q: "The acid present in the human stomach is:", hi: "मानव पेट में कौन-सा अम्ल होता है?", options: ["Hydrochloric acid", "Sulphuric acid", "Nitric acid", "Acetic acid"], answer: 0, explain: "Stomach me Hydrochloric acid (HCl) hota hai." },
      { q: "The pH value of a neutral solution is:", hi: "उदासीन विलयन का pH मान क्या होता है?", options: ["7", "0", "14", "1"], answer: 0, explain: "Neutral solution ka pH 7 hota hai." },
      { q: "Which gas is used in balloons to make them float?", hi: "गुब्बारों को तैराने के लिए कौन-सी गैस प्रयोग होती है?", options: ["Helium", "Hydrogen", "Oxygen", "Nitrogen"], answer: 0, explain: "Helium (light, non-flammable) balloons me use hoti hai." },
      { q: "Common salt is chemically known as:", hi: "साधारण नमक रासायनिक रूप से क्या कहलाता है?", options: ["Sodium chloride", "Sodium bicarbonate", "Calcium carbonate", "Potassium chloride"], answer: 0, explain: "Common salt = Sodium chloride (NaCl)." },
      { q: "The lightest element is:", hi: "सबसे हल्का तत्व कौन-सा है?", options: ["Hydrogen", "Helium", "Lithium", "Oxygen"], answer: 0, explain: "Hydrogen sabse halka tatva hai (atomic no. 1)." },
      { q: "Baking soda is chemically:", hi: "बेकिंग सोडा रासायनिक रूप से क्या है?", options: ["Sodium bicarbonate", "Sodium carbonate", "Calcium carbonate", "Sodium chloride"], answer: 0, explain: "Baking soda = Sodium bicarbonate (NaHCO₃)." },
      { q: "Which metal is liquid at room temperature?", hi: "कमरे के तापमान पर कौन-सी धातु द्रव अवस्था में होती है?", options: ["Mercury", "Iron", "Copper", "Aluminium"], answer: 0, explain: "Mercury (Para) room temperature par liquid hai." },
      { q: "The process of rusting of iron involves:", hi: "लोहे में जंग लगने की प्रक्रिया में क्या शामिल है?", options: ["Oxidation", "Reduction", "Sublimation", "Distillation"], answer: 0, explain: "Rusting oxidation hai (iron + oxygen + water)." },
      { q: "Which gas is released during photosynthesis?", hi: "प्रकाश संश्लेषण के दौरान कौन-सी गैस निकलती है?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], answer: 0, explain: "Photosynthesis me oxygen release hoti hai." },
      { q: "The hardest natural substance is:", hi: "सबसे कठोर प्राकृतिक पदार्थ कौन-सा है?", options: ["Diamond", "Gold", "Iron", "Quartz"], answer: 0, explain: "Diamond (heera) sabse kathor prakritik padarth hai." },
      { q: "Which acid is found in lemon/citrus fruits?", hi: "नींबू/खट्टे फलों में कौन-सा अम्ल होता है?", options: ["Citric acid", "Lactic acid", "Acetic acid", "Tartaric acid"], answer: 0, explain: "Citrus fruits me Citric acid hota hai." },
      { q: "Vinegar is a dilute form of:", hi: "सिरका किसका तनु रूप है?", options: ["Acetic acid", "Citric acid", "Sulphuric acid", "Formic acid"], answer: 0, explain: "Vinegar (sirka) dilute Acetic acid hai." },
      { q: "The atomic number represents the number of:", hi: "परमाणु संख्या किसकी संख्या दर्शाती है?", options: ["Protons", "Neutrons", "Electrons + Neutrons", "Molecules"], answer: 0, explain: "Atomic number = protons ki sankhya." },
      { q: "Which gas is known as 'laughing gas'?", hi: "किस गैस को 'हँसाने वाली गैस' कहते हैं?", options: ["Nitrous oxide", "Carbon dioxide", "Methane", "Ammonia"], answer: 0, explain: "Nitrous oxide (N₂O) = laughing gas." },
      { q: "The chemical formula of table sugar (sucrose) is:", hi: "चीनी (सुक्रोज़) का रासायनिक सूत्र क्या है?", options: ["C₁₂H₂₂O₁₁", "C₆H₁₂O₆", "CO₂", "H₂O"], answer: 0, explain: "Sucrose ka formula C₁₂H₂₂O₁₁ hai." },
    ],
  },
  {
    id: "biology-1",
    name: "Biology — Human Body & Health",
    questions: [
      { q: "The powerhouse of the cell is:", hi: "कोशिका का 'ऊर्जा गृह' किसे कहते हैं?", options: ["Mitochondria", "Nucleus", "Ribosome", "Golgi body"], answer: 0, explain: "Mitochondria ko cell ka 'powerhouse' kehte hain (ATP)." },
      { q: "The largest organ of the human body is:", hi: "मानव शरीर का सबसे बड़ा अंग कौन-सा है?", options: ["Skin", "Liver", "Heart", "Brain"], answer: 0, explain: "Skin (twacha) sabse bada ang hai." },
      { q: "The largest gland in the human body is:", hi: "मानव शरीर की सबसे बड़ी ग्रंथि कौन-सी है?", options: ["Liver", "Pancreas", "Thyroid", "Pituitary"], answer: 0, explain: "Liver (yakrit) sabse badi gland hai." },
      { q: "The number of bones in an adult human body is:", hi: "वयस्क मानव शरीर में कितनी हड्डियाँ होती हैं?", options: ["206", "300", "212", "198"], answer: 0, explain: "Vayask manav me 206 haddiyan hoti hain (baby me ~300)." },
      { q: "Which vitamin is produced in the skin by sunlight?", hi: "सूर्य के प्रकाश से त्वचा में कौन-सा विटामिन बनता है?", options: ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin K"], answer: 0, explain: "Vitamin D sunlight se skin me banta hai." },
      { q: "The deficiency of Vitamin C causes:", hi: "विटामिन C की कमी से कौन-सा रोग होता है?", options: ["Scurvy", "Rickets", "Night blindness", "Beriberi"], answer: 0, explain: "Vitamin C ki kami se Scurvy hota hai." },
      { q: "The deficiency of iron causes:", hi: "लोहे की कमी से कौन-सा रोग होता है?", options: ["Anaemia", "Goitre", "Scurvy", "Rickets"], answer: 0, explain: "Iron ki kami se Anaemia (raktalpta) hota hai." },
      { q: "The deficiency of iodine causes:", hi: "आयोडीन की कमी से कौन-सा रोग होता है?", options: ["Goitre", "Anaemia", "Scurvy", "Beriberi"], answer: 0, explain: "Iodine ki kami se Goitre (ghengha) hota hai." },
      { q: "The universal blood donor group is:", hi: "सार्वभौमिक रक्तदाता समूह कौन-सा है?", options: ["O negative", "AB positive", "A positive", "B negative"], answer: 0, explain: "O negative universal donor hai." },
      { q: "The universal blood recipient group is:", hi: "सार्वभौमिक रक्त प्राप्तकर्ता समूह कौन-सा है?", options: ["AB positive", "O negative", "A negative", "B positive"], answer: 0, explain: "AB positive universal recipient hai." },
      { q: "The normal body temperature of a human is:", hi: "मानव शरीर का सामान्य तापमान कितना होता है?", options: ["37°C (98.6°F)", "40°C", "35°C", "42°C"], answer: 0, explain: "Normal body temp 37°C (98.6°F) hai." },
      { q: "Insulin is produced in the:", hi: "इंसुलिन कहाँ बनता है?", options: ["Pancreas", "Liver", "Kidney", "Stomach"], answer: 0, explain: "Insulin Pancreas me banta hai (blood sugar control)." },
      { q: "Which blood cells help in clotting?", hi: "रक्त का थक्का बनने में कौन-सी कोशिकाएँ मदद करती हैं?", options: ["Platelets", "RBC", "WBC", "Plasma"], answer: 0, explain: "Platelets (thrombocytes) blood clotting me madad karte hain." },
      { q: "The functional unit of the kidney is:", hi: "गुर्दे की कार्यात्मक इकाई कौन-सी है?", options: ["Nephron", "Neuron", "Alveoli", "Villi"], answer: 0, explain: "Nephron kidney ki functional unit hai." },
      { q: "Which organ purifies blood in the human body?", hi: "मानव शरीर में रक्त को कौन-सा अंग शुद्ध करता है?", options: ["Kidney", "Heart", "Lungs", "Liver"], answer: 0, explain: "Kidney (gurda) rakt ko shuddh karta hai." },
      { q: "The red colour of blood is due to:", hi: "रक्त का लाल रंग किसके कारण होता है?", options: ["Haemoglobin", "Plasma", "Platelets", "WBC"], answer: 0, explain: "Blood ka laal rang Haemoglobin (iron) ke kaaran hai." },
      { q: "Deficiency of Vitamin A causes:", hi: "विटामिन A की कमी से क्या होता है?", options: ["Night blindness", "Scurvy", "Rickets", "Anaemia"], answer: 0, explain: "Vitamin A ki kami se Night Blindness (ratundhi) hota hai." },
      { q: "Deficiency of Vitamin D causes:", hi: "विटामिन D की कमी से क्या होता है?", options: ["Rickets", "Scurvy", "Goitre", "Anaemia"], answer: 0, explain: "Vitamin D ki kami se Rickets (bachcho me) hota hai." },
      { q: "The smallest bone in the human body is in the:", hi: "मानव शरीर की सबसे छोटी हड्डी कहाँ है?", options: ["Ear (Stapes)", "Nose", "Hand", "Foot"], answer: 0, explain: "Sabse chhoti haddi Stapes (kaan me) hai." },
      { q: "The master gland of the human body is:", hi: "मानव शरीर की 'मास्टर ग्रंथि' कौन-सी है?", options: ["Pituitary gland", "Thyroid", "Pancreas", "Adrenal"], answer: 0, explain: "Pituitary gland ko 'master gland' kehte hain." },
    ],
  },
  {
    id: "biology-2",
    name: "Biology — Plants, Diseases & General",
    questions: [
      { q: "The process by which plants make food is:", hi: "पौधे भोजन बनाने की प्रक्रिया को क्या कहते हैं?", options: ["Photosynthesis", "Respiration", "Transpiration", "Digestion"], answer: 0, explain: "Photosynthesis (prakash sanshleshan) se paudhe bhojan banate hain." },
      { q: "The green pigment in plants is:", hi: "पौधों में हरा वर्णक क्या है?", options: ["Chlorophyll", "Haemoglobin", "Carotene", "Xanthophyll"], answer: 0, explain: "Chlorophyll (haritima) plants me hara pigment hai." },
      { q: "Which part of the plant conducts photosynthesis?", hi: "पौधे का कौन-सा भाग प्रकाश संश्लेषण करता है?", options: ["Leaves", "Roots", "Stem", "Flower"], answer: 0, explain: "Pattiyan (leaves) photosynthesis karti hain." },
      { q: "Malaria is caused by:", hi: "मलेरिया किससे होता है?", options: ["Plasmodium (protozoa)", "Bacteria", "Virus", "Fungus"], answer: 0, explain: "Malaria Plasmodium (protozoa) se hota hai (female Anopheles mosquito)." },
      { q: "Which disease is caused by a virus?", hi: "कौन-सा रोग वायरस से होता है?", options: ["Polio", "Tuberculosis", "Cholera", "Typhoid"], answer: 0, explain: "Polio virus se hota hai (TB, cholera, typhoid bacteria se)." },
      { q: "Tuberculosis (TB) is caused by:", hi: "क्षय रोग (TB) किससे होता है?", options: ["Bacteria", "Virus", "Fungus", "Protozoa"], answer: 0, explain: "TB bacteria (Mycobacterium tuberculosis) se hota hai." },
      { q: "The study of birds is called:", hi: "पक्षियों के अध्ययन को क्या कहते हैं?", options: ["Ornithology", "Entomology", "Ichthyology", "Herpetology"], answer: 0, explain: "Ornithology = pakshiyon ka adhyayan." },
      { q: "The study of insects is called:", hi: "कीटों के अध्ययन को क्या कहते हैं?", options: ["Entomology", "Ornithology", "Botany", "Zoology"], answer: 0, explain: "Entomology = keeton ka adhyayan." },
      { q: "The basic unit of life is the:", hi: "जीवन की मूल इकाई क्या है?", options: ["Cell", "Tissue", "Organ", "Atom"], answer: 0, explain: "Cell (koshika) jeevan ki mool unit hai." },
      { q: "DNA stands for:", hi: "DNA का पूर्ण रूप क्या है?", options: ["Deoxyribonucleic Acid", "Diribonucleic Acid", "Deoxyribose Nuclear Acid", "Double Nucleic Acid"], answer: 0, explain: "DNA = Deoxyribonucleic Acid." },
      { q: "Which gas do plants absorb during photosynthesis?", hi: "प्रकाश संश्लेषण में पौधे कौन-सी गैस अवशोषित करते हैं?", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: 0, explain: "Plants CO₂ absorb karte hain aur O₂ release karte hain." },
      { q: "Rabies is caused by:", hi: "रेबीज़ किससे होता है?", options: ["Virus", "Bacteria", "Fungus", "Protozoa"], answer: 0, explain: "Rabies virus se hota hai (dog bite)." },
      { q: "Which vitamin helps in blood clotting?", hi: "रक्त के थक्का बनने में कौन-सा विटामिन मदद करता है?", options: ["Vitamin K", "Vitamin C", "Vitamin A", "Vitamin D"], answer: 0, explain: "Vitamin K blood clotting me madad karta hai." },
      { q: "The exchange of gases in humans occurs in the:", hi: "मनुष्यों में गैसों का आदान-प्रदान कहाँ होता है?", options: ["Alveoli (lungs)", "Trachea", "Bronchi", "Nose"], answer: 0, explain: "Gas exchange Alveoli (phephdon me) hota hai." },
      { q: "Which is the longest bone in the human body?", hi: "मानव शरीर की सबसे लंबी हड्डी कौन-सी है?", options: ["Femur (thigh bone)", "Tibia", "Humerus", "Radius"], answer: 0, explain: "Femur (jaangh ki haddi) sabse lambi hai." },
      { q: "The number of chambers in the human heart is:", hi: "मानव हृदय में कितने कक्ष होते हैं?", options: ["Four", "Two", "Three", "Five"], answer: 0, explain: "Human heart me 4 chambers (2 atria + 2 ventricles) hote hain." },
      { q: "Which blood cells fight infection?", hi: "कौन-सी रक्त कोशिकाएँ संक्रमण से लड़ती हैं?", options: ["White blood cells (WBC)", "Red blood cells", "Platelets", "Plasma"], answer: 0, explain: "WBC (shwet rakt kanikaen) infection se ladti hain." },
      { q: "The process of water loss from plant leaves is:", hi: "पौधों की पत्तियों से जल की हानि की प्रक्रिया क्या है?", options: ["Transpiration", "Photosynthesis", "Respiration", "Osmosis"], answer: 0, explain: "Transpiration (vashpotsarjan) me pattiyon se paani udta hai." },
      { q: "Beriberi is caused by the deficiency of:", hi: "बेरीबेरी किसकी कमी से होता है?", options: ["Vitamin B1", "Vitamin C", "Vitamin D", "Iron"], answer: 0, explain: "Beriberi Vitamin B1 (thiamine) ki kami se hota hai." },
      { q: "Which organ is responsible for pumping blood?", hi: "रक्त पंप करने के लिए कौन-सा अंग जिम्मेदार है?", options: ["Heart", "Lungs", "Kidney", "Liver"], answer: 0, explain: "Heart (hriday) rakt pump karta hai." },
    ],
  },
  {
    id: "science-misc",
    name: "General Science — Mixed",
    questions: [
      { q: "Which instrument is used to detect and measure radiation?", hi: "विकिरण का पता लगाने और मापने का यंत्र कौन-सा है?", options: ["Geiger counter", "Barometer", "Ammeter", "Thermometer"], answer: 0, explain: "Geiger counter radiation naapta hai." },
      { q: "The chemical used in photography is:", hi: "फोटोग्राफी में प्रयुक्त रसायन कौन-सा है?", options: ["Silver bromide", "Sodium chloride", "Calcium carbonate", "Copper sulphate"], answer: 0, explain: "Silver bromide/halides photography me use hote hain." },
      { q: "LPG (cooking gas) mainly contains:", hi: "LPG (रसोई गैस) में मुख्यतः क्या होता है?", options: ["Butane and Propane", "Methane", "Ethane", "Hydrogen"], answer: 0, explain: "LPG me mainly Butane aur Propane hote hain." },
      { q: "CNG stands for:", hi: "CNG का पूर्ण रूप क्या है?", options: ["Compressed Natural Gas", "Cooking Natural Gas", "Carbon Natural Gas", "Clean Natural Gas"], answer: 0, explain: "CNG = Compressed Natural Gas (mainly methane)." },
      { q: "The alloy 'brass' is made of copper and:", hi: "मिश्रधातु 'पीतल' तांबा और किससे बनती है?", options: ["Zinc", "Tin", "Iron", "Nickel"], answer: 0, explain: "Brass (pital) = Copper + Zinc." },
      { q: "The alloy 'bronze' is made of copper and:", hi: "मिश्रधातु 'कांसा' तांबा और किससे बनती है?", options: ["Tin", "Zinc", "Iron", "Lead"], answer: 0, explain: "Bronze (kansa) = Copper + Tin." },
      { q: "Stainless steel contains iron, chromium and:", hi: "स्टेनलेस स्टील में लोहा, क्रोमियम और क्या होता है?", options: ["Nickel", "Zinc", "Tin", "Copper"], answer: 0, explain: "Stainless steel = Iron + Chromium + Nickel." },
      { q: "Which is a renewable source of energy?", hi: "कौन-सा ऊर्जा का नवीकरणीय स्रोत है?", options: ["Solar energy", "Coal", "Petroleum", "Natural gas"], answer: 0, explain: "Solar energy renewable (navikarniya) source hai." },
      { q: "The unit of loudness of sound is:", hi: "ध्वनि की प्रबलता की इकाई क्या है?", options: ["Decibel", "Hertz", "Watt", "Newton"], answer: 0, explain: "Sound loudness ki unit Decibel (dB) hai." },
      { q: "Which vitamin is water-soluble?", hi: "कौन-सा विटामिन जल में घुलनशील है?", options: ["Vitamin C", "Vitamin A", "Vitamin D", "Vitamin K"], answer: 0, explain: "Vitamin C (aur B) water-soluble hain (A, D, E, K fat-soluble)." },
      { q: "The device that converts solar energy to electricity is:", hi: "सौर ऊर्जा को बिजली में बदलने वाला उपकरण कौन-सा है?", options: ["Solar cell", "Dynamo", "Transformer", "Battery"], answer: 0, explain: "Solar cell (photovoltaic) surya urja ko bijli me badalti hai." },
      { q: "The gas filled in electric bulbs is:", hi: "बिजली के बल्ब में कौन-सी गैस भरी जाती है?", options: ["Argon/Nitrogen (inert)", "Oxygen", "Carbon dioxide", "Hydrogen"], answer: 0, explain: "Bulb me inert gas (Argon/Nitrogen) bhari jaati hai (filament ki raksha)." },
      { q: "The main component of natural gas is:", hi: "प्राकृतिक गैस का मुख्य घटक क्या है?", options: ["Methane", "Ethane", "Propane", "Butane"], answer: 0, explain: "Natural gas ka mukhya ghatak Methane hai." },
      { q: "Which metal is the best conductor of electricity?", hi: "कौन-सी धातु बिजली की सबसे अच्छी चालक है?", options: ["Silver", "Copper", "Gold", "Aluminium"], answer: 0, explain: "Silver bijli ki sabse achhi conductor hai." },
      { q: "The nuclear reactor uses which fuel?", hi: "नाभिकीय रिएक्टर में कौन-सा ईंधन प्रयोग होता है?", options: ["Uranium", "Coal", "Petrol", "Diesel"], answer: 0, explain: "Nuclear reactor me Uranium fuel use hota hai." },
      { q: "The process of converting milk into curd involves:", hi: "दूध को दही में बदलने की प्रक्रिया में क्या शामिल है?", options: ["Bacteria (Lactobacillus)", "Virus", "Fungus", "Yeast"], answer: 0, explain: "Dahi banne me Lactobacillus bacteria kaam karte hain." },
      { q: "Which acid is used in car batteries?", hi: "कार की बैटरी में कौन-सा अम्ल प्रयोग होता है?", options: ["Sulphuric acid", "Nitric acid", "Hydrochloric acid", "Acetic acid"], answer: 0, explain: "Car battery me Sulphuric acid (H₂SO₄) use hota hai." },
      { q: "The unit of frequency is:", hi: "आवृत्ति की इकाई क्या है?", options: ["Hertz", "Decibel", "Watt", "Joule"], answer: 0, explain: "Frequency ki unit Hertz (Hz) hai." },
      { q: "Which is the most reactive metal?", hi: "सबसे अधिक क्रियाशील धातु कौन-सी है?", options: ["Potassium", "Iron", "Copper", "Gold"], answer: 0, explain: "Potassium (aur Sodium) bahut reactive metals hain." },
      { q: "The 'father of modern chemistry' is:", hi: "'आधुनिक रसायन विज्ञान का जनक' किसे कहते हैं?", options: ["Antoine Lavoisier", "Dalton", "Mendeleev", "Rutherford"], answer: 0, explain: "Antoine Lavoisier ko 'father of modern chemistry' kaha jaata hai." },
    ],
  },
];
